# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""`fluid contract digest` — the producer for consumes[].upstreamDigest.

0.7.6 made ``upstreamDigest`` REQUIRED whenever ``upstreamWorkspace`` is
set (via ``dependentRequired``), and shipped no way to obtain the value:
``compute_contract_digest`` was reachable only from inside the federation
fetcher. The schema demanded a number nobody could produce.

The test that matters here is the round-trip — that what this command
prints is byte-identical to what ``fluid apply``'s federation gate
computes for the same upstream. A digest command that produced a
*different* digest would be worse than none, because the pin would look
authoritative and fail every apply.
"""

from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import patch

import pytest
import yaml

pytestmark = pytest.mark.unit


UPSTREAM = {
    "fluidVersion": "0.7.6",
    "kind": "DataProduct",
    "id": "telco.orders",
    "name": "Telco Orders",
    "domain": "sales",
    "metadata": {"layer": "Bronze", "owner": {"team": "telco", "email": "t@example.com"}},
    "exposes": [
        {
            "exposeId": "orders",
            "kind": "table",
            "version": "1.0.0",
            "binding": {
                "platform": "local",
                "format": "parquet",
                "location": {"database": "bronze", "table": "orders"},
            },
            "contract": {"schema": [{"name": "id", "type": "integer", "required": True}]},
        }
    ],
}


def _run(args_list, tmp_path):
    """Drive the real CLI parser, not the handler directly."""
    from fluid_build.cli import build_parser

    parser = build_parser()
    args = parser.parse_args(args_list)
    import logging

    return args.func(args, logging.getLogger("test"))


@pytest.fixture
def upstream_file(tmp_path: Path) -> Path:
    p = tmp_path / "upstream.fluid.yaml"
    p.write_text(yaml.safe_dump(UPSTREAM, sort_keys=True), encoding="utf-8")
    return p


class TestDigestMatchesTheFederationGate:
    def test_printed_digest_equals_what_the_federation_fetcher_computes(
        self, upstream_file, capsys
    ):
        """The round-trip. If these ever diverge the pin is useless."""
        rc = _run(["contract", "digest", str(upstream_file)], upstream_file.parent)
        printed = capsys.readouterr().out.strip().splitlines()[-1]
        assert rc == 0

        from fluid_build.forge.federation import FederatedWorkspace, _fetch_digest_via_git

        ws = FederatedWorkspace(
            id="telco", kind="git_registry", endpoint="https://git.example.invalid/telco"
        )
        with patch(
            "fluid_build.forge.federation._git_read_contract",
            return_value=upstream_file.read_text(encoding="utf-8"),
        ):
            fetched = _fetch_digest_via_git(ws, "telco.orders", "1")

        assert printed == fetched, (
            "the digest this command prints must be the one `fluid apply` compares "
            f"against; got {printed!r} vs {fetched!r}"
        )

    def test_digest_is_stable_across_reformatting(self, upstream_file, tmp_path, capsys):
        """The property federation depends on.

        Peers format the same contract differently -- key order, indent,
        quoting, comments. If the digest moved with formatting, every
        upstream `yamlfmt` run would page the downstream team.
        """
        _run(["contract", "digest", str(upstream_file)], tmp_path)
        first = capsys.readouterr().out.strip().splitlines()[-1]

        hostile = tmp_path / "reformatted.yaml"
        hostile.write_text(
            "# regenerated by a peer's formatter\n"
            + yaml.safe_dump(UPSTREAM, sort_keys=False, indent=4),
            encoding="utf-8",
        )
        _run(["contract", "digest", str(hostile)], tmp_path)
        second = capsys.readouterr().out.strip().splitlines()[-1]

        assert first == second, "formatting-only change must not move the digest"

    def test_a_real_content_change_moves_the_digest(self, upstream_file, tmp_path, capsys):
        """The converse -- otherwise the pin would detect nothing."""
        _run(["contract", "digest", str(upstream_file)], tmp_path)
        before = capsys.readouterr().out.strip().splitlines()[-1]

        changed = json.loads(json.dumps(UPSTREAM))
        changed["exposes"][0]["contract"]["schema"].append({"name": "customer_id", "type": "string"})
        other = tmp_path / "changed.yaml"
        other.write_text(yaml.safe_dump(changed, sort_keys=True), encoding="utf-8")
        _run(["contract", "digest", str(other)], tmp_path)
        after = capsys.readouterr().out.strip().splitlines()[-1]

        assert before != after


class TestOutputShape:
    def test_bare_form_is_pipeable(self, upstream_file, capsys):
        """Exactly one line, the digest, nothing decorative -- it is meant
        to be pasted or piped straight into a contract."""
        _run(["contract", "digest", str(upstream_file)], upstream_file.parent)
        out = capsys.readouterr().out.strip()
        assert out.startswith("sha256:")
        assert len(out.split("\n")) == 1
        assert len(out) == len("sha256:") + 64

    def test_json_form_parses(self, upstream_file, capsys):
        _run(["contract", "digest", str(upstream_file), "--json"], upstream_file.parent)
        payload = json.loads(capsys.readouterr().out.strip())
        assert payload["digest"].startswith("sha256:")
        assert payload["path"].endswith("upstream.fluid.yaml")

    def test_the_digest_satisfies_the_schema_pattern(self, upstream_file, capsys):
        """What it prints must be accepted by the field it exists to fill."""
        import re

        from fluid_build.schema_manager import SchemaManager

        _run(["contract", "digest", str(upstream_file)], upstream_file.parent)
        digest = capsys.readouterr().out.strip()

        schema = SchemaManager().get_schema("0.7.6")
        pattern = schema["$defs"]["consumeRef"]["properties"]["upstreamDigest"]["pattern"]
        assert re.match(pattern, digest), f"{digest!r} does not match {pattern!r}"


class TestFailureModes:
    def test_missing_file_is_a_typed_error(self, tmp_path):
        from fluid_build.cli._common import CLIError

        with pytest.raises(CLIError) as exc:
            _run(["contract", "digest", str(tmp_path / "nope.yaml")], tmp_path)
        assert exc.value.event == "digest_contract_not_found"

    def test_a_non_mapping_document_is_rejected(self, tmp_path):
        from fluid_build.cli._common import CLIError

        bad = tmp_path / "list.yaml"
        bad.write_text("- just\n- a\n- list\n", encoding="utf-8")
        with pytest.raises(CLIError) as exc:
            _run(["contract", "digest", str(bad)], tmp_path)
        assert exc.value.event == "digest_contract_not_a_mapping"
