# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate dbt's ``catalogs.yml`` from a FLUID contract's Iceberg exposes.

dbt writes the Iceberg *table entry* but explicitly does not create the
infrastructure it depends on. Its own documentation puts the external volume,
the catalog integration, the IAM role Snowflake assumes to read Glue, and the
catalog-linked database on the user. FLUID already provisions that class of
resource, so emitting ``catalogs.yml`` here is the half that points dbt at what
``fluid apply`` created.

**Schema version.** This emits dbt's *shipped* v1 shape, the one dbt Core 1.10+
actually parses:

    catalogs:
      - name: <catalog>
        active_write_integration: <integration>
        write_integrations:
          - name: <integration>
            table_format: iceberg
            catalog_type: built_in | iceberg_rest
            external_volume: <name>          # built_in only
            adapter_properties: {...}

A v2 shape is proposed in dbt-labs/dbt-core Discussion #12723 which drops
``write_integrations`` and nests configuration under warehouse keys. It is not
released and lands in dbt Fusion first, so emitting it today would produce a
file no released dbt can parse. :func:`_render_v1` is deliberately isolated so a
``_render_v2`` can sit beside it once that ships.

**Adapter scope.** Snowflake only, for now. dbt also supports Iceberg on
Databricks and BigQuery, but their ``catalogs.yml`` shapes differ and are not
verified here. Emitting a guessed shape is worse than emitting nothing, so other
adapters return ``None`` and the file is simply not written.

**Zero drift.** Catalog identity comes from
:func:`fluid_build.providers._iceberg_catalog.resolve_iceberg_catalog`, the same
resolver the streaming Iceberg sink uses, so the dbt catalog and the Kafka
Connect / Debezium sinks can never disagree about which table they mean. The
external volume name comes from
:func:`fluid_build.providers._iceberg_catalog.iceberg_external_volume_name`,
which the Snowflake IaC emitter also calls, so the volume FLUID creates is
exactly the volume this file references.
"""

from __future__ import annotations

import hashlib
from typing import Any, Dict, List, Mapping, Optional

import yaml

from fluid_build.providers._iceberg_catalog import (
    iceberg_external_volume_name,
    resolve_iceberg_catalog,
)

_HEADER = (
    "# Generated by fluid generate. Do not edit manually.\n# Regenerate with: fluid generate\n\n"
)

#: ``binding.format`` values that mark an expose as an Iceberg table. The
#: alias normalises to ``iceberg`` upstream, but the IaC validator accepts both,
#: so accept both here too rather than disagreeing with it.
_ICEBERG_FORMATS = frozenset({"iceberg", "iceberg_table"})

#: dbt's Snowflake adapter accepts exactly these two catalog types.
_CATALOG_TYPE_BUILT_IN = "built_in"
_CATALOG_TYPE_REST = "iceberg_rest"

#: ``location.catalog`` values that mean "an external catalog", i.e. anything
#: other than Snowflake's own Horizon. Anything here maps to ``iceberg_rest``;
#: an absent or Snowflake-managed catalog maps to ``built_in``.
_EXTERNAL_CATALOGS = frozenset({"glue", "polaris", "unity", "rest", "iceberg_rest", "nessie"})

#: Only Snowflake's shape is verified against dbt's documentation.
_SUPPORTED_ADAPTERS = frozenset({"snowflake"})


def _is_iceberg_expose(expose: Mapping[str, Any]) -> bool:
    binding = expose.get("binding") or {}
    return str(binding.get("format") or "").lower() in _ICEBERG_FORMATS


def _catalog_names(expose_id: str, seen: set) -> tuple[str, str]:
    """``(catalog name, write-integration name)`` for an expose.

    Deterministic so regenerating a project produces a byte-identical file and
    a model's ``catalog:`` config keeps resolving across runs. ASCII-only fold,
    matching the identifier discipline in ``_iceberg_catalog._ident_core``.

    ``seen`` disambiguates: the fold collapses separators, so exposeIds like
    ``a.b`` and ``a_b`` would otherwise yield two catalogs with the same name
    in one file, which dbt would treat as a duplicate definition.
    """
    safe = "".join(
        c if ("a" <= c.lower() <= "z" or c.isdigit() or c == "_") else "_" for c in expose_id
    )
    safe = safe.strip("_").lower() or "fluid"
    if safe in seen:
        digest = hashlib.sha256(expose_id.encode("utf-8")).hexdigest()[:6]
        safe = f"{safe}_{digest}"
    seen.add(safe)
    return f"{safe}_catalog", f"{safe}_write_integration"


def _adapter_properties(
    resolved: Any,
    location: Mapping[str, Any],
    *,
    catalog_type: str,
) -> Dict[str, Any]:
    """Only properties we can actually derive. Never invent defaults.

    dbt applies its own defaults for anything omitted, so emitting a guess here
    would silently override the adapter rather than defer to it.
    """
    props: Dict[str, Any] = {}
    if catalog_type != _CATALOG_TYPE_REST:
        return props

    # A REST catalog on Snowflake is reached through a catalog-linked database.
    linked = location.get("glue_database") or location.get("database")
    if linked:
        props["catalog_linked_database"] = str(linked)
    if str(getattr(resolved, "catalog_type", "") or "").lower() == "glue":
        props["catalog_linked_database_type"] = "glue"
    return props


def _write_integration(
    contract: Mapping[str, Any],
    expose: Mapping[str, Any],
    *,
    integration_name: str,
) -> Dict[str, Any]:
    binding = expose.get("binding") or {}
    location = binding.get("location") or {}
    resolved = resolve_iceberg_catalog(binding, contract=contract)

    explicit_catalog = str(location.get("catalog") or "").lower()
    is_external = explicit_catalog in _EXTERNAL_CATALOGS
    catalog_type = _CATALOG_TYPE_REST if is_external else _CATALOG_TYPE_BUILT_IN

    integration: Dict[str, Any] = {
        "name": integration_name,
        "table_format": "iceberg",
        "catalog_type": catalog_type,
    }

    if catalog_type == _CATALOG_TYPE_BUILT_IN:
        # Snowflake Horizon writes through an EXTERNAL VOLUME that dbt will not
        # create. The name is derived, not read from the contract, because
        # bindingLocation is additionalProperties:false and has no slot for it.
        integration["external_volume"] = iceberg_external_volume_name(contract, binding)

    props = _adapter_properties(resolved, location, catalog_type=catalog_type)
    if props:
        integration["adapter_properties"] = props
    return integration


def _render_v1(catalogs: List[Dict[str, Any]]) -> str:
    return _HEADER + yaml.dump(
        {"catalogs": catalogs}, sort_keys=False, default_flow_style=False, width=100
    )


def generate_catalogs_yml(
    contract: Dict[str, Any],
    build: Dict[str, Any],
) -> Optional[str]:
    """Render ``catalogs.yml``, or ``None`` when there is nothing to write.

    Returns ``None`` when the contract has no Iceberg expose, or when the
    build's adapter is not one whose shape has been verified. In both cases the
    caller simply omits the file, which is what dbt expects when a project has
    no external catalogs.
    """
    from . import _types as _types

    if _types.adapter_for_build(build) not in _SUPPORTED_ADAPTERS:
        return None

    exposes = contract.get("exposes") or []
    catalogs: List[Dict[str, Any]] = []
    seen_names: set = set()
    for expose in exposes:
        if not isinstance(expose, Mapping) or not _is_iceberg_expose(expose):
            continue
        expose_id = str(expose.get("exposeId") or expose.get("id") or "")
        if not expose_id:
            continue
        catalog_name, integration_name = _catalog_names(expose_id, seen_names)
        catalogs.append(
            {
                "name": catalog_name,
                "active_write_integration": integration_name,
                "write_integrations": [
                    _write_integration(contract, expose, integration_name=integration_name)
                ],
            }
        )

    if not catalogs:
        return None
    return _render_v1(catalogs)
