# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate dbt's ``catalogs.yml`` from a FLUID contract's Iceberg exposes.

dbt writes the Iceberg *table entry* but explicitly does not create the
infrastructure it depends on. Its own documentation puts the external volume,
the catalog integration, the IAM role Snowflake assumes to read Glue, and the
catalog-linked database on the user. FLUID already provisions that class of
resource, so emitting ``catalogs.yml`` here is the half that points dbt at what
``fluid apply`` created.

**Schema version.** This emits dbt's *shipped* v1 shape, the one dbt Core 1.10+
actually parses:

    catalogs:
      - name: <catalog>
        active_write_integration: <integration>
        write_integrations:
          - name: <integration>
            table_format: iceberg
            catalog_type: built_in | iceberg_rest
            external_volume: <name>          # built_in only
            adapter_properties: {...}

A v2 shape is proposed in dbt-labs/dbt-core Discussion #12723 which drops
``write_integrations`` and nests configuration under warehouse keys. It is not
released and lands in dbt Fusion first, so emitting it today would produce a
file no released dbt can parse. :func:`_render_v1` is deliberately isolated so a
``_render_v2`` can sit beside it once that ships.

**Adapter scope.** Snowflake and BigQuery. Their shapes genuinely differ:
Snowflake's ``external_volume`` is an object NAME (an EXTERNAL VOLUME that must
exist), while BigQuery's is a bare ``gs://`` URI, and BigQuery adds
``file_format``. Databricks is not covered because its shape is not verified
here, and emitting a guessed shape is worse than emitting nothing, so it
returns ``None`` and the file is simply not written.

**Zero drift.** Which catalog an expose lives in comes from the catalog-kind
table in :mod:`fluid_build.providers._iceberg_catalog`
(:func:`~fluid_build.providers._iceberg_catalog.binding_catalog_kind` read
through :func:`~fluid_build.providers._iceberg_catalog.catalog_kind_info`), the
same table the streaming Iceberg sink's resolver and the AWS / Snowflake IaC
emitters read, so dbt, the Kafka Connect / Debezium sinks and the provisioned
infrastructure can never disagree about which catalog a table is in. The
external volume name comes from
:func:`fluid_build.providers._iceberg_catalog.iceberg_external_volume_name`,
which the Snowflake IaC emitter also calls, so the volume FLUID creates is
exactly the volume this file references.

**Unreachable catalogs.** An expose whose catalog the adapter has no
integration for (Hive, JDBC, Hadoop or DynamoDB on Snowflake; anything but
BigLake metastore on BigQuery) is omitted with a warning rather than mapped to
the nearest shape. A guessed integration has dbt write a second table under
the name the catalog already owns; ``fluid validate`` is where the combination
is refused.
"""

from __future__ import annotations

import hashlib
import logging
from typing import Any, Dict, List, Mapping, Optional

import yaml

from fluid_build.providers._iceberg_catalog import (
    FAMILY_GLUE,
    CatalogKind,
    binding_catalog_kind,
    canonical_catalog_kind,
    catalog_kind_info,
    iceberg_external_volume_name,
    iceberg_storage_uri,
    known_catalog_kinds,
)

logger = logging.getLogger(__name__)

_HEADER = (
    "# Generated by fluid generate. Do not edit manually.\n# Regenerate with: fluid generate\n\n"
)

#: ``binding.format`` values that mark an expose as an Iceberg table. The
#: alias normalises to ``iceberg`` upstream, but the IaC validator accepts both,
#: so accept both here too rather than disagreeing with it.
_ICEBERG_FORMATS = frozenset({"iceberg", "iceberg_table"})

#: dbt's Snowflake adapter accepts exactly these two catalog types.
_CATALOG_TYPE_BUILT_IN = "built_in"
_CATALOG_TYPE_REST = "iceberg_rest"

#: The external-vs-managed split is not decided in this module. It is the
#: ``snowflake_catalog_type`` column of the catalog-kind table, which the
#: Snowflake IaC emitter partitions on too: ``iceberg_rest`` for a catalog
#: external to Snowflake, ``built_in`` for Snowflake-managed (including an
#: absent catalog on ``platform: snowflake``, and an unknown value, the
#: historic fallback ``fluid validate`` reports), and ``None`` for a catalog
#: Snowflake has no integration for. The two sides must partition identically
#: or this file references a volume the IaC never creates. A hand-kept set here
#: is how ``catalog: lakekeeper`` used to fall through to ``built_in`` while
#: the streaming sink wrote the same table over REST.

#: BigQuery's only catalog type. dbt's docs are explicit that the metastore
#: itself needs no setup because it is built into BigQuery: the prerequisite
#: is the GCS bucket, which the GCP IaC emitter creates.
_CATALOG_TYPE_BIGLAKE = "biglake_metastore"

#: The catalog kind ``biglake_metastore`` IS. dbt-bigquery cannot point a
#: model at any other Iceberg catalog, so an expose naming one is omitted.
_BIGLAKE_KIND = "bigquery"

#: Adapters whose shape is verified against dbt's documentation. Databricks
#: is deliberately absent.
_SUPPORTED_ADAPTERS = frozenset({"snowflake", "bigquery"})


def _is_iceberg_expose(expose: Mapping[str, Any]) -> bool:
    binding = expose.get("binding") or {}
    return str(binding.get("format") or "").lower() in _ICEBERG_FORMATS


def _catalog_names(expose_id: str, seen: set) -> tuple[str, str]:
    """``(catalog name, write-integration name)`` for an expose.

    Deterministic so regenerating a project produces a byte-identical file and
    a model's ``catalog:`` config keeps resolving across runs. ASCII-only fold,
    matching the identifier discipline in ``_iceberg_catalog._ident_core``.

    ``seen`` disambiguates: the fold collapses separators, so exposeIds like
    ``a.b`` and ``a_b`` would otherwise yield two catalogs with the same name
    in one file, which dbt would treat as a duplicate definition.
    """
    safe = "".join(
        c if ("a" <= c.lower() <= "z" or c.isdigit() or c == "_") else "_" for c in expose_id
    )
    safe = safe.strip("_").lower() or "fluid"
    if safe in seen:
        digest = hashlib.sha256(expose_id.encode("utf-8")).hexdigest()[:6]
        safe = f"{safe}_{digest}"
    seen.add(safe)
    return f"{safe}_catalog", f"{safe}_write_integration"


def _adapter_properties(info: CatalogKind, location: Mapping[str, Any]) -> Dict[str, Any]:
    """Only properties we can actually derive. Never invent defaults.

    dbt applies its own defaults for anything omitted, so emitting a guess here
    would silently override the adapter rather than defer to it.
    """
    props: Dict[str, Any] = {}
    if info.snowflake_catalog_type != _CATALOG_TYPE_REST:
        return props

    # A REST catalog on Snowflake is reached through a catalog-linked database.
    linked = location.get("glue_database") or location.get("database")
    if linked:
        props["catalog_linked_database"] = str(linked)
    # Glue only. dbt documents ``glue`` as the one value, and dbt-snowflake's
    # create macro branches on exactly ``== 'glue'`` (Glue needs a multi-step
    # create instead of CTAS). Its v2-catalog translation also maps unity to
    # ``unity``, but no macro reads any other value, so emitting it would add
    # an undocumented key that changes nothing.
    if info.family == FAMILY_GLUE:
        props["catalog_linked_database_type"] = "glue"
    return props


def _reachable_kinds(adapter: str) -> str:
    """The catalog kinds ``adapter`` can write through, for a warning."""
    if adapter == "bigquery":
        return f"{_BIGLAKE_KIND} (or omit location.catalog)"
    kinds = [
        k
        for k in known_catalog_kinds()
        if canonical_catalog_kind(k) == k and catalog_kind_info(k).snowflake_catalog_type
    ]
    return ", ".join(kinds) + " (or omit location.catalog for a Snowflake-managed table)"


def _warn_unreachable(expose_id: str, kind: str, adapter: str) -> None:
    logger.warning(
        "catalogs.yml: omitting expose %r: dbt-%s has no catalog integration for "
        "location.catalog %r, and a guessed one would write a second table under "
        "the name that catalog owns. Use one of: %s.",
        expose_id,
        adapter,
        kind,
        _reachable_kinds(adapter),
    )


def _bigquery_write_integration(
    contract: Mapping[str, Any],
    binding: Mapping[str, Any],
    *,
    integration_name: str,
    expose_id: str = "",
) -> Optional[Dict[str, Any]]:
    """BigQuery's shape: ``biglake_metastore`` over a ``gs://`` URI.

    Unlike Snowflake, ``external_volume`` here is the storage URI itself, not
    the name of an object that must already exist, and ``file_format`` is
    required. Returns ``None`` when no bucket is derivable, since a
    ``biglake_metastore`` integration without storage is not usable.

    Also returns ``None`` when ``location.catalog`` names a catalog other than
    BigLake metastore. ``biglake_metastore`` is dbt-bigquery's only catalog
    type, so emitting it for ``catalog: lakekeeper`` had dbt create a BigLake
    table under the name the streaming sink commits to in Lakekeeper. This
    reads the explicit value only, not :func:`binding_catalog_kind`: an absent
    catalog has always meant BigLake here, whatever the platform default says.
    """
    kind = canonical_catalog_kind((binding.get("location") or {}).get("catalog"))
    if kind and kind != _BIGLAKE_KIND:
        _warn_unreachable(expose_id, kind, "bigquery")
        return None

    storage_uri = iceberg_storage_uri(binding, scheme="gs")
    if not storage_uri:
        return None
    return {
        "name": integration_name,
        "external_volume": storage_uri,
        "table_format": "iceberg",
        "file_format": "parquet",
        "catalog_type": _CATALOG_TYPE_BIGLAKE,
    }


def _write_integration(
    contract: Mapping[str, Any],
    expose: Mapping[str, Any],
    *,
    integration_name: str,
    expose_id: str = "",
) -> Optional[Dict[str, Any]]:
    """Snowflake's shape, ``built_in`` or ``iceberg_rest`` per the kind table.

    Returns ``None`` for a catalog Snowflake has no integration for (Hive,
    JDBC, Hadoop, DynamoDB), which the caller omits exactly as it omits an
    underivable BigQuery expose.
    """
    binding = expose.get("binding") or {}
    location = binding.get("location") or {}
    # The binding's kind, not the raw ``location.catalog`` string: it folds
    # spelling (``Lakekeeper``, ``ICEBERG_REST``) and applies the platform
    # default the IaC emitters apply. An absent catalog on ``platform:
    # snowflake`` is Snowflake-managed (built_in). On ``platform: aws`` it is
    # the Glue table the AWS IaC creates; ``built_in`` there named a volume
    # nothing creates, since the Snowflake IaC only serves Snowflake exposes.
    kind = binding_catalog_kind(binding)
    info = catalog_kind_info(kind)
    catalog_type = info.snowflake_catalog_type
    if catalog_type is None:
        _warn_unreachable(expose_id, kind, "snowflake")
        return None

    integration: Dict[str, Any] = {
        "name": integration_name,
        "table_format": "iceberg",
        "catalog_type": catalog_type,
    }

    if catalog_type == _CATALOG_TYPE_BUILT_IN:
        # Snowflake Horizon writes through an EXTERNAL VOLUME that dbt will not
        # create. The name is derived, not read from the contract, because
        # bindingLocation is additionalProperties:false and has no slot for it.
        integration["external_volume"] = iceberg_external_volume_name(contract, binding)

    props = _adapter_properties(info, location)
    if props:
        integration["adapter_properties"] = props
    return integration


def _render_v1(catalogs: List[Dict[str, Any]]) -> str:
    return _HEADER + yaml.dump(
        {"catalogs": catalogs}, sort_keys=False, default_flow_style=False, width=100
    )


def generate_catalogs_yml(
    contract: Dict[str, Any],
    build: Dict[str, Any],
) -> Optional[str]:
    """Render ``catalogs.yml``, or ``None`` when there is nothing to write.

    Returns ``None`` when the contract has no Iceberg expose, or when the
    build's adapter is not one whose shape has been verified. In both cases the
    caller simply omits the file, which is what dbt expects when a project has
    no external catalogs.
    """
    from . import _types as _types

    adapter = _types.adapter_for_build(build)
    if adapter not in _SUPPORTED_ADAPTERS:
        return None

    exposes = contract.get("exposes") or []
    catalogs: List[Dict[str, Any]] = []
    seen_names: set = set()
    for expose in exposes:
        if not isinstance(expose, Mapping) or not _is_iceberg_expose(expose):
            continue
        expose_id = str(expose.get("exposeId") or expose.get("id") or "")
        if not expose_id:
            continue
        catalog_name, integration_name = _catalog_names(expose_id, seen_names)
        if adapter == "bigquery":
            integration = _bigquery_write_integration(
                contract,
                expose.get("binding") or {},
                integration_name=integration_name,
                expose_id=expose_id,
            )
        else:
            integration = _write_integration(
                contract, expose, integration_name=integration_name, expose_id=expose_id
            )
        if integration is None:
            # No integration this adapter can express: a BigQuery expose with
            # no derivable bucket (biglake_metastore would name storage that
            # does not exist), or a catalog the adapter cannot reach.
            continue
        catalogs.append(
            {
                "name": catalog_name,
                "active_write_integration": integration_name,
                "write_integrations": [integration],
            }
        )

    if not catalogs:
        return None
    return _render_v1(catalogs)
