# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate dbt SQL model files from FLUID contract builds."""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from ..base import GenerationResult, TransformationIntent

_HEADER = (
    "-- Generated by fluid generate — do not edit manually.\n-- Regenerate with: fluid generate\n\n"
)

try:
    from fluid_build.util.contract import get_expose_contract, get_expose_id, get_exposes
except ImportError:  # pragma: no cover

    def get_exposes(contract):
        return contract.get("exposes", [])

    def get_expose_id(expose):
        return expose.get("exposeId") or expose.get("id")

    def get_expose_contract(expose):
        return expose.get("contract")


def generate_models(
    contract: Dict[str, Any],
    build: Dict[str, Any],
    *,
    schema_context: Optional[Dict[str, Any]] = None,
    transformation_intent: Optional[TransformationIntent] = None,
) -> GenerationResult:
    """Generate SQL model files for a dbt project."""
    pattern = build.get("pattern", "hybrid-reference")

    if pattern == "multi-stage":
        return _generate_multi_stage(contract, build, transformation_intent=transformation_intent)
    elif pattern == "embedded-logic":
        return _generate_embedded(contract, build)
    else:
        # hybrid-reference: generate from AI intent or skeleton
        return _generate_hybrid(
            contract,
            build,
            schema_context=schema_context,
            transformation_intent=transformation_intent,
        )


# ---------------------------------------------------------------------------
# Hybrid-reference pattern
# ---------------------------------------------------------------------------


def _generate_hybrid(
    contract: Dict[str, Any],
    build: Dict[str, Any],
    *,
    schema_context: Optional[Dict[str, Any]] = None,
    transformation_intent: Optional[TransformationIntent] = None,
) -> GenerationResult:
    files: GenerationResult = {}

    if transformation_intent and transformation_intent.stages:
        return _generate_from_intent(contract, transformation_intent)

    # No AI intent — generate skeletons from consumes + exposes. The
    # shape depends on the chosen data modeling technique; see
    # :class:`TransformationIntent.data_modeling_technique`.  When the
    # LLM later ships real SQL via ``additional_files`` it overrides
    # these skeletons (merge-precedence swap in ``forge_modes``).
    technique = (
        transformation_intent.data_modeling_technique if transformation_intent else None
    ) or "dimensional"

    consumes = contract.get("consumes", [])
    exposes = get_exposes(contract)

    if technique == "data_vault_2":
        return _dv2_skeleton_files(contract, build, consumes, exposes)

    # Default: dimensional / Kimball stg + fct/dim skeletons.
    for consume in consumes:
        if not isinstance(consume, dict):
            continue
        source_id = consume.get("exposeId") or consume.get("id") or "source"
        model_name = f"stg_{source_id}"
        files[f"models/staging/{model_name}.sql"] = _staging_skeleton(source_id)

    for expose in exposes:
        expose_id = get_expose_id(expose) or "output"
        schema_cols = _extract_schema_columns(expose)
        staging_refs = [
            f"stg_{c.get('exposeId') or c.get('id', 'source')}"
            for c in consumes
            if isinstance(c, dict)
        ]
        files[f"models/marts/{expose_id}.sql"] = _mart_skeleton(
            expose_id, schema_cols, staging_refs
        )

    return files


def _dv2_skeleton_files(
    contract: Dict[str, Any],
    build: Dict[str, Any],
    consumes: List[Any],
    exposes: List[Any],
) -> GenerationResult:
    """Return hub / satellite / link skeleton files for a DV2 build.

    Per DV2 conventions we emit:
      - ``models/staging/hub_<source>.sql``  — hub + business-key hash
      - ``models/staging/sat_<source>_raw.sql`` — raw satellite per source
      - ``models/marts/lnk_<mart>.sql`` — link + descendants per expose
    The mart SQL reference ``hub_*`` hashes (not natural keys) and carry
    ``load_dts`` + ``record_source`` metadata so downstream consumers can
    diff history insert-only.
    """
    files: GenerationResult = {}
    for consume in consumes:
        if not isinstance(consume, dict):
            continue
        source_id = consume.get("exposeId") or consume.get("id") or "source"
        files[f"models/staging/hub_{source_id}.sql"] = _dv2_hub_skeleton(source_id)
        files[f"models/staging/sat_{source_id}_raw.sql"] = _dv2_sat_skeleton(source_id)

    for expose in exposes:
        expose_id = get_expose_id(expose) or "output"
        schema_cols = _extract_schema_columns(expose)
        hub_refs = [
            f"hub_{c.get('exposeId') or c.get('id', 'source')}"
            for c in consumes
            if isinstance(c, dict)
        ]
        files[f"models/marts/lnk_{expose_id}.sql"] = _dv2_link_skeleton(
            expose_id, schema_cols, hub_refs
        )

    return files


def _dv2_hub_skeleton(source_id: str) -> str:
    """Generate a DV2 hub skeleton for an upstream source.

    Hubs hold business-key → md5 hash-key mappings plus minimal load
    metadata.  One hub per business entity; we use the exposeId as the
    business entity identifier pending a smarter mapping.
    """
    return (
        f"{_HEADER}"
        "{{ config(materialized='table') }}\n\n"
        f"-- DV2 hub skeleton for {source_id}. Fill in the business key column.\n"
        "select\n"
        "    md5(upper(trim(cast(<business_key> as varchar)))) as hk,\n"
        "    <business_key> as business_key,\n"
        "    current_timestamp() as load_dts,\n"
        f"    '{source_id}' as record_source\n"
        f"from {{{{ source('raw', '{source_id}') }}}}\n"
        "-- TODO: replace <business_key> with the natural key column from "
        f"{source_id}.\n"
    )


def _dv2_sat_skeleton(source_id: str) -> str:
    """Generate a DV2 satellite skeleton — one satellite per upstream source."""
    return (
        f"{_HEADER}"
        "{{ config(materialized='table') }}\n\n"
        f"-- DV2 raw satellite for {source_id}. Insert-only — one row per change.\n"
        "select\n"
        "    md5(upper(trim(cast(<business_key> as varchar)))) as hk,\n"
        "    current_timestamp() as load_dts,\n"
        f"    '{source_id}' as record_source,\n"
        "    md5(concat_ws('||', cast(*  as varchar))) as hash_diff,\n"
        "    -- descriptive attributes follow\n"
        "    *\n"
        f"from {{{{ source('raw', '{source_id}') }}}}\n"
        "-- TODO: replace <business_key> and narrow the `*` projection.\n"
    )


def _dv2_link_skeleton(
    expose_id: str,
    schema_cols: List[Dict[str, str]],
    hub_refs: List[str],
) -> str:
    """Generate a DV2 link skeleton — joins hubs and projects the expose schema."""
    lines = [_HEADER, "{{ config(materialized='table') }}\n\n"]
    if schema_cols:
        lines.append("select\n")
        col_lines = [
            f"    cast(null as {_sql_type(col.get('type', 'string'))}) as {col['name']}"
            for col in schema_cols
        ]
        col_lines.append("    current_timestamp() as load_dts")
        col_lines.append(f"    '{expose_id}' as record_source")
        lines.append(",\n".join(col_lines))
        lines.append("\n\n")
    else:
        lines.append(
            "select\n"
            "    current_timestamp() as load_dts,\n"
            f"    '{expose_id}' as record_source\n"
            "    -- TODO: project output columns\n\n"
        )

    if hub_refs:
        lines.append(f"from {{{{ ref('{hub_refs[0]}') }}}}\n")
        for ref_name in hub_refs[1:]:
            lines.append(f"-- TODO: join {{ ref('{ref_name}') }} via hk\n")
    else:
        lines.append("-- TODO: add hub references\nfrom dual\n")
    lines.append("\n-- TODO: replace the null projections with real hub/satellite joins.\n")
    return "".join(lines)


def _staging_skeleton(source_id: str) -> str:
    """Generate a staging model skeleton."""
    return (
        f"{_HEADER}"
        f"{{{{ config(materialized='view') }}}}\n\n"
        f"select\n"
        f"    *\n"
        f"    -- TODO: Add column cleaning and standardization\n\n"
        f"from {{{{ source('raw', '{source_id}') }}}}\n"
    )


def _mart_skeleton(
    expose_id: str,
    schema_cols: List[Dict[str, str]],
    staging_refs: List[str],
) -> str:
    """Generate a mart model skeleton."""
    lines = [_HEADER, "{{ config(materialized='table') }}\n\n"]

    if schema_cols:
        lines.append("select\n")
        col_lines = []
        for col in schema_cols:
            col_lines.append(
                f"    cast(null as {_sql_type(col.get('type', 'string'))}) as {col['name']}"
            )
        lines.append(",\n".join(col_lines))
        lines.append("\n\n")
    else:
        lines.append("select\n    *\n    -- TODO: Define output columns\n\n")

    if staging_refs:
        lines.append(f"from {{{{ ref('{staging_refs[0]}') }}}}\n")
        for ref_name in staging_refs[1:]:
            lines.append(f"-- TODO: join {{ ref('{ref_name}') }}\n")
    else:
        lines.append("-- TODO: Add source references\nfrom dual\n")

    lines.append("\n-- TODO: Add transformation logic (joins, aggregations, filters)\n")
    return "".join(lines)


# ---------------------------------------------------------------------------
# Embedded-logic pattern
# ---------------------------------------------------------------------------


def _generate_embedded(
    contract: Dict[str, Any],
    build: Dict[str, Any],
) -> GenerationResult:
    """Wrap embedded SQL with dbt config macro."""
    properties = build.get("properties", {})
    sql = properties.get("sql", "")
    if not sql:
        return {}

    model_name = build.get("id", "main")
    content = f"{_HEADER}" f"{{{{ config(materialized='table') }}}}\n\n" f"{sql.strip()}\n"
    return {f"models/marts/{model_name}.sql": content}


# ---------------------------------------------------------------------------
# Multi-stage pattern
# ---------------------------------------------------------------------------


def _generate_multi_stage(
    contract: Dict[str, Any],
    build: Dict[str, Any],
    *,
    transformation_intent: Optional[TransformationIntent] = None,
) -> GenerationResult:
    """Generate models from multi-stage build definition."""
    files: GenerationResult = {}
    properties = build.get("properties", {})
    stages = properties.get("stages", [])

    for stage in stages:
        if not isinstance(stage, dict):
            continue

        name = stage.get("name", "unnamed")
        stage_sql = stage.get("properties", {}).get("sql", "")
        depends_on = stage.get("dependsOn", [])
        layer = _infer_layer(name)
        materialization = _layer_materialization(layer)

        if stage_sql:
            # Wrap user SQL with config macro
            content = (
                f"{_HEADER}"
                f"{{{{ config(materialized='{materialization}') }}}}\n\n"
                f"{stage_sql.strip()}\n"
            )
        else:
            # Skeleton with refs to dependencies
            ref_lines = "".join(f"-- depends on: {{{{ ref('{dep}') }}}}\n" for dep in depends_on)
            content = (
                f"{_HEADER}"
                f"{{{{ config(materialized='{materialization}') }}}}\n\n"
                f"{ref_lines}"
                f"select\n"
                f"    *\n"
                f"    -- TODO: Add transformation logic for stage '{name}'\n\n"
                f"from {{{{ ref('{depends_on[0]}') }}}}\n"
                if depends_on
                else f"{_HEADER}"
                f"{{{{ config(materialized='{materialization}') }}}}\n\n"
                f"select\n"
                f"    *\n"
                f"    -- TODO: Add transformation logic for stage '{name}'\n\n"
                f"-- TODO: Add source references\n"
            )

        files[f"models/{layer}/{name}.sql"] = content

    return files


# ---------------------------------------------------------------------------
# AI-intent-driven generation
# ---------------------------------------------------------------------------


def _generate_from_intent(
    contract: Dict[str, Any],
    intent: TransformationIntent,
) -> GenerationResult:
    """Generate full models from AI-produced TransformationIntent."""
    files: GenerationResult = {}

    for stage in intent.stages:
        name = stage.get("name", "unnamed")
        sql = stage.get("sql", "")
        layer = stage.get("layer", _infer_layer(name))
        materialization = _layer_materialization(layer)

        content = (
            f"{_HEADER}"
            f"{{{{ config(materialized='{materialization}') }}}}\n\n"
            f"{sql.strip()}\n"
            if sql
            else f"{_HEADER}"
            f"{{{{ config(materialized='{materialization}') }}}}\n\n"
            f"-- TODO: AI could not generate SQL for stage '{name}'\n"
            f"select 1\n"
        )
        files[f"models/{layer}/{name}.sql"] = content

    return files


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _infer_layer(stage_name: str) -> str:
    """Infer dbt model layer from stage name."""
    lower = stage_name.lower()
    if any(token in lower for token in ("stg_", "staging", "extract", "raw")):
        return "staging"
    if any(token in lower for token in ("int_", "intermediate", "prep")):
        return "intermediate"
    return "marts"


def _layer_materialization(layer: str) -> str:
    """Default materialization for a layer."""
    return {"staging": "view", "intermediate": "view", "marts": "table"}.get(layer, "table")


def _extract_schema_columns(expose: Dict[str, Any]) -> List[Dict[str, str]]:
    """Extract column definitions from an expose's contract.schema."""
    contract_section = get_expose_contract(expose) or {}
    schema = contract_section.get("schema", [])
    if isinstance(schema, list):
        return [
            {"name": col["name"], "type": col.get("type", "string")}
            for col in schema
            if isinstance(col, dict) and col.get("name")
        ]
    return []


def _sql_type(fluid_type: str) -> str:
    """Map FLUID type to SQL type for skeleton casts."""
    mapping = {
        "string": "varchar",
        "STRING": "varchar",
        "integer": "integer",
        "INTEGER": "integer",
        "number": "numeric",
        "NUMBER": "numeric",
        "float": "numeric",
        "FLOAT": "numeric",
        "boolean": "boolean",
        "BOOLEAN": "boolean",
        "date": "date",
        "DATE": "date",
        "timestamp": "timestamp",
        "TIMESTAMP": "timestamp",
        "datetime": "timestamp",
        "array": "varchar",  # fallback
        "object": "varchar",  # fallback
    }
    return mapping.get(fluid_type, "varchar")
