# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate ``profiles.yml`` template based on target platform."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Optional

import yaml

from .project_yml import _sanitize_project_name
from .sources import _normalize_placeholder

_HEADER = "# Generated by fluid generate — do not edit manually.\n# Regenerate with: fluid generate\n#\n# Fill in the placeholder values or use dbt env_var() for secrets.\n\n"

# Last-resort target schema when the contract declares none. ``PUBLIC`` is
# only correct when the contract really is schema-less — resolving the
# declared schema (below) takes precedence, because a profile that silently
# writes to PUBLIC builds every model in the wrong place on a green
# ``dbt debug``.
_SCHEMA_FALLBACK = (
    "{{ env_var('SNOWFLAKE_DBT_SCHEMA', env_var('SNOWFLAKE_FLUID_SCHEMA', 'PUBLIC')) }}"
)


def generate_profiles(
    contract: Dict[str, Any],
    build: Dict[str, Any],
    *,
    output_dir: Optional[Path] = None,
) -> Optional[str]:
    """Generate ``profiles.yml`` template content."""
    contract_id = contract.get("id", "fluid_project")
    profile_name = _sanitize_project_name(contract_id)

    execution = build.get("execution", {})
    runtime = execution.get("runtime", {})
    platform = runtime.get("platform", "local")

    profile = _profile_for_platform(
        platform,
        profile_name,
        output_dir=output_dir,
        schema_expr=resolve_schema_expr(contract, build),
    )
    if not profile:
        return None

    return _HEADER + yaml.dump(
        profile, default_flow_style=False, sort_keys=False, allow_unicode=True
    )


def resolve_schema_expr(
    contract: Dict[str, Any],
    build: Dict[str, Any],
) -> Optional[str]:
    """Resolve the dbt target schema the *contract* declares.

    ``profiles.yml`` used to hardcode
    ``env_var('SNOWFLAKE_DBT_SCHEMA', env_var('SNOWFLAKE_FLUID_SCHEMA', 'PUBLIC'))``
    and never look at the contract at all, so a contract declaring
    ``builds[].execution.runtime.resources.schema`` built every model into
    ``PUBLIC`` while ``dbt debug`` reported "connection ok" — the failure was
    asymmetric because ``database`` *was* resolved correctly.

    Precedence:

    1. ``builds[].execution.runtime.resources.schema`` (or ``dataset`` on
       BigQuery) — the build's own declared target.
    2. The schema on the first ``exposes[].binding.location`` — where the
       contract says its outputs land.

    ``{{ env.X }}`` / ``${X}`` placeholders are translated to dbt's
    ``env_var('X')`` by the same normaliser ``sources.py`` uses, so the two
    emitters agree on how contract placeholders reach dbt. Returns ``None``
    when the contract declares no schema, leaving the caller's env-var
    fallback in place.
    """
    execution = build.get("execution", {}) if isinstance(build, dict) else {}
    runtime = execution.get("runtime", {}) if isinstance(execution, dict) else {}
    resources = runtime.get("resources", {}) if isinstance(runtime, dict) else {}
    if isinstance(resources, dict):
        declared = resources.get("schema") or resources.get("dataset")
        normalized = _normalize_placeholder(declared)
        if normalized:
            return normalized

    for expose in contract.get("exposes", []) or []:
        if not isinstance(expose, dict):
            continue
        binding = expose.get("binding")
        if not isinstance(binding, dict):
            continue
        location = binding.get("location")
        if not isinstance(location, dict):
            continue
        normalized = _normalize_placeholder(location.get("schema") or location.get("dataset"))
        if normalized:
            return normalized

    return None


def _profile_for_platform(
    platform: str,
    profile_name: str,
    *,
    output_dir: Optional[Path] = None,
    schema_expr: Optional[str] = None,
) -> Dict[str, Any]:
    """Build a profiles.yml dict for the given platform."""
    lower = platform.lower()

    if lower in ("gcp", "bigquery"):
        return {
            profile_name: {
                "target": "dev",
                "outputs": {
                    "dev": {
                        "type": "bigquery",
                        "method": "oauth",
                        "project": "{{ env_var('GCP_PROJECT') }}",
                        "dataset": schema_expr or "analytics_dev",
                        "threads": 4,
                        "location": "US",
                    },
                    "prod": {
                        "type": "bigquery",
                        "method": "oauth",
                        "project": "{{ env_var('GCP_PROJECT') }}",
                        "dataset": schema_expr or "analytics",
                        "threads": 8,
                        "location": "US",
                    },
                },
            }
        }

    if lower in ("snowflake",):
        # All Snowflake connection parameters are sourced from env vars so
        # the same profiles.yml works across environments. The target schema
        # comes from the contract when it declares one (see
        # ``resolve_schema_expr``); the env-var chain is only the fallback
        # for a contract that declares no schema at all.
        return {
            profile_name: {
                "target": "dev",
                "outputs": {
                    "dev": {
                        "type": "snowflake",
                        "account": "{{ env_var('SNOWFLAKE_ACCOUNT') }}",
                        "user": "{{ env_var('SNOWFLAKE_USER') }}",
                        "password": "{{ env_var('SNOWFLAKE_PASSWORD') }}",
                        "role": "{{ env_var('SNOWFLAKE_ROLE') }}",
                        "database": "{{ env_var('SNOWFLAKE_DATABASE') }}",
                        "warehouse": "{{ env_var('SNOWFLAKE_WAREHOUSE') }}",
                        "schema": schema_expr or _SCHEMA_FALLBACK,
                        "threads": 4,
                    },
                },
            }
        }

    if lower in ("aws", "redshift"):
        return {
            profile_name: {
                "target": "dev",
                "outputs": {
                    "dev": {
                        "type": "redshift",
                        "host": "{{ env_var('REDSHIFT_HOST') }}",
                        "user": "{{ env_var('REDSHIFT_USER') }}",
                        "password": "{{ env_var('REDSHIFT_PASSWORD') }}",
                        "port": 5439,
                        "dbname": "analytics",
                        "schema": schema_expr or "dev",
                        "threads": 4,
                    },
                },
            }
        }

    # Default: local / DuckDB. Use a project-local absolute path when
    # the generator knows the output directory so `dbt run --project-dir`
    # works from any current working directory.
    duckdb_path = (
        str((output_dir / "dev.duckdb").resolve()) if output_dir is not None else "dev.duckdb"
    )
    return {
        profile_name: {
            "target": "dev",
            "outputs": {
                "dev": {
                    "type": "duckdb",
                    "path": duckdb_path,
                    "threads": 4,
                },
            },
        }
    }
