# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate ``schema.yml`` (dbt tests + Mesh ``access:``) from contract.

Each entry in ``exposes[]`` becomes a dbt model with:
- ``name`` — the ``exposeId``
- ``description`` — from ``exposes[].description``
- ``access: public`` — per the dbt Mesh spec (dbt-core >= 1.6). Every
  expose is by definition a public output port of the data product;
  marking the model as ``access: public`` lets downstream dbt Mesh
  consumers ``ref('other_project', 'public_model')`` reference it,
  while keeping non-exposed internal staging models at their default
  ``access: protected``. This is Q4 Option 1 of the Phase 7-rest
  design — automatic mesh annotations from ``exposes[]``, zero extra
  contract authoring work.
- ``columns[]`` — column metadata + dbt tests derived from the
  FLUID schema + DQ rules (unchanged pre-existing behaviour).

Optional ``--mesh-hub <name>`` CLI flag (wired at the
:mod:`fluid_build.cli.generate_speed_transformation` layer, not this
module): when set, also emits a ``dependencies.yml`` naming the hub
project so the generated dbt project participates in a dbt Mesh
network.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

import yaml

from ..base import GenerationResult

# The single shared contract → dbt-test mapping. Reached via module attribute
# access (``_tm.<fn>``) so a ``patch("...engines.dbt._test_mapping.<fn>")``
# flows through to every call site.
from . import _test_mapping as _tm

_HEADER = (
    "# Generated by fluid generate — do not edit manually.\n# Regenerate with: fluid generate\n\n"
)

try:
    from fluid_build.util.contract import get_expose_contract, get_expose_id, get_exposes
except ImportError:  # pragma: no cover

    def get_exposes(contract):
        return contract.get("exposes", [])

    def get_expose_id(expose):
        return expose.get("exposeId") or expose.get("id")

    def get_expose_contract(expose):
        return expose.get("contract")


def generate_schema_yml(
    contract: Dict[str, Any],
    *,
    mesh_hub: Optional[str] = None,
) -> GenerationResult:
    """Generate ``schema.yml`` (dbt tests + Mesh ``access: public``)
    and, when ``mesh_hub`` is set, a companion ``dependencies.yml``.

    Every entry in ``exposes[]`` gets ``access: public`` on its
    emitted model. Internal staging models (in ``models/staging/``)
    are NOT touched — they inherit dbt's default ``access: protected``
    so they remain invisible to cross-project ``ref('other', ...)``.

    When ``mesh_hub`` is set, also emit ``dependencies.yml`` declaring
    the hub project this data product participates in (dbt Mesh's
    hub-and-spoke pattern for cross-product lineage).
    """
    exposes = get_exposes(contract)
    if not exposes:
        # No exposes = no public surface = no schema.yml needed.
        # Still emit dependencies.yml when mesh_hub is set because
        # even a purely-consuming product participates in the hub.
        if mesh_hub:
            return _mesh_only_output(mesh_hub)
        return {}

    # All mart models go into a single schema.yml for now
    model_defs: List[Dict[str, Any]] = []

    for expose in exposes:
        if not isinstance(expose, dict):
            continue
        expose_id = get_expose_id(expose)
        if not expose_id:
            continue

        contract_section = get_expose_contract(expose) or {}
        schema_cols = contract_section.get("schema", [])
        dq = contract_section.get("dq", {})
        dq_rules = dq.get("rules", []) if isinstance(dq, dict) else []

        columns = _build_column_tests(schema_cols, dq_rules)

        model_def: Dict[str, Any] = {"name": expose_id}

        desc = expose.get("description")
        if desc:
            model_def["description"] = desc

        # Mesh annotation: every expose is a public output port by
        # definition of ``exposes``. This lets dbt-core >= 1.6
        # consumers reference the model via
        # ``ref('this_project', 'expose_id')`` from another project.
        # Internal staging models — NOT in ``exposes[]`` — inherit
        # dbt's default ``access: protected`` so they stay private
        # to this project.
        model_def["access"] = "public"

        # Semantic versioning for public interfaces: read ``version``
        # from ``exposes[].contract.version`` and thread it through.
        # dbt uses this for model-version pinning in downstream refs.
        version = contract_section.get("version")
        if version:
            model_def["latest_version"] = version
            # dbt model-versions require a ``versions`` list too.
            model_def["versions"] = [{"v": version}]

        if columns:
            model_def["columns"] = columns

        model_defs.append(model_def)

    out: GenerationResult = {}
    if model_defs:
        data = {"version": 2, "models": model_defs}
        content = _HEADER + yaml.dump(
            data, default_flow_style=False, sort_keys=False, allow_unicode=True
        )
        out["models/marts/schema.yml"] = content

    if mesh_hub:
        out.update(_mesh_only_output(mesh_hub))

    return out


def _mesh_only_output(mesh_hub: str) -> GenerationResult:
    """Emit ``dependencies.yml`` for a product participating in a hub.

    Shape (dbt-core spec):
        projects:
          - name: <hub-project-name>

    The hub project at the ``name`` needs to exist in the downstream
    dbt environment — typically by adding it as a package or installing
    it via ``dbt deps``. This file just declares the participation.
    """
    data = {"projects": [{"name": mesh_hub}]}
    content = _HEADER + yaml.dump(
        data, default_flow_style=False, sort_keys=False, allow_unicode=True
    )
    return {"dependencies.yml": content}


def _build_column_tests(
    schema_cols: List[Dict[str, Any]],
    dq_rules: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """Build dbt column test definitions from schema + DQ rules."""
    # Index DQ rules by selector (column name)
    rules_by_col: Dict[str, List[Dict[str, Any]]] = {}
    for rule in dq_rules:
        if not isinstance(rule, dict):
            continue
        selector = rule.get("selector", "")
        if selector:
            rules_by_col.setdefault(selector, []).append(rule)

    columns: List[Dict[str, Any]] = []
    seen_cols = set()

    for col in schema_cols:
        if not isinstance(col, dict):
            continue
        col_name = col.get("name")
        if not col_name:
            continue
        seen_cols.add(col_name)

        tests = _tests_for_column(col, rules_by_col.get(col_name, []))
        col_entry: Dict[str, Any] = {"name": col_name}
        if col.get("description"):
            col_entry["description"] = col["description"]
        if tests:
            col_entry["tests"] = tests
        columns.append(col_entry)

    # DQ rules on columns not in schema
    for col_name, rules in rules_by_col.items():
        if col_name in seen_cols:
            continue
        tests = _tests_for_column({"name": col_name}, rules)
        if tests:
            columns.append({"name": col_name, "tests": tests})

    return columns


def _tests_for_column(
    col_def: Dict[str, Any],
    dq_rules: List[Dict[str, Any]],
) -> List[Any]:
    """Map FLUID DQ rules + inline column constraints to dbt tests.

    Delegates to the single shared mapping (:mod:`._test_mapping`) so the engine
    path emits the *same* dbt tests as the exporter and the copilot generator
    for the same contract intent — including ``relationships`` (from a column FK
    reference), the unified numeric-range dialect, and freshness/recency, which
    this path previously did not surface.
    """
    col_name = str(col_def.get("name") or "")
    rule_tests = [
        test for rule in dq_rules if (test := _tm.forward_column_rule(rule, col_name)) is not None
    ]
    # dq-rule tests win over the generic constraint-derived form on collision.
    return _tm.merge_tests(rule_tests, _tm.constraint_tests(col_def))
