# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate ``schema.yml`` (dbt tests + Mesh ``access:``) from contract.

Each entry in ``exposes[]`` becomes a dbt model with:
- ``name`` — the ``exposeId``
- ``description`` — from ``exposes[].description``
- ``access: public`` — per the dbt Mesh spec (dbt-core >= 1.6). Every
  expose is by definition a public output port of the data product;
  marking the model as ``access: public`` lets downstream dbt Mesh
  consumers ``ref('other_project', 'public_model')`` reference it,
  while keeping non-exposed internal staging models at their default
  ``access: protected``. This is Q4 Option 1 of the Phase 7-rest
  design — automatic mesh annotations from ``exposes[]``, zero extra
  contract authoring work.
- ``columns[]`` — column metadata + dbt tests derived from the
  FLUID schema + DQ rules (unchanged pre-existing behaviour).

Optional ``--mesh-hub <name>`` CLI flag (wired at the
:mod:`fluid_build.cli.generate_speed_transformation` layer, not this
module): when set, also emits a ``dependencies.yml`` naming the hub
project so the generated dbt project participates in a dbt Mesh
network.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

import yaml

from ..base import GenerationResult

# The single shared contract → dbt-test mapping. Reached via module attribute
# access (``_tm.<fn>``) so a ``patch("...engines.dbt._test_mapping.<fn>")``
# flows through to every call site.
from . import _test_mapping as _tm

# Adapter-aware FLUID → SQL type mapping (shared with models.py skeleton
# casts). Module attribute access for the same patch-flow reason.
from . import _types as _types

# Materializations on which dbt renders constraints and supports enforced
# contracts — table/incremental only; views take name/data_type but not
# constraints. Borrowed from datacontract-cli's dbt_exporter.py
# ``_supports_constraints`` (MIT).
_CONSTRAINT_MATERIALIZATIONS = frozenset({"table", "incremental"})

_HEADER = (
    "# Generated by fluid generate — do not edit manually.\n# Regenerate with: fluid generate\n\n"
)

# The dbt YAML key under which data tests attach. dbt-core 1.8 renamed
# ``tests:`` → ``data_tests:`` ("Both are currently supported for backward
# compatibility" — docs.getdbt.com/docs/dbt-versions/core-upgrade/
# upgrading-to-v1.8); the Fusion engine (dbt v2) strict-parses and does not
# support deprecated functionality, so a Fusion user's generated project must
# carry ``data_tests:``. Emitting the modern key unconditionally (as
# datacontract-cli's dbt_exporter does) would break dbt-core <1.8, so the
# choice is threaded as a plain string from the CLI layer — which detects the
# dbt binary the user will actually run — down through every emitter.
# ``engines/`` must stay free of ``build_runners`` imports (import-linter
# tiering), hence a string option here instead of engine detection.
TESTS_KEY_LEGACY = "tests"
TESTS_KEY_MODERN = "data_tests"
VALID_TESTS_KEYS = frozenset({TESTS_KEY_LEGACY, TESTS_KEY_MODERN})


def normalize_tests_key(tests_key: Optional[str]) -> str:
    """Validate/default the dbt tests-key dialect.

    ``None`` → the legacy ``"tests"`` key (byte-identical output for every
    caller that never opts in); anything outside :data:`VALID_TESTS_KEYS`
    raises ``ValueError`` so a typo'd override fails loud instead of
    emitting a YAML key dbt silently ignores.
    """
    if tests_key is None:
        return TESTS_KEY_LEGACY
    if tests_key not in VALID_TESTS_KEYS:
        raise ValueError(
            f"invalid dbt tests key {tests_key!r}: expected one of {sorted(VALID_TESTS_KEYS)}"
        )
    return tests_key


try:
    from fluid_build.util.contract import get_expose_contract, get_expose_id, get_exposes
except ImportError:  # pragma: no cover

    def get_exposes(contract):
        return contract.get("exposes", [])

    def get_expose_id(expose):
        return expose.get("exposeId") or expose.get("id")

    def get_expose_contract(expose):
        return expose.get("contract")


def generate_schema_yml(
    contract: Dict[str, Any],
    *,
    mesh_hub: Optional[str] = None,
    model_contracts: bool = False,
    adapter: Optional[str] = None,
    tests_key: Optional[str] = None,
) -> GenerationResult:
    """Generate ``schema.yml`` (dbt tests + Mesh ``access: public``)
    and, when ``mesh_hub`` is set, a companion ``dependencies.yml``.

    Every entry in ``exposes[]`` gets ``access: public`` on its
    emitted model. Internal staging models (in ``models/staging/``)
    are NOT touched — they inherit dbt's default ``access: protected``
    so they remain invisible to cross-project ``ref('other', ...)``.

    When ``mesh_hub`` is set, also emit ``dependencies.yml`` declaring
    the hub project this data product participates in (dbt Mesh's
    hub-and-spoke pattern for cross-product lineage).

    When ``model_contracts`` is set (opt-in ``--model-contracts``),
    each expose model additionally gets a dbt model contract
    (dbt-core >= 1.5): ``config: {contract: {enforced: true}}``,
    per-column ``data_type`` (adapter-correct via ``adapter``), and
    ``constraints`` (``not_null`` for required columns, plus
    ``primary_key`` where the column is a declared key). ``dbt build``
    then FAILS whenever the model's actual output columns/types
    diverge from ``exposes[].contract.schema[]`` — build-time
    enforcement of the data contract in producer CI. Enforcement is
    applied to expose/mart models only (this module never emits
    staging models; views don't support constraints anyway).

    ``tests_key`` selects the YAML key data tests attach under —
    ``"tests"`` (legacy, default — dbt-core <1.8 only understands this)
    or ``"data_tests"`` (dbt-core >=1.8 / required by Fusion). See the
    module-level note on :data:`TESTS_KEY_MODERN`.
    """
    resolved_tests_key = normalize_tests_key(tests_key)
    exposes = get_exposes(contract)
    if not exposes:
        # No exposes = no public surface = no schema.yml needed.
        # Still emit dependencies.yml when mesh_hub is set because
        # even a purely-consuming product participates in the hub.
        if mesh_hub:
            return _mesh_only_output(mesh_hub)
        return {}

    # All mart models go into a single schema.yml for now
    model_defs: List[Dict[str, Any]] = []

    for expose in exposes:
        if not isinstance(expose, dict):
            continue
        expose_id = get_expose_id(expose)
        if not expose_id:
            continue

        contract_section = get_expose_contract(expose) or {}
        schema_cols = contract_section.get("schema", [])
        dq = contract_section.get("dq", {})
        dq_rules = dq.get("rules", []) if isinstance(dq, dict) else []

        columns, model_tests = _build_column_tests(
            schema_cols, dq_rules, tests_key=resolved_tests_key
        )

        model_def: Dict[str, Any] = {"name": expose_id}

        desc = expose.get("description")
        if desc:
            model_def["description"] = desc

        # Mesh annotation: every expose is a public output port by
        # definition of ``exposes``. This lets dbt-core >= 1.6
        # consumers reference the model via
        # ``ref('this_project', 'expose_id')`` from another project.
        # Internal staging models — NOT in ``exposes[]`` — inherit
        # dbt's default ``access: protected`` so they stay private
        # to this project.
        model_def["access"] = "public"

        # Table-wide (``selector: "*"``) rules — and freshness rules, which
        # dbt can only express at model level — attach here, not as a dbt
        # column literally named ``*``.
        if model_tests:
            model_def[resolved_tests_key] = model_tests

        # Opt-in dbt model contract (build-time schema enforcement).
        if model_contracts:
            _apply_model_contract(
                model_def, columns, schema_cols, adapter, tests_key=resolved_tests_key
            )

        # Semantic versioning for public interfaces: read ``version``
        # from ``exposes[].contract.version`` and thread it through.
        # dbt uses this for model-version pinning in downstream refs.
        version = contract_section.get("version")
        if version:
            model_def["latest_version"] = version
            # dbt model-versions require a ``versions`` list too.
            model_def["versions"] = [{"v": version}]

        if columns:
            model_def["columns"] = columns

        model_defs.append(model_def)

    out: GenerationResult = {}
    if model_defs:
        data = {"version": 2, "models": model_defs}
        content = _HEADER + yaml.dump(
            data, default_flow_style=False, sort_keys=False, allow_unicode=True
        )
        out["models/marts/schema.yml"] = content

    if mesh_hub:
        out.update(_mesh_only_output(mesh_hub))

    return out


def _mesh_only_output(mesh_hub: str) -> GenerationResult:
    """Emit ``dependencies.yml`` for a product participating in a hub.

    Shape (dbt-core spec):
        projects:
          - name: <hub-project-name>

    The hub project at the ``name`` needs to exist in the downstream
    dbt environment — typically by adding it as a package or installing
    it via ``dbt deps``. This file just declares the participation.
    """
    data = {"projects": [{"name": mesh_hub}]}
    content = _HEADER + yaml.dump(
        data, default_flow_style=False, sort_keys=False, allow_unicode=True
    )
    return {"dependencies.yml": content}


def _apply_model_contract(
    model_def: Dict[str, Any],
    columns: List[Dict[str, Any]],
    schema_cols: List[Dict[str, Any]],
    adapter: Optional[str],
    *,
    tests_key: str = TESTS_KEY_LEGACY,
) -> None:
    """Turn one emitted model into a dbt model contract (in place).

    Adds ``config: {contract: {enforced: true}}`` plus per-column
    ``data_type`` and ``constraints``. Mirrors datacontract-cli's
    dbt_exporter.py (MIT) in two load-bearing rules:

    - Contracts are only enforced on materializations that render
      constraints (table/incremental). Expose models are materialized
      as marts, so we consult the marts-layer materialization via
      module indirection into ``models.py`` — if that ever changes to
      a view, enforcement is skipped rather than emitting YAML dbt
      rejects.
    - ``not_null`` intent is *split*: when constraints are supported it
      becomes a ``constraints: [{type: not_null}]`` entry (checked at
      build time, before bad data lands) and the redundant ``not_null``
      data test is dropped; on the fallback path the test remains.

    Additionally (verified against dbt-core 1.11: "Contracted models
    require data_type to be defined for each column"): a contracted
    model must declare ``data_type`` for *every* column entry. DQ rules
    can reference columns absent from ``schema[]`` — their type is
    unknowable here, so if any such orphan column entry exists the
    contract is skipped for that model entirely instead of emitting a
    contract that fails on our YAML rather than on user drift.
    """
    if not schema_cols:
        # No declared schema → nothing to enforce against.
        return

    schema_by_name = {
        col["name"]: col for col in schema_cols if isinstance(col, dict) and col.get("name")
    }
    if any(entry.get("name") not in schema_by_name for entry in columns):
        # Orphan dq-rule column (not in schema[]) → skip enforcement.
        return

    # Consult the marts-layer materialization via module indirection so a
    # future materialization change flows through (and test patches too).
    from . import models as _models

    if _models._layer_materialization("marts") not in _CONSTRAINT_MATERIALIZATIONS:
        return

    model_def["config"] = {"contract": {"enforced": True}}

    for entry in columns:
        col = schema_by_name[entry["name"]]

        constraints: List[Dict[str, Any]] = []
        is_key = _tm.column_is_key(col)
        if _tm.is_truthy(col.get("required")) or is_key:
            constraints.append({"type": "not_null"})
        if is_key:
            constraints.append({"type": "primary_key"})

        # Re-insert so the emitted key order reads name → description →
        # data_type → constraints → tests/data_tests.
        tests = entry.pop(tests_key, None)
        entry["data_type"] = _types.sql_type(str(col.get("type", "string")), adapter)
        if constraints:
            entry["constraints"] = constraints
            # The build-time not_null constraint supersedes the post-build
            # not_null data test (datacontract-cli's constraints/tests split).
            tests = [t for t in tests if t != "not_null"] if tests else tests
        if tests:
            entry[tests_key] = tests


def _build_column_tests(
    schema_cols: List[Dict[str, Any]],
    dq_rules: List[Dict[str, Any]],
    *,
    tests_key: str = TESTS_KEY_LEGACY,
) -> tuple[List[Dict[str, Any]], List[Any]]:
    """Build dbt column + model test definitions from schema + DQ rules.

    Returns ``(columns, model_tests)``. The rule → (column | model) routing
    is :func:`._test_mapping.partition_rules`, the same router the exporter
    uses, so ``selector: "*"`` and freshness rules land in the same place on
    both surfaces. Before, this path treated ``"*"`` as an ordinary column
    name and emitted ``- name: '*'``.
    """
    rules_by_col, model_tests = _tm.partition_rules(dq_rules, schema_cols=schema_cols)

    columns: List[Dict[str, Any]] = []
    seen_cols = set()

    for col in schema_cols:
        if not isinstance(col, dict):
            continue
        col_name = col.get("name")
        if not col_name:
            continue
        seen_cols.add(col_name)

        tests = _tests_for_column(col, rules_by_col.get(col_name, []))
        col_entry: Dict[str, Any] = {"name": col_name}
        if col.get("description"):
            col_entry["description"] = col["description"]
        if tests:
            col_entry[tests_key] = tests
        columns.append(col_entry)

    # DQ rules on columns not in schema
    for col_name, tests in rules_by_col.items():
        if col_name in seen_cols:
            continue
        if tests:
            columns.append({"name": col_name, tests_key: tests})

    return columns, model_tests


def _tests_for_column(
    col_def: Dict[str, Any],
    rule_tests: List[Any],
) -> List[Any]:
    """Merge already-mapped DQ-rule tests with inline column constraints.

    Delegates to the single shared mapping (:mod:`._test_mapping`) so the engine
    path emits the *same* dbt tests as the exporter and the copilot generator
    for the same contract intent — including ``relationships`` (from a column FK
    reference), the unified numeric-range dialect, and freshness/recency, which
    this path previously did not surface.
    """
    # dq-rule tests win over the generic constraint-derived form on collision.
    return _tm.merge_tests(list(rule_tests), _tm.constraint_tests(col_def))
