# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""``models/semantic_models.yml`` — MetricFlow bridge for the contract semantics block.

The contract schema's ``exposes[*].semantics`` block is deliberately
MetricFlow-shaped (entities / measures / dimensions / metrics — the schema
description literally says "Compatible with dbt MetricFlow"), and forge
populates it on every expose. This module closes the loop: ``fluid generate
transformation`` emits a ``models/semantic_models.yml`` carrying
``semantic_models:`` + ``metrics:`` so the generated dbt project ships a
queryable semantic layer, validated by the same ``dbt parse`` gate as the
rest of the project.

The mapping is near-mechanical (camelCase → snake_case, wrap with
``model: ref('<expose model>')``); the value-add is the defaulting layer
that satisfies MetricFlow's parse-time strictness (verified against
dbt-core 1.11 + dbt-semantic-interfaces):

* **Primary entity is mandatory.** When the semantics block declares no
  ``type: primary`` entity, derive one from the expose's declared key
  column (``_test_mapping.column_is_key`` — same key detection the
  schema.yml/model-contract emitters use); failing that, promote the
  first ``unique`` entity; failing that, fall back to the first schema
  column. A model where no primary entity can be derived is skipped
  (with a log warning) rather than emitting YAML dbt rejects.
* **Measures need an aggregation time dimension.** ``defaults.
  agg_time_dimension`` maps from ``defaultAggTimeDimension`` when it
  resolves to a time dimension; otherwise the first time dimension is
  used. When the referenced name is a real schema column that simply
  wasn't declared as a dimension, a day-grain time dimension is
  synthesized for it. If no time dimension can be resolved at all,
  measures + metrics are dropped (entities/dimensions still emit).
* **Time dimensions need ``type_params.time_granularity``** — defaulted
  to ``day`` when the contract omits ``typeParams.timeGranularity``.
* **Element names share one namespace per model** (entities, dimensions,
  measures) — duplicates are dropped first-wins in entity → dimension →
  measure precedence order.
* **Metrics referencing missing inputs are skipped** (simple → measure
  must exist; ratio → numerator + denominator; derived → expr +
  inputMetrics), as are duplicate metric names across exposes.
  ``label`` (required by dbt >= 1.7) defaults to the metric name.
* ``agg: percentile`` maps the contract's ``aggParams``
  (``{percentile, useDiscretePercentile}``, 0.7.6+) into MetricFlow's
  ``agg_params``; when the contract omits the value it defaults to the
  shared ``DEFAULT_PERCENTILE`` (0.5 == median — identical to the MCP
  query compiler's default so both consumers answer the same number,
  and MetricFlow refuses percentile measures without agg_params).
* **A day-grain time spine model ships alongside** — real ``dbt parse``
  (1.11) rejects any project with semantic models but no time spine
  ("The semantic layer requires a time spine model with granularity DAY
  or smaller"). We emit ``models/metricflow_time_spine.sql`` (built on
  dbt-core's cross-database ``dbt.date_spine`` macro — no package
  dependency) plus the modern ``time_spine:`` YAML config (dbt >= 1.9
  shape; the venv's parse gate runs 1.11).

No-op guarantee: contracts without any ``exposes[*].semantics`` produce
no file — byte-identical output to the pre-semantics generator.
"""

from __future__ import annotations

import logging
import re
from typing import Any, Dict, List, Mapping, Optional, Set

import yaml

from ..base import GenerationResult
from . import _test_mapping as _tm

logger = logging.getLogger(__name__)

_HEADER = (
    "# Generated by fluid generate — do not edit manually.\n# Regenerate with: fluid generate\n\n"
)

# MetricFlow accepts these grains (dbt-semantic-interfaces TimeGranularity).
_VALID_GRAINS = {"nanosecond", "microsecond", "millisecond", "second", "minute", "hour"} | {
    "day",
    "week",
    "month",
    "quarter",
    "year",
}
_DEFAULT_GRAIN = "day"

_NAME_RE = re.compile(r"[^A-Za-z0-9_]+")

try:
    from fluid_build.util.contract import get_expose_contract, get_expose_id, get_exposes
except ImportError:  # pragma: no cover

    def get_exposes(contract):
        return contract.get("exposes", [])

    def get_expose_id(expose):
        return expose.get("exposeId") or expose.get("id")

    def get_expose_contract(expose):
        return expose.get("contract")


def _sanitize_name(raw: str) -> str:
    """Coerce a contract name into a MetricFlow-legal identifier.

    MetricFlow element names must be word-character identifiers that
    don't start with a digit. Collapse everything else to ``_``.
    """
    name = _NAME_RE.sub("_", str(raw).strip()).strip("_")
    if not name:
        return ""
    if name[0].isdigit():
        name = f"_{name}"
    return name


def _schema_columns(expose: Mapping[str, Any]) -> List[Dict[str, Any]]:
    contract_section = get_expose_contract(expose) or {}
    cols = contract_section.get("schema", [])
    if not isinstance(cols, list):
        return []
    return [c for c in cols if isinstance(c, dict) and c.get("name")]


# ---------------------------------------------------------------------------
# Entities
# ---------------------------------------------------------------------------


def _build_entities(
    semantics: Mapping[str, Any],
    expose: Mapping[str, Any],
    model_name: str,
) -> List[Dict[str, Any]]:
    """Map contract entities, guaranteeing exactly one primary entity."""
    entities: List[Dict[str, Any]] = []
    seen: Set[str] = set()
    have_primary = False

    for raw in semantics.get("entities") or []:
        if not isinstance(raw, Mapping) or not raw.get("name"):
            continue
        name = _sanitize_name(raw["name"])
        if not name or name in seen:
            continue
        etype = str(raw.get("type") or "foreign").strip().lower()
        if etype not in ("primary", "foreign", "unique", "natural"):
            etype = "foreign"
        if etype == "primary":
            if have_primary:
                # MetricFlow allows at most one primary entity.
                etype = "unique"
            else:
                have_primary = True
        entity: Dict[str, Any] = {"name": name, "type": etype}
        if raw.get("expr"):
            entity["expr"] = str(raw["expr"])
        if raw.get("description"):
            entity["description"] = str(raw["description"])
        entities.append(entity)
        seen.add(name)

    if not have_primary:
        derived = _derive_primary_entity(expose, model_name, seen)
        if derived is None:
            # Last resort: promote the first unique entity to primary.
            for entity in entities:
                if entity["type"] == "unique":
                    entity["type"] = "primary"
                    have_primary = True
                    break
        else:
            entities.insert(0, derived)
            have_primary = True

    if not have_primary:
        return []
    return entities


def _derive_primary_entity(
    expose: Mapping[str, Any],
    model_name: str,
    taken: Set[str],
) -> Optional[Dict[str, Any]]:
    """Derive a primary entity from the expose's declared key column.

    Mirrors the forge semantics emitter's naming (``order_id`` → entity
    ``order`` with ``expr: order_id``). Falls back to the first schema
    column when no column is declared a key.
    """
    columns = _schema_columns(expose)
    key_col: Optional[str] = None
    for col in columns:
        if _tm.column_is_key(col):
            key_col = str(col["name"])
            break
    if key_col is None and columns:
        key_col = str(columns[0]["name"])
    if key_col is None:
        return None

    base = _sanitize_name(re.sub(r"_id$", "", key_col) or key_col)
    if not base:
        base = _sanitize_name(key_col)
    if not base:
        return None
    if base in taken:
        base = _sanitize_name(f"{model_name}_{base}")
        if not base or base in taken:
            return None
    return {"name": base, "type": "primary", "expr": key_col}


# ---------------------------------------------------------------------------
# Dimensions + aggregation time dimension
# ---------------------------------------------------------------------------


def _build_dimensions(
    semantics: Mapping[str, Any],
    used_names: Set[str],
) -> List[Dict[str, Any]]:
    """Map contract dimensions; time dims always get a granularity."""
    dimensions: List[Dict[str, Any]] = []
    for raw in semantics.get("dimensions") or []:
        if not isinstance(raw, Mapping) or not raw.get("name"):
            continue
        name = _sanitize_name(raw["name"])
        if not name or name in used_names:
            continue
        dtype = str(raw.get("type") or "categorical").strip().lower()
        if dtype not in ("categorical", "time"):
            dtype = "categorical"
        dim: Dict[str, Any] = {"name": name, "type": dtype}
        if raw.get("expr"):
            dim["expr"] = str(raw["expr"])
        if raw.get("description"):
            dim["description"] = str(raw["description"])
        if dtype == "time":
            grain = None
            type_params = raw.get("typeParams")
            if isinstance(type_params, Mapping):
                grain = str(type_params.get("timeGranularity") or "").strip().lower() or None
            if grain not in _VALID_GRAINS:
                # MetricFlow refuses time dimensions without a granularity.
                grain = _DEFAULT_GRAIN
            dim["type_params"] = {"time_granularity": grain}
        dimensions.append(dim)
        used_names.add(name)
    return dimensions


def _resolve_agg_time_dimension(
    semantics: Mapping[str, Any],
    dimensions: List[Dict[str, Any]],
    expose: Mapping[str, Any],
    used_names: Set[str],
) -> Optional[str]:
    """Resolve the model-level default aggregation time dimension.

    Resolution order (each step must yield a *time* dimension in this
    model — MetricFlow rejects agg_time_dimension references that
    aren't):

    1. ``defaultAggTimeDimension`` when it names an emitted time
       dimension.
    2. ``defaultAggTimeDimension`` when it names a schema column not
       declared as a dimension — synthesize a day-grain time dimension
       for it (appended to ``dimensions`` in place).
    3. The first emitted time dimension.
    4. ``None`` — the caller drops measures + metrics.
    """
    time_dims = {d["name"] for d in dimensions if d.get("type") == "time"}
    declared = _sanitize_name(semantics.get("defaultAggTimeDimension") or "")

    if declared and declared in time_dims:
        return declared

    if declared and declared not in used_names:
        column_names = {str(c["name"]) for c in _schema_columns(expose)}
        if declared in column_names:
            dimensions.append(
                {
                    "name": declared,
                    "type": "time",
                    "type_params": {"time_granularity": _DEFAULT_GRAIN},
                }
            )
            used_names.add(declared)
            return declared

    if time_dims:
        # Deterministic: first time dimension in emitted order.
        for dim in dimensions:
            if dim.get("type") == "time":
                return dim["name"]
    return None


# ---------------------------------------------------------------------------
# Measures
# ---------------------------------------------------------------------------

_VALID_AGGS = {"sum", "avg", "count", "count_distinct", "min", "max", "median", "percentile"}

# Default when a percentile measure carries no ``aggParams.percentile``.
# MUST stay equal to ``output_ports/mcp/query_compiler.DEFAULT_PERCENTILE``
# (pinned by tests) so the governed query path and the exported dbt
# project answer the same number for the same contract. 0.5 == median.
DEFAULT_PERCENTILE = 0.5


def _percentile_agg_params(raw: Any) -> Dict[str, Any]:
    """Map the contract's ``aggParams`` into MetricFlow ``agg_params``.

    Out-of-range / malformed values fall back to the default rather than
    emitting YAML ``dbt parse`` rejects — consistent with this module's
    degrade-don't-fail posture (the strict path is the MCP compiler).
    """
    params = raw if isinstance(raw, Mapping) else {}
    percentile = params.get("percentile", DEFAULT_PERCENTILE)
    if (
        isinstance(percentile, bool)
        or not isinstance(percentile, (int, float))
        or not 0 <= float(percentile) <= 1
    ):
        percentile = DEFAULT_PERCENTILE
    agg_params: Dict[str, Any] = {"percentile": float(percentile)}
    if _tm.is_truthy(params.get("useDiscretePercentile")):
        agg_params["use_discrete_percentile"] = True
    return agg_params


def _build_measures(
    semantics: Mapping[str, Any],
    used_names: Set[str],
    time_dims: Set[str],
    model_label: str,
) -> List[Dict[str, Any]]:
    """Map contract measures. Caller guarantees a default agg time dim exists."""
    measures: List[Dict[str, Any]] = []
    for raw in semantics.get("measures") or []:
        if not isinstance(raw, Mapping) or not raw.get("name"):
            continue
        name = _sanitize_name(raw["name"])
        if not name or name in used_names:
            logger.warning(
                "semantic_models: dropping measure %r on %s (duplicate element name)",
                raw.get("name"),
                model_label,
            )
            continue
        agg = str(raw.get("agg") or "").strip().lower()
        if agg not in _VALID_AGGS:
            logger.warning(
                "semantic_models: dropping measure %r on %s (unsupported agg %r)",
                name,
                model_label,
                raw.get("agg"),
            )
            continue
        measure: Dict[str, Any] = {"name": name, "agg": agg}
        if raw.get("description"):
            measure["description"] = str(raw["description"])
        if raw.get("expr"):
            measure["expr"] = str(raw["expr"])
        if agg == "percentile":
            # MetricFlow refuses percentile measures without agg_params.
            # Map the contract's aggParams (0.7.6+); default matches the
            # MCP query compiler (DEFAULT_PERCENTILE) so the governed
            # query path and the exported dbt project agree.
            measure["agg_params"] = _percentile_agg_params(raw.get("aggParams"))
        override = _sanitize_name(raw.get("aggTimeDimension") or "")
        if override and override in time_dims:
            measure["agg_time_dimension"] = override
        nad = raw.get("nonAdditiveDimension")
        if isinstance(nad, Mapping) and nad.get("name"):
            nad_name = _sanitize_name(nad["name"])
            if nad_name in time_dims:
                window_choice = str(nad.get("windowChoice") or "min").strip().lower()
                if window_choice not in ("min", "max"):
                    window_choice = "min"
                measure["non_additive_dimension"] = {
                    "name": nad_name,
                    "window_choice": window_choice,
                }
        if _tm.is_truthy(raw.get("createMetric")):
            measure["create_metric"] = True
        measures.append(measure)
        used_names.add(name)
    return measures


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------


def _build_metrics(
    semantics: Mapping[str, Any],
    measure_names: Set[str],
    metric_names_taken: Set[str],
    model_label: str,
    deferred: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """Map contract metrics → dbt metrics (simple / derived / ratio).

    Metrics whose inputs can't be satisfied are skipped with a warning —
    an emitted metric that fails ``dbt parse`` is worse than an honest
    omission. Simple metrics are checked against this model's emitted
    measures right here; ratio/derived metrics reference OTHER metrics
    (a project-global namespace, possibly defined by a later expose), so
    they are appended to ``deferred`` as ``{"metric": doc, "inputs":
    [names]}`` and resolved by :func:`_resolve_deferred_metrics` once
    every expose has contributed its metric names.
    """
    metrics: List[Dict[str, Any]] = []
    for raw in semantics.get("metrics") or []:
        if not isinstance(raw, Mapping) or not raw.get("name"):
            continue
        name = _sanitize_name(raw["name"])
        if not name:
            continue
        if name in metric_names_taken:
            logger.warning(
                "semantic_models: dropping metric %r on %s (duplicate metric name)",
                name,
                model_label,
            )
            continue
        mtype = str(raw.get("type") or "").strip().lower()

        type_params: Optional[Dict[str, Any]] = None
        if mtype == "simple":
            measure = _sanitize_name(raw.get("measure") or "")
            if measure not in measure_names:
                logger.warning(
                    "semantic_models: dropping simple metric %r on %s " "(measure %r not emitted)",
                    name,
                    model_label,
                    raw.get("measure"),
                )
                continue
            type_params = {"measure": measure}
        elif mtype == "ratio":
            input_metrics = [
                _sanitize_name(m) for m in raw.get("inputMetrics") or [] if _sanitize_name(m)
            ]
            numerator = _sanitize_name(raw.get("numerator") or "") or (
                input_metrics[0] if len(input_metrics) >= 1 else ""
            )
            denominator = _sanitize_name(raw.get("denominator") or "") or (
                input_metrics[1] if len(input_metrics) >= 2 else ""
            )
            if not numerator or not denominator:
                logger.warning(
                    "semantic_models: dropping ratio metric %r on %s "
                    "(needs numerator + denominator)",
                    name,
                    model_label,
                )
                continue
            type_params = {"numerator": numerator, "denominator": denominator}
        elif mtype == "derived":
            expr = str(raw.get("expr") or "").strip()
            input_metrics = [
                _sanitize_name(m) for m in raw.get("inputMetrics") or [] if _sanitize_name(m)
            ]
            if not expr or not input_metrics:
                logger.warning(
                    "semantic_models: dropping derived metric %r on %s "
                    "(needs expr + inputMetrics)",
                    name,
                    model_label,
                )
                continue
            type_params = {"expr": expr, "metrics": [{"name": m} for m in input_metrics]}
        else:
            logger.warning(
                "semantic_models: dropping metric %r on %s (unsupported type %r)",
                name,
                model_label,
                raw.get("type"),
            )
            continue

        metric: Dict[str, Any] = {
            "name": name,
            # dbt >= 1.7 requires a label on every metric.
            "label": str(raw.get("name")),
            "type": mtype,
        }
        if raw.get("description"):
            metric["description"] = str(raw["description"])
        metric["type_params"] = type_params
        if raw.get("filter"):
            metric["filter"] = str(raw["filter"])

        if mtype == "simple":
            metrics.append(metric)
        else:
            # ratio / derived: inputs are metric names — resolve globally
            # once all exposes have emitted (a reference to a dropped
            # metric would fail dbt parse).
            inputs = (
                [type_params["numerator"], type_params["denominator"]]
                if mtype == "ratio"
                else [m["name"] for m in type_params["metrics"]]
            )
            deferred.append({"metric": metric, "inputs": inputs, "model": model_label})
        metric_names_taken.add(name)
    return metrics


def _resolve_deferred_metrics(
    deferred: List[Dict[str, Any]],
    emitted_names: Set[str],
) -> List[Dict[str, Any]]:
    """Fixpoint-resolve ratio/derived metrics against emitted metric names.

    A deferred metric emits only when every input metric it references
    actually exists in the project (simple metrics, ``create_metric``
    measures, or other deferred metrics resolved in an earlier pass —
    hence the fixpoint loop: a ratio may reference a derived metric).
    Whatever cannot be satisfied is dropped with a warning.
    """
    resolved: List[Dict[str, Any]] = []
    pending = list(deferred)
    progress = True
    while progress and pending:
        progress = False
        still_pending: List[Dict[str, Any]] = []
        for item in pending:
            if all(name in emitted_names for name in item["inputs"]):
                resolved.append(item["metric"])
                emitted_names.add(item["metric"]["name"])
                progress = True
            else:
                still_pending.append(item)
        pending = still_pending
    for item in pending:
        missing = [name for name in item["inputs"] if name not in emitted_names]
        logger.warning(
            "semantic_models: dropping %s metric %r on %s (input metrics %s not emitted)",
            item["metric"]["type"],
            item["metric"]["name"],
            item["model"],
            missing,
        )
    return resolved


# ---------------------------------------------------------------------------
# Time spine (mandatory companion of any semantic model)
# ---------------------------------------------------------------------------

# dbt-core's cross-database date_spine macro — portable across adapters,
# no dbt_utils dependency. Fixed range keeps the emit deterministic.
_TIME_SPINE_SQL = """{{ config(materialized='table') }}

-- Generated by fluid generate — do not edit manually.
-- MetricFlow requires a day-grain time spine in any project with
-- semantic models. Range is fixed so the emit stays deterministic.

with days as (
    {{ dbt.date_spine('day', "cast('2020-01-01' as date)", "cast('2035-01-01' as date)") }}
)

select cast(date_day as date) as date_day
from days
"""

_TIME_SPINE_MODEL_DEF: Dict[str, Any] = {
    "name": "metricflow_time_spine",
    "description": "Day-grain time spine required by the MetricFlow semantic layer.",
    "time_spine": {"standard_granularity_column": "date_day"},
    "columns": [{"name": "date_day", "granularity": "day"}],
}


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def generate_semantic_models(contract: Dict[str, Any]) -> GenerationResult:
    """Emit ``models/semantic_models.yml`` from ``exposes[*].semantics``.

    Returns ``{}`` (graceful no-op) when no expose carries a semantics
    block — hand-authored contracts often lack one, and the generated
    project must stay byte-identical for them.
    """
    semantic_models: List[Dict[str, Any]] = []
    all_metrics: List[Dict[str, Any]] = []
    deferred_metrics: List[Dict[str, Any]] = []
    metric_names_taken: Set[str] = set()
    emitted_metric_names: Set[str] = set()
    model_names_taken: Set[str] = set()

    for expose in get_exposes(contract):
        if not isinstance(expose, dict):
            continue
        semantics = expose.get("semantics")
        if not isinstance(semantics, Mapping) or not semantics:
            continue
        expose_id = get_expose_id(expose)
        if not expose_id:
            continue
        model_name = _sanitize_name(expose_id)
        if not model_name or model_name in model_names_taken:
            continue

        entities = _build_entities(semantics, expose, model_name)
        if not entities:
            logger.warning(
                "semantic_models: skipping expose %r (no primary entity could be derived)",
                expose_id,
            )
            continue

        used_names: Set[str] = {e["name"] for e in entities}
        dimensions = _build_dimensions(semantics, used_names)
        agg_time_dim = _resolve_agg_time_dimension(semantics, dimensions, expose, used_names)

        time_dims = {d["name"] for d in dimensions if d.get("type") == "time"}
        measures: List[Dict[str, Any]] = []
        if agg_time_dim is None:
            if semantics.get("measures"):
                logger.warning(
                    "semantic_models: expose %r has measures but no resolvable "
                    "time dimension — measures + metrics dropped",
                    expose_id,
                )
        else:
            measures = _build_measures(semantics, used_names, time_dims, model_name)

        model_def: Dict[str, Any] = {
            "name": model_name,
            "model": f"ref('{expose_id}')",
        }
        description = semantics.get("description") or expose.get("description")
        if description:
            model_def["description"] = str(description)
        if agg_time_dim is not None and measures:
            model_def["defaults"] = {"agg_time_dimension": agg_time_dim}
        model_def["entities"] = entities
        if dimensions:
            model_def["dimensions"] = dimensions
        if measures:
            model_def["measures"] = measures

        semantic_models.append(model_def)
        model_names_taken.add(model_name)

        measure_names = {m["name"] for m in measures}
        # A ``create_metric`` measure auto-creates a metric bearing its
        # name — that name is claimed (an explicit same-named metric
        # would collide at parse) and counts as resolvable input for
        # ratio/derived metrics.
        create_metric_names = {m["name"] for m in measures if m.get("create_metric")}
        metric_names_taken.update(create_metric_names)
        emitted_metric_names.update(create_metric_names)

        simple_metrics = _build_metrics(
            semantics, measure_names, metric_names_taken, model_name, deferred_metrics
        )
        emitted_metric_names.update(m["name"] for m in simple_metrics)
        all_metrics.extend(simple_metrics)

    if not semantic_models:
        return {}

    all_metrics.extend(_resolve_deferred_metrics(deferred_metrics, emitted_metric_names))

    data: Dict[str, Any] = {"semantic_models": semantic_models}
    if all_metrics:
        data["metrics"] = all_metrics
    # MetricFlow refuses to parse a project with semantic models but no
    # day-grain (or smaller) time spine. Ship one + its YAML config.
    data["models"] = [_TIME_SPINE_MODEL_DEF]
    content = _HEADER + yaml.dump(
        data, default_flow_style=False, sort_keys=False, allow_unicode=True
    )
    return {
        "models/semantic_models.yml": content,
        "models/metricflow_time_spine.sql": _TIME_SPINE_SQL,
    }
