# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate ``models/sources.yml`` from ``consumes[]``.

When the caller provides a ``workspace_root`` (or the ``FLUID_UPSTREAM_CONTRACTS``
environment variable is set), we walk those directories looking for upstream
``contract.fluid.yaml`` files whose ``id`` matches a consume's ``productId``.
For each match we use the upstream expose's ``binding.location`` to resolve
the real Snowflake/BigQuery ``database``/``schema``/``identifier`` so the
generated dbt sources.yml points at the correct physical objects instead of
placeholders.

When upstream contracts cannot be found, we degrade gracefully to env_var
placeholders and an uppercased exposeId identifier — the author will need
to adjust sources.yml by hand, but the project still parses.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Tuple

import yaml

from fluid_build.util.freshness import iso_duration_to_freshness_unit
from fluid_build.util.upstream_discovery import discover_upstream_products

# Shared tests:/data_tests: dialect handling — see the note on
# ``schema_yml.TESTS_KEY_MODERN`` for why the key is engine/version-aware.
from .schema_yml import TESTS_KEY_LEGACY, normalize_tests_key

_HEADER = (
    "# Generated by fluid generate — do not edit manually.\n# Regenerate with: fluid generate\n\n"
)

_logger = logging.getLogger(__name__)

# Adapters that compute source freshness from warehouse metadata tables and so
# do NOT require a ``loaded_at_field`` (dbt >= 1.7). Mapped from the contract's
# ``binding.platform`` enum. Everything else (duckdb/local, postgres, kafka …)
# needs an explicit ``loaded_at_field``; when none is derivable we omit the
# whole ``freshness:`` block rather than emit one dbt would error on.
# Ref: https://docs.getdbt.com/reference/resource-properties/freshness
_METADATA_FRESHNESS_PLATFORMS = frozenset(
    {"snowflake", "gcp", "bigquery", "aws", "redshift", "databricks"}
)

try:
    from fluid_build.util.contract import consumes_to_canonical_ports
except ImportError:  # pragma: no cover

    def consumes_to_canonical_ports(contract, **_kw):
        return [
            {
                "id": c.get("exposeId") or c.get("id", "unknown"),
                "name": c.get("name", ""),
                "reference": c.get("productId") or c.get("ref"),
            }
            for c in contract.get("consumes", [])
            if isinstance(c, dict)
        ]


# Matches ``{{ env.FOO }}`` / ``{{env.FOO}}`` (FLUID contract placeholder).
_FLUID_ENV_RE = re.compile(r"\{\{\s*env\.([A-Za-z_][A-Za-z0-9_]*)\s*\}\}")
# Matches ``${FOO}`` (shell-style placeholder) and ``$FOO``.
_SHELL_ENV_RE = re.compile(r"\$\{?([A-Za-z_][A-Za-z0-9_]*)\}?")


def generate_sources(
    contract: Dict[str, Any],
    *,
    schema_context: Optional[Dict[str, Any]] = None,
    workspace_root: Optional[Path] = None,
    tests_key: Optional[str] = None,
) -> Optional[str]:
    """Generate ``sources.yml`` content from contract consumes.

    Returns ``None`` if the contract has no consumes.

    ``workspace_root`` tells the walker where to start searching for upstream
    ``contract.fluid.yaml`` files. Additional roots can be supplied via the
    ``FLUID_UPSTREAM_CONTRACTS`` environment variable (colon-separated paths).

    ``tests_key`` selects the YAML key source-column data tests attach
    under — ``"tests"`` (legacy, default) or ``"data_tests"`` (dbt-core
    >=1.8 / required by Fusion).
    """
    resolved_tests_key = normalize_tests_key(tests_key)
    consumes = contract.get("consumes", [])
    if not consumes:
        return None

    canonical = consumes_to_canonical_ports(contract)
    if not canonical:
        return None

    upstream_index = discover_upstream_products(workspace_root)

    # Whether the consumer's target adapter can compute freshness from
    # warehouse metadata (so a ``loaded_at_field`` is optional).
    metadata_capable = _target_platform(contract) in _METADATA_FRESHNESS_PLATFORMS

    # Group tables by (database_expr, schema_expr) so multi-schema lineage
    # lands in separate dbt source blocks.
    grouped: Dict[Tuple[str, str], List[Dict[str, Any]]] = {}
    order: List[Tuple[str, str]] = []

    for port in canonical:
        resolved, expose = _resolve_binding(port, upstream_index)
        key = (resolved["database_expr"], resolved["schema_expr"])
        if key not in grouped:
            grouped[key] = []
            order.append(key)

        table_entry: Dict[str, Any] = {
            "name": port["id"],
        }
        if resolved["identifier"] and resolved["identifier"] != port["id"]:
            table_entry["identifier"] = resolved["identifier"]
        if port.get("description"):
            table_entry["description"] = port["description"]

        columns = _columns_for_source(port["id"], schema_context, tests_key=resolved_tests_key)
        if columns:
            table_entry["columns"] = columns

        # Freshness (``dbt source freshness``) — operationalizes the contract's
        # freshness promise on the consumed source. loaded_at_field + freshness
        # are appended last so tables without a freshness promise are byte-for-
        # byte unchanged.
        freshness = _freshness_block(port, expose)
        if freshness is not None:
            loaded_at_field = resolved.get("loaded_at_field")
            if loaded_at_field:
                table_entry["loaded_at_field"] = loaded_at_field
                table_entry["freshness"] = freshness
            elif metadata_capable:
                # No cursor column, but the adapter reads freshness from
                # warehouse metadata — emit the block without loaded_at_field.
                table_entry["freshness"] = freshness
            # else: duckdb/local etc. with no derivable column — omit the block
            # entirely so ``dbt source freshness`` doesn't error.

        grouped[key].append(table_entry)

    sources_list: List[Dict[str, Any]] = []
    for idx, key in enumerate(order):
        database_expr, schema_expr = key
        block: Dict[str, Any] = {
            "name": "raw" if len(order) == 1 else f"raw_{idx}",
            "description": "Source data consumed by this data product",
        }
        if database_expr:
            block["database"] = database_expr
        if schema_expr:
            block["schema"] = schema_expr
        block["tables"] = grouped[key]
        sources_list.append(block)

    source_def: Dict[str, Any] = {
        "version": 2,
        "sources": sources_list,
    }

    return _HEADER + yaml.dump(
        source_def, default_flow_style=False, sort_keys=False, allow_unicode=True
    )


def generate_sources_from_logical_model(logical_model: Mapping[str, Any]) -> Optional[str]:
    """Generate dbt sources from a forged DDL logical sidecar.

    DDL-driven models do not have ``consumes[]`` lineage yet, but their OSI
    datasets still carry the source table names and columns. Emitting a
    ``raw`` source block lets generated models use ``source('raw', table)``
    in production while the model SQL guards missing local relations for
    offline smoke runs.
    """
    source_summary = logical_model.get("source_summary") or {}
    if source_summary.get("source_kind") != "ddl":
        return None
    osi = logical_model.get("osi") or {}
    datasets = osi.get("datasets") or []
    tables: List[Dict[str, Any]] = []
    for dataset in datasets:
        if not isinstance(dataset, Mapping):
            continue
        name = str(dataset.get("source") or dataset.get("name") or "").strip()
        if not name:
            continue
        entry: Dict[str, Any] = {"name": name}
        fields = dataset.get("fields") or []
        columns = []
        for field in fields:
            if isinstance(field, Mapping) and field.get("name"):
                columns.append({"name": str(field["name"])})
        if columns:
            entry["columns"] = columns
        tables.append(entry)
    if not tables:
        return None

    source_def: Dict[str, Any] = {
        "version": 2,
        "sources": [
            {
                "name": "raw",
                "description": "Source tables inferred from the forged DDL sidecar",
                "schema": "{{ env_var('FLUID_SOURCE_SCHEMA', env_var('SNOWFLAKE_STAGE_SCHEMA', target.schema)) }}",
                "tables": tables,
            }
        ],
    }
    return _HEADER + yaml.dump(
        source_def, default_flow_style=False, sort_keys=False, allow_unicode=True
    )


# ---------------------------------------------------------------------------
# Binding resolution
# ---------------------------------------------------------------------------


def _resolve_binding(
    port: Mapping[str, Any],
    upstream_index: Mapping[str, Mapping[str, Any]],
) -> Tuple[Dict[str, Optional[str]], Optional[Mapping[str, Any]]]:
    """Resolve a consume to ``({database_expr, schema_expr, identifier,
    loaded_at_field}, matched_upstream_expose)``.

    Tries the upstream contract index first; falls back to env_var-style
    placeholders when the upstream cannot be located. The second tuple element
    is the matched upstream ``exposes[]`` entry (or ``None`` on fallback) — its
    ``qos.freshnessSLO`` / ``contract.freshness`` feed the freshness block.
    ``loaded_at_field`` is derived from the upstream's acquisition cursor field
    when available (else ``None``).
    """
    expose_id = port.get("id") or ""
    product_id = port.get("reference")

    upstream = upstream_index.get(product_id) if product_id else None
    if upstream:
        for expose in upstream.get("exposes") or []:
            if not isinstance(expose, Mapping):
                continue
            if (expose.get("exposeId") or expose.get("id")) != expose_id:
                continue
            binding = expose.get("binding") or {}
            location = binding.get("location") or {}
            if not isinstance(location, Mapping):
                location = {}
            resolved: Dict[str, Optional[str]] = {
                "database_expr": _normalize_placeholder(location.get("database")),
                "schema_expr": _normalize_placeholder(
                    location.get("schema") or location.get("dataset")
                ),
                "identifier": _identifier_from_location(location, expose_id),
                "loaded_at_field": _cursor_field_from_upstream(upstream),
            }
            return resolved, expose

    # Fallback — we didn't find the upstream contract or the specific expose.
    # Emit env_var placeholders so dbt still compiles; the user can correct
    # them by setting SNOWFLAKE_DATABASE / SNOWFLAKE_STAGE_SCHEMA (or via
    # env vars for other warehouses).
    _logger.debug(
        "sources: upstream %s/%s not resolved; using env_var fallback",
        product_id,
        expose_id,
    )
    return {
        "database_expr": "{{ env_var('SNOWFLAKE_DATABASE') }}",
        "schema_expr": "{{ env_var('SNOWFLAKE_STAGE_SCHEMA', 'PUBLIC') }}",
        "identifier": expose_id.upper() if expose_id else None,
        "loaded_at_field": None,
    }, None


def _identifier_from_location(
    location: Mapping[str, Any],
    default: str,
) -> Optional[str]:
    for key in ("table", "object", "view", "path"):
        value = location.get(key)
        if isinstance(value, str) and value.strip():
            return _normalize_placeholder(value)
    if default:
        return default.upper()
    return None


def _normalize_placeholder(value: Any) -> Optional[str]:
    """Rewrite FLUID/shell env-style placeholders to dbt ``env_var(...)``.

    dbt source blocks support Jinja that's rendered at parse time. FLUID
    contracts ship with ``{{ env.FOO }}`` or ``${FOO}`` — dbt doesn't
    understand those shapes, so we translate them to ``env_var('FOO')``.
    Literal (non-placeholder) strings are returned unchanged.
    """
    if value is None:
        return None
    if not isinstance(value, str):
        return str(value)
    text = value.strip()
    if not text:
        return None

    text = _FLUID_ENV_RE.sub(lambda m: f"{{{{ env_var('{m.group(1)}') }}}}", text)
    text = _SHELL_ENV_RE.sub(lambda m: f"{{{{ env_var('{m.group(1)}') }}}}", text)
    return text


# ---------------------------------------------------------------------------
# Source freshness (``dbt source freshness``)
# ---------------------------------------------------------------------------


def _freshness_block(
    port: Mapping[str, Any],
    expose: Optional[Mapping[str, Any]],
) -> Optional[Dict[str, Any]]:
    """Build a dbt ``freshness:`` block for one source table.

    Precedence (highest first):

      1. Upstream expose ``contract.freshness`` — a copilot-enriched, already
         dbt-shaped block passed through verbatim (a null ``filter`` key is
         stripped). Tolerates absence: ``exposes[].contract.freshness`` is
         schema-invalid today, so it is usually not present.
      2. Consumer ``qosExpectations.freshnessMax`` → ``error_after`` and, when
         present, upstream ``qos.freshnessSLO`` → ``warn_after``.
      3. ``freshnessSLO`` alone → ``warn_after`` = SLO, ``error_after`` = 2×SLO.

    Returns the freshness mapping (``{warn_after, error_after, filter?}``) or
    ``None`` when the contract declares no freshness promise. ``loaded_at_field``
    is NOT part of the returned block — the caller places it as a sibling of
    ``freshness`` on the table and decides omission for metadata-less adapters.
    """
    # (1) Pass-through of an already-dbt-shaped block.
    passthrough = _passthrough_freshness(expose)
    if passthrough is not None:
        return passthrough

    # (2)/(3) Derive from ISO-8601 freshness durations.
    slo = _expose_freshness_slo(expose)
    freshness_max = _consumer_freshness_max(port)
    warn = iso_duration_to_freshness_unit(slo)
    error = iso_duration_to_freshness_unit(freshness_max)

    if warn and error:
        # (2) both declared: producer SLO warns, consumer max errors.
        return {"warn_after": warn, "error_after": error}
    if error:
        # freshnessMax alone — a consumer hard expectation, no soft warn.
        return {"error_after": error}
    if warn:
        # (3) SLO alone — warn at the SLO, error at twice the SLO.
        return {
            "warn_after": warn,
            "error_after": iso_duration_to_freshness_unit(slo, multiplier=2),
        }
    return None


def _passthrough_freshness(
    expose: Optional[Mapping[str, Any]],
) -> Optional[Dict[str, Any]]:
    """Return a copy of ``expose.contract.freshness`` (null ``filter`` stripped).

    ``exposes[].contract.freshness`` is not part of the current schema
    (``exposeContract`` is ``additionalProperties: false``), so this must
    tolerate its absence gracefully and return ``None``.
    """
    if not isinstance(expose, Mapping):
        return None
    contract_block = expose.get("contract")
    if not isinstance(contract_block, Mapping):
        return None
    freshness = contract_block.get("freshness")
    if not isinstance(freshness, Mapping) or not freshness:
        return None
    result = dict(freshness)  # copy — never mutate the source contract
    if result.get("filter") is None:
        result.pop("filter", None)
    return result


def _expose_freshness_slo(expose: Optional[Mapping[str, Any]]) -> Optional[str]:
    """Producer freshness promise: upstream ``exposes[].qos.freshnessSLO``."""
    if not isinstance(expose, Mapping):
        return None
    qos = expose.get("qos")
    if isinstance(qos, Mapping):
        slo = qos.get("freshnessSLO")
        if isinstance(slo, str) and slo.strip():
            return slo.strip()
    return None


def _consumer_freshness_max(port: Mapping[str, Any]) -> Optional[str]:
    """Consumer expectation: ``consumes[].qosExpectations.freshnessMax``.

    The canonical port carries this under ``qos_expectations`` (see
    :func:`fluid_build.util.contract.consumes_to_canonical_ports`).
    """
    qos = port.get("qos_expectations")
    if isinstance(qos, Mapping):
        freshness_max = qos.get("freshnessMax")
        if isinstance(freshness_max, str) and freshness_max.strip():
            return freshness_max.strip()
    return None


def _cursor_field_from_upstream(upstream: Mapping[str, Any]) -> Optional[str]:
    """Derive a dbt ``loaded_at_field`` from the upstream acquisition source.

    Looks for an acquisition source's ``cursor_field`` (e.g. ``updated_at``) in
    the shapes a contract can carry it: a top-level ``acquisition`` block and
    the schema-canonical ``builds[].properties.source`` acquisition pattern.
    Returns the first match, else ``None`` (freshness then relies on warehouse
    metadata or is omitted).
    """
    # Card shape: acquisition.sources[].cursor_field / acquisition.source.*
    acquisition = upstream.get("acquisition")
    if isinstance(acquisition, Mapping):
        for source in acquisition.get("sources") or []:
            cursor = _cursor_field(source)
            if cursor:
                return cursor
        cursor = _cursor_field(acquisition.get("source"))
        if cursor:
            return cursor

    # Schema-canonical shape: builds[].properties.source (acquisitionPattern).
    for build in upstream.get("builds") or []:
        if not isinstance(build, Mapping):
            continue
        properties = build.get("properties")
        if isinstance(properties, Mapping):
            cursor = _cursor_field(properties.get("source"))
            if cursor:
                return cursor
    return None


def _cursor_field(source: Any) -> Optional[str]:
    if isinstance(source, Mapping):
        cursor = source.get("cursor_field")
        if isinstance(cursor, str) and cursor.strip():
            return cursor.strip()
    return None


def _target_platform(contract: Mapping[str, Any]) -> Optional[str]:
    """Resolve the consumer's target platform (lowercased) or ``None``.

    Prefers ``exposes[].binding.platform`` (the output-port binding), falling
    back to ``builds[].execution.runtime.platform`` (as ``profiles.yml`` reads
    it). Drives whether a ``loaded_at_field`` is required for freshness.
    """
    for expose in contract.get("exposes") or []:
        if isinstance(expose, Mapping):
            platform = (expose.get("binding") or {}).get("platform")
            if isinstance(platform, str) and platform.strip():
                return platform.strip().lower()
    for build in contract.get("builds") or []:
        if isinstance(build, Mapping):
            runtime = (build.get("execution") or {}).get("runtime") or {}
            platform = runtime.get("platform") if isinstance(runtime, Mapping) else None
            if isinstance(platform, str) and platform.strip():
                return platform.strip().lower()
    return None


# ---------------------------------------------------------------------------
# Column projection
# ---------------------------------------------------------------------------


def _columns_for_source(
    table_name: str,
    schema_context: Optional[Dict[str, Any]],
    *,
    tests_key: str = TESTS_KEY_LEGACY,
) -> List[Dict[str, Any]]:
    """Extract column definitions from schema_context for a source table."""
    if not schema_context:
        return []

    schemas = schema_context.get("schemas", {})
    table_schema = schemas.get(table_name)
    if not table_schema:
        for key, schema in schemas.items():
            base = key.rsplit(".", 1)[0] if "." in key else key
            if base == table_name or base.replace("-", "_") == table_name:
                table_schema = schema
                break

    if not table_schema or not isinstance(table_schema, dict):
        return []

    columns_map = table_schema.get("columns", {})
    if not isinstance(columns_map, dict):
        return []

    columns: List[Dict[str, Any]] = []
    for col_name, _col_type in columns_map.items():
        col_entry: Dict[str, Any] = {"name": col_name}
        if col_name.endswith("_id") or col_name == "id":
            col_entry[tests_key] = ["unique", "not_null"]
        columns.append(col_entry)

    return columns
