# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate ``models/sources.yml`` from ``consumes[]``.

When the caller provides a ``workspace_root`` (or the ``FLUID_UPSTREAM_CONTRACTS``
environment variable is set), we walk those directories looking for upstream
``contract.fluid.yaml`` files whose ``id`` matches a consume's ``productId``.
For each match we use the upstream expose's ``binding.location`` to resolve
the real Snowflake/BigQuery ``database``/``schema``/``identifier`` so the
generated dbt sources.yml points at the correct physical objects instead of
placeholders.

When upstream contracts cannot be found, we degrade gracefully to env_var
placeholders and an uppercased exposeId identifier — the author will need
to adjust sources.yml by hand, but the project still parses.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Tuple

import yaml

from fluid_build.util.upstream_discovery import discover_upstream_products

_HEADER = (
    "# Generated by fluid generate — do not edit manually.\n# Regenerate with: fluid generate\n\n"
)

_logger = logging.getLogger(__name__)

try:
    from fluid_build.util.contract import consumes_to_canonical_ports
except ImportError:  # pragma: no cover

    def consumes_to_canonical_ports(contract, **_kw):
        return [
            {
                "id": c.get("exposeId") or c.get("id", "unknown"),
                "name": c.get("name", ""),
                "reference": c.get("productId") or c.get("ref"),
            }
            for c in contract.get("consumes", [])
            if isinstance(c, dict)
        ]


# Matches ``{{ env.FOO }}`` / ``{{env.FOO}}`` (FLUID contract placeholder).
_FLUID_ENV_RE = re.compile(r"\{\{\s*env\.([A-Za-z_][A-Za-z0-9_]*)\s*\}\}")
# Matches ``${FOO}`` (shell-style placeholder) and ``$FOO``.
_SHELL_ENV_RE = re.compile(r"\$\{?([A-Za-z_][A-Za-z0-9_]*)\}?")


def generate_sources(
    contract: Dict[str, Any],
    *,
    schema_context: Optional[Dict[str, Any]] = None,
    workspace_root: Optional[Path] = None,
) -> Optional[str]:
    """Generate ``sources.yml`` content from contract consumes.

    Returns ``None`` if the contract has no consumes.

    ``workspace_root`` tells the walker where to start searching for upstream
    ``contract.fluid.yaml`` files. Additional roots can be supplied via the
    ``FLUID_UPSTREAM_CONTRACTS`` environment variable (colon-separated paths).
    """
    consumes = contract.get("consumes", [])
    if not consumes:
        return None

    canonical = consumes_to_canonical_ports(contract)
    if not canonical:
        return None

    upstream_index = discover_upstream_products(workspace_root)

    # Group tables by (database_expr, schema_expr) so multi-schema lineage
    # lands in separate dbt source blocks.
    grouped: Dict[Tuple[str, str], List[Dict[str, Any]]] = {}
    order: List[Tuple[str, str]] = []

    for port in canonical:
        resolved = _resolve_binding(port, upstream_index)
        key = (resolved["database_expr"], resolved["schema_expr"])
        if key not in grouped:
            grouped[key] = []
            order.append(key)

        table_entry: Dict[str, Any] = {
            "name": port["id"],
        }
        if resolved["identifier"] and resolved["identifier"] != port["id"]:
            table_entry["identifier"] = resolved["identifier"]
        if port.get("description"):
            table_entry["description"] = port["description"]

        columns = _columns_for_source(port["id"], schema_context)
        if columns:
            table_entry["columns"] = columns

        grouped[key].append(table_entry)

    sources_list: List[Dict[str, Any]] = []
    for idx, key in enumerate(order):
        database_expr, schema_expr = key
        block: Dict[str, Any] = {
            "name": "raw" if len(order) == 1 else f"raw_{idx}",
            "description": "Source data consumed by this data product",
        }
        if database_expr:
            block["database"] = database_expr
        if schema_expr:
            block["schema"] = schema_expr
        block["tables"] = grouped[key]
        sources_list.append(block)

    source_def: Dict[str, Any] = {
        "version": 2,
        "sources": sources_list,
    }

    return _HEADER + yaml.dump(
        source_def, default_flow_style=False, sort_keys=False, allow_unicode=True
    )


def generate_sources_from_logical_model(logical_model: Mapping[str, Any]) -> Optional[str]:
    """Generate dbt sources from a forged DDL logical sidecar.

    DDL-driven models do not have ``consumes[]`` lineage yet, but their OSI
    datasets still carry the source table names and columns. Emitting a
    ``raw`` source block lets generated models use ``source('raw', table)``
    in production while the model SQL guards missing local relations for
    offline smoke runs.
    """
    source_summary = logical_model.get("source_summary") or {}
    if source_summary.get("source_kind") != "ddl":
        return None
    osi = logical_model.get("osi") or {}
    datasets = osi.get("datasets") or []
    tables: List[Dict[str, Any]] = []
    for dataset in datasets:
        if not isinstance(dataset, Mapping):
            continue
        name = str(dataset.get("source") or dataset.get("name") or "").strip()
        if not name:
            continue
        entry: Dict[str, Any] = {"name": name}
        fields = dataset.get("fields") or []
        columns = []
        for field in fields:
            if isinstance(field, Mapping) and field.get("name"):
                columns.append({"name": str(field["name"])})
        if columns:
            entry["columns"] = columns
        tables.append(entry)
    if not tables:
        return None

    source_def: Dict[str, Any] = {
        "version": 2,
        "sources": [
            {
                "name": "raw",
                "description": "Source tables inferred from the forged DDL sidecar",
                "schema": "{{ env_var('FLUID_SOURCE_SCHEMA', env_var('SNOWFLAKE_STAGE_SCHEMA', target.schema)) }}",
                "tables": tables,
            }
        ],
    }
    return _HEADER + yaml.dump(
        source_def, default_flow_style=False, sort_keys=False, allow_unicode=True
    )


# ---------------------------------------------------------------------------
# Binding resolution
# ---------------------------------------------------------------------------


def _resolve_binding(
    port: Mapping[str, Any],
    upstream_index: Mapping[str, Mapping[str, Any]],
) -> Dict[str, Optional[str]]:
    """Resolve a consume to ``{database_expr, schema_expr, identifier}``.

    Tries the upstream contract index first; falls back to env_var-style
    placeholders when the upstream cannot be located.
    """
    expose_id = port.get("id") or ""
    product_id = port.get("reference")

    upstream = upstream_index.get(product_id) if product_id else None
    if upstream:
        for expose in upstream.get("exposes") or []:
            if not isinstance(expose, Mapping):
                continue
            if (expose.get("exposeId") or expose.get("id")) != expose_id:
                continue
            binding = expose.get("binding") or {}
            location = binding.get("location") or {}
            if not isinstance(location, Mapping):
                location = {}
            return {
                "database_expr": _normalize_placeholder(location.get("database")),
                "schema_expr": _normalize_placeholder(
                    location.get("schema") or location.get("dataset")
                ),
                "identifier": _identifier_from_location(location, expose_id),
            }

    # Fallback — we didn't find the upstream contract or the specific expose.
    # Emit env_var placeholders so dbt still compiles; the user can correct
    # them by setting SNOWFLAKE_DATABASE / SNOWFLAKE_STAGE_SCHEMA (or via
    # env vars for other warehouses).
    _logger.debug(
        "sources: upstream %s/%s not resolved; using env_var fallback",
        product_id,
        expose_id,
    )
    return {
        "database_expr": "{{ env_var('SNOWFLAKE_DATABASE') }}",
        "schema_expr": "{{ env_var('SNOWFLAKE_STAGE_SCHEMA', 'PUBLIC') }}",
        "identifier": expose_id.upper() if expose_id else None,
    }


def _identifier_from_location(
    location: Mapping[str, Any],
    default: str,
) -> Optional[str]:
    for key in ("table", "object", "view", "path"):
        value = location.get(key)
        if isinstance(value, str) and value.strip():
            return _normalize_placeholder(value)
    if default:
        return default.upper()
    return None


def _normalize_placeholder(value: Any) -> Optional[str]:
    """Rewrite FLUID/shell env-style placeholders to dbt ``env_var(...)``.

    dbt source blocks support Jinja that's rendered at parse time. FLUID
    contracts ship with ``{{ env.FOO }}`` or ``${FOO}`` — dbt doesn't
    understand those shapes, so we translate them to ``env_var('FOO')``.
    Literal (non-placeholder) strings are returned unchanged.
    """
    if value is None:
        return None
    if not isinstance(value, str):
        return str(value)
    text = value.strip()
    if not text:
        return None

    text = _FLUID_ENV_RE.sub(lambda m: f"{{{{ env_var('{m.group(1)}') }}}}", text)
    text = _SHELL_ENV_RE.sub(lambda m: f"{{{{ env_var('{m.group(1)}') }}}}", text)
    return text


# ---------------------------------------------------------------------------
# Column projection
# ---------------------------------------------------------------------------


def _columns_for_source(
    table_name: str,
    schema_context: Optional[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """Extract column definitions from schema_context for a source table."""
    if not schema_context:
        return []

    schemas = schema_context.get("schemas", {})
    table_schema = schemas.get(table_name)
    if not table_schema:
        for key, schema in schemas.items():
            base = key.rsplit(".", 1)[0] if "." in key else key
            if base == table_name or base.replace("-", "_") == table_name:
                table_schema = schema
                break

    if not table_schema or not isinstance(table_schema, dict):
        return []

    columns_map = table_schema.get("columns", {})
    if not isinstance(columns_map, dict):
        return []

    columns: List[Dict[str, Any]] = []
    for col_name, _col_type in columns_map.items():
        col_entry: Dict[str, Any] = {"name": col_name}
        if col_name.endswith("_id") or col_name == "id":
            col_entry["tests"] = ["unique", "not_null"]
        columns.append(col_entry)

    return columns
