# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Airflow DAG Generation for Snowflake Provider.

Generates Python DAG files from FLUID contracts for Airflow with Snowflake.

Supports:
- Database and schema management
- Table creation and queries
- Stored procedures
- Data loading operations
"""

from datetime import datetime
from typing import Any, Dict, List

from fluid_build.providers.common.codegen_utils import py_str_literal, sanitize_identifier


def generate_airflow_dag(
    contract: Dict[str, Any], account: str, database: str, warehouse: str = "COMPUTE_WH"
) -> str:
    """
    Generate Airflow DAG Python code from FLUID contract.

    Args:
        contract: FLUID contract with orchestration section
        account: Snowflake account ID
        database: Snowflake database
        warehouse: Snowflake warehouse (default: COMPUTE_WH)

    Returns:
        Python code for Airflow DAG
    """
    orchestration = contract.get("orchestration", {})
    if not orchestration:
        raise ValueError("Contract missing orchestration section")

    tasks = orchestration.get("tasks", [])
    if not tasks:
        raise ValueError("Orchestration has no tasks")

    # Extract configuration
    contract_id = contract.get("id", "unknown")
    contract_name = contract.get("name", contract_id)
    schedule = orchestration.get("schedule", "0 2 * * *")
    timezone = orchestration.get("timezone", "UTC")

    # Filter provider action tasks
    provider_tasks = [t for t in tasks if t.get("type") == "provider_action"]

    # Generate DAG code
    dag_code = _generate_dag_header(
        contract_id, contract_name, schedule, timezone, account, database, warehouse
    )
    dag_code += "\n\n"
    dag_code += _generate_dag_imports()
    dag_code += "\n\n"
    dag_code += _generate_dag_definition(contract_id, contract_name, schedule, timezone)
    dag_code += "\n\n"
    dag_code += _generate_task_definitions(provider_tasks, account, database, warehouse)
    dag_code += "\n\n"
    dag_code += _generate_task_dependencies(provider_tasks)

    return dag_code


def _generate_dag_header(
    contract_id: str,
    contract_name: str,
    schedule: str,
    timezone: str,
    account: str,
    database: str,
    warehouse: str,
) -> str:
    """Generate DAG file header with metadata.

    The header is a ``\"\"\"``-delimited docstring in the generated file. Every
    interpolated, contract-derived value is escaped via ``_escape_for_docstring``
    so a value containing ``\"\"\"`` (or a trailing ``"``) cannot terminate the
    docstring and turn following text into a top-level statement that Airflow
    would execute at DAG-parse time.
    """
    contract_name = _escape_for_docstring(contract_name)
    contract_id = _escape_for_docstring(contract_id)
    schedule = _escape_for_docstring(schedule)
    timezone = _escape_for_docstring(timezone)
    account = _escape_for_docstring(account)
    database = _escape_for_docstring(database)
    warehouse = _escape_for_docstring(warehouse)
    return f'''"""
FLUID Generated DAG: {contract_name}

Contract ID: {contract_id}
Schedule: {schedule}
Timezone: {timezone}
Snowflake Account: {account}
Database: {database}
Warehouse: {warehouse}

Auto-generated by FLUID Forge - DO NOT EDIT MANUALLY
Generated: {datetime.utcnow().isoformat()}Z
"""'''


def _escape_for_docstring(value: Any) -> str:
    """Escape a value for safe interpolation into a ``\"\"\"``-delimited docstring.

    Backslashes are escaped first, then double-quotes, so no embedded ``\"\"\"``
    (or a trailing ``"`` butting up against the closing delimiter) can terminate
    the generated docstring. This is the docstring analogue of
    ``escape_sql_for_python`` and keeps the text lossless (an escaped ``\\"`` is
    rendered, not a terminator).
    """
    s = "" if value is None else str(value)
    s = s.replace("\\", "\\\\")
    s = s.replace('"', '\\"')
    return s


def _generate_dag_imports() -> str:
    """Generate import statements."""
    return """from datetime import datetime, timedelta
from zoneinfo import ZoneInfo
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.providers.snowflake.operators.snowflake import SnowflakeOperator
from airflow.providers.snowflake.hooks.snowflake import SnowflakeHook
import json
import logging

logger = logging.getLogger(__name__)"""


def _generate_dag_definition(
    contract_id: str, contract_name: str, schedule: str, timezone: str
) -> str:
    """Generate DAG definition with default arguments."""
    airflow_schedule = _convert_schedule(schedule)

    # All contract-derived values are emitted as repr()-escaped literals
    # (py_str_literal) so a malicious name/timezone/schedule/id cannot break
    # out of its string and inject code that Airflow runs at DAG-parse time.
    # dag_id is sanitised to a bare identifier first, then literal-quoted.
    dag_id_lit = py_str_literal(_sanitize_dag_id(contract_id))
    description_lit = py_str_literal(contract_name)
    schedule_lit = py_str_literal(airflow_schedule)
    timezone_lit = py_str_literal(timezone)
    tags = ["fluid", "auto-generated", "snowflake", contract_id]

    return f"""# Default DAG arguments
default_args = {{
    'owner': 'fluid-forge',
    'depends_on_past': False,
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 3,
    'retry_delay': timedelta(minutes=5),
    'execution_timeout': timedelta(hours=2),
}}

# DAG definition
dag = DAG(
    dag_id={dag_id_lit},
    default_args=default_args,
    description={description_lit},
    schedule_interval={schedule_lit},
    start_date=datetime(2026, 1, 1, tzinfo=ZoneInfo({timezone_lit})),
    catchup=False,
    tags={tags!r},
)

# Snowflake connection ID (configure in Airflow UI or via env vars)
SNOWFLAKE_CONN_ID = 'snowflake_default'  """


def _generate_task_definitions(
    tasks: List[Dict[str, Any]], account: str, database: str, warehouse: str
) -> str:
    """Generate task definitions."""
    task_code = "# Task definitions\n"

    for task in tasks:
        task_code += _generate_single_task(task, account, database, warehouse)
        task_code += "\n\n"

    return task_code.rstrip()


def _generate_single_task(task: Dict[str, Any], account: str, database: str, warehouse: str) -> str:
    """Generate code for a single task."""
    task.get("taskId")
    action = task.get("action", "")
    params = task.get("params", {})

    # Parse action (e.g., "snowflake.database.create")
    action_parts = action.split(".")
    if len(action_parts) < 3:
        return _generate_python_task(task, account, database)

    service = action_parts[1]
    operation = action_parts[2]

    # Map to appropriate Snowflake operator
    if service in ("database", "schema", "table", "query"):
        return _generate_snowflake_sql_task(task, operation, params, database, warehouse)
    else:
        return _generate_python_task(task, account, database)


def _generate_snowflake_sql_task(
    task: Dict[str, Any], operation: str, params: Dict[str, Any], database: str, warehouse: str
) -> str:
    """Generate Snowflake SQL task code."""
    task_id = task.get("taskId")

    if operation == "create_database":
        db_name = params.get("database", "UNKNOWN_DB")
        sql = f"CREATE DATABASE IF NOT EXISTS {db_name}"

    elif operation == "create_schema":
        schema_name = params.get("schema", "UNKNOWN_SCHEMA")
        db_name = params.get("database", database)
        sql = f"CREATE SCHEMA IF NOT EXISTS {db_name}.{schema_name}"

    elif operation == "create_table":
        table_name = params.get("table", "UNKNOWN_TABLE")
        schema_name = params.get("schema", "PUBLIC")
        db_name = params.get("database", database)
        columns = params.get("columns", [])

        if columns:
            cols_def = ", ".join([f"{c['name']} {c['type']}" for c in columns])
            sql = f"CREATE TABLE IF NOT EXISTS {db_name}.{schema_name}.{table_name} ({cols_def})"
        else:
            sql = f"CREATE TABLE IF NOT EXISTS {db_name}.{schema_name}.{table_name} (id INTEGER, created_at TIMESTAMP_NTZ)"

    elif operation == "query" or operation == "run_query":
        sql = params.get("sql", params.get("query", "SELECT 1"))

    else:
        sql = f"SELECT 'Operation: {operation}' AS result"

    # repr() (via py_str_literal) escapes embedded quotes / triple-quotes /
    # newlines, so a contract-supplied sql value cannot terminate the literal
    # and inject a top-level statement that Airflow would execute at DAG-parse
    # time. The LHS variable name is sanitised to a legal Python identifier so
    # an untrusted taskId can't inject a bare statement either.
    var = sanitize_identifier(task_id)
    task_id_lit = py_str_literal(task_id)
    sql_lit = py_str_literal(sql)
    warehouse_lit = py_str_literal(warehouse)
    database_lit = py_str_literal(database)

    return f"""{var} = SnowflakeOperator(
    task_id={task_id_lit},
    snowflake_conn_id=SNOWFLAKE_CONN_ID,
    sql={sql_lit},
    warehouse={warehouse_lit},
    database={database_lit},
    dag=dag,
)"""


def _generate_python_task(task: Dict[str, Any], account: str, database: str) -> str:
    """Generate generic Python task.

    Quote safety: interpolating ``{params!r}`` inside a single-quoted string
    literal is unsafe — ``repr({'k': 'v'})`` contains single quotes that
    terminate the outer literal (SyntaxError at best, code injection at worst).
    Instead serialise params via ``json.dumps`` (double-quoted JSON) and emit
    every interpolated value through ``py_str_literal`` / ``sanitize_identifier``
    so untrusted contract content cannot inject code at DAG-parse time.
    """
    import json

    task_id = task.get("taskId") or "unnamed_task"
    action = task.get("action") or ""
    params = task.get("params", {})

    var = sanitize_identifier(task_id)
    task_id_lit = py_str_literal(task_id)
    action_lit = py_str_literal(action)
    params_json_lit = repr(json.dumps(params, sort_keys=True))

    return f"""{var} = PythonOperator(
    task_id={task_id_lit},
    python_callable=lambda: logger.info(
        'Action: ' + {action_lit} + ', Params: ' + {params_json_lit}
    ),
    dag=dag,
)"""


def _generate_task_dependencies(tasks: List[Dict[str, Any]]) -> str:
    """Generate task dependency declarations."""
    if not tasks:
        return "# No task dependencies"

    dep_code = "# Task dependencies\n"

    for task in tasks:
        task_id = task.get("taskId")
        depends_on = task.get("dependsOn", [])

        if depends_on:
            # These are Python *variable names*, so both sides must be
            # sanitised to match the identifiers the task generators emit
            # (sanitize_identifier(taskId) = Operator(...)) — otherwise an
            # untrusted taskId / dependsOn entry could inject code as a bare
            # identifier, and a non-identifier id would dangle and fail to parse.
            safe_task = sanitize_identifier(task_id)
            safe_deps = [sanitize_identifier(dep) for dep in depends_on]
            if len(safe_deps) == 1:
                dep_code += f"{safe_deps[0]} >> {safe_task}\n"
            else:
                dep_code += f"[{', '.join(safe_deps)}] >> {safe_task}\n"

    return dep_code.rstrip()


def _convert_schedule(schedule: str) -> str:
    """Convert FLUID schedule to Airflow schedule_interval."""
    schedule_lower = schedule.lower()
    if schedule_lower in ("@hourly", "@daily", "@weekly", "@monthly"):
        return schedule_lower

    if schedule.count(" ") >= 4:
        return schedule

    return "@daily"


def _sanitize_dag_id(dag_id: str) -> str:
    """Sanitize DAG ID for Airflow (alphanumeric and underscores only)."""
    import re

    return re.sub(r"[^a-zA-Z0-9_]", "_", dag_id)
