# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Prefect Flow Generation for Snowflake Provider.

Generates Python flow code from FLUID contracts for Prefect with Snowflake.

Every contract-derived value that lands in the emitted source goes through
``providers/common/codegen_utils``: ``py_str_literal`` for data,
``sanitize_identifier`` for names the generated file binds, and
``escape_for_docstring`` for docstrings. This matters more here than in the
Airflow emitters: the splices sit at *module scope* inside ``@flow`` / ``@task``
decorators, so an unescaped payload runs on a plain ``import`` of the generated
file — ``prefect deploy``, a worker picking the flow up, or a developer opening
it in a REPL.
"""

import json
from datetime import datetime
from datetime import timezone as dt_timezone
from typing import Any, Dict, List

from fluid_build.providers.common.codegen_utils import (
    escape_for_docstring,
    json_literal,
    py_str_literal,
    sanitize_identifier,
    task_identifier,
)


def _task_func_name(task_spec: Dict[str, Any]) -> str:
    """Resolve the Python function name a task is emitted as.

    Both the definition (``def <name>():``) and the flow-body call
    (``<name>_result = <name>()``) resolve through this one helper, so the two
    sides cannot drift — a mismatch emits a file that calls an undefined name.
    ``or ""`` guards a missing ``taskId``, which used to emit ``def None():``.
    """
    return task_identifier(task_spec.get("taskId") or "")


def generate_prefect_flow(
    contract: Dict[str, Any], account: str, database: str, warehouse: str = "COMPUTE_WH"
) -> str:
    """Generate Prefect flow from FLUID contract."""
    orchestration = contract.get("orchestration", {})
    if not orchestration:
        raise ValueError("Contract missing orchestration section")

    tasks = orchestration.get("tasks", [])
    provider_tasks = [t for t in tasks if t.get("type") == "provider_action"]

    contract_id = contract.get("id", "unknown")
    contract_name = contract.get("name", contract_id)
    schedule = orchestration.get("schedule", "0 2 * * *")
    timezone = orchestration.get("timezone", "UTC")

    code = _generate_header(contract_id, contract_name, account, database, warehouse)
    code += "\n\n"
    code += _generate_imports()
    code += "\n\n"
    code += _generate_config(account, database, warehouse)
    code += "\n\n"
    code += _generate_tasks(provider_tasks, database, warehouse)
    code += "\n\n"
    code += _generate_flow(contract_id, contract_name, provider_tasks)
    code += "\n\n"
    code += _generate_deployment(contract_id, contract_name, schedule, timezone)

    return code


def _generate_header(
    contract_id: str, contract_name: str, account: str, database: str, warehouse: str
) -> str:
    # Every contract-derived field is escaped so it cannot terminate this
    # docstring. A ``name`` carrying a triple quote used to close the module
    # docstring and leave the rest of the value at module scope, where Prefect
    # runs it the moment the flow file is imported. The ``"""`` delimiters
    # below are this generator's own and stay: escape_for_docstring returns a
    # bare escaped string, not a literal, so nothing is written around the
    # placeholders.
    return f'''"""
FLUID Generated Prefect Flow: {escape_for_docstring(contract_name)}

Contract ID: {escape_for_docstring(contract_id)}
Snowflake Account: {escape_for_docstring(account)}
Database: {escape_for_docstring(database)}
Warehouse: {escape_for_docstring(warehouse)}

Auto-generated by FLUID Forge
Generated: {datetime.now(dt_timezone.utc).replace(tzinfo=None).isoformat()}Z
"""'''


def _generate_imports() -> str:
    # ``json`` is needed by the generic task, which rebuilds its params with
    # json.loads rather than carrying a repr spliced into the source.
    # Credentials are read through Prefect's own ``Secret`` block instead of
    # ``os.getenv``: keeping every ``os``/``subprocess`` import out of the
    # emitted file is what lets a reviewer (and the codegen-injection pin)
    # treat the presence of one as evidence that a contract value became code.
    # It also matches the Snowflake Airflow emitter, which takes credentials
    # from the orchestrator's connection store rather than from the DAG file.
    return """from prefect import flow, task
from prefect.blocks.system import Secret
from prefect.deployments import Deployment
from prefect.server.schemas.schedules import CronSchedule
from snowflake.connector import connect
import json
import logging

logger = logging.getLogger(__name__)"""


def _generate_config(account: str, database: str, warehouse: str) -> str:
    # py_str_literal returns a repr(), which brings its own quotes — the
    # hand-written ones that used to wrap these three placeholders are gone.
    # With them, a warehouse of ``WH" ; import os ; x = "`` closed the literal
    # and left a statement at module scope, executed on import.
    return f'''# Snowflake Configuration
SNOWFLAKE_ACCOUNT = {py_str_literal(account)}
SNOWFLAKE_DATABASE = {py_str_literal(database)}
SNOWFLAKE_WAREHOUSE = {py_str_literal(warehouse)}
SNOWFLAKE_SCHEMA = "PUBLIC"

def get_snowflake_connection():
    """Get Snowflake connection.

    User and password come from the Prefect ``Secret`` blocks
    ``snowflake-user`` and ``snowflake-password``. Seed them once with:

        from prefect.blocks.system import Secret
        Secret(value="...").save("snowflake-user")
        Secret(value="...").save("snowflake-password")
    """
    return connect(
        account=SNOWFLAKE_ACCOUNT,
        user=Secret.load("snowflake-user").get(),
        password=Secret.load("snowflake-password").get(),
        database=SNOWFLAKE_DATABASE,
        warehouse=SNOWFLAKE_WAREHOUSE,
        schema=SNOWFLAKE_SCHEMA
    )'''


def _generate_tasks(tasks: List[Dict[str, Any]], database: str, warehouse: str) -> str:
    tasks_code = "# Prefect Tasks\n"
    for task_spec in tasks:
        tasks_code += _generate_single_task(task_spec, database, warehouse)
        tasks_code += "\n\n"
    return tasks_code.rstrip()


def _generate_single_task(task_spec: Dict[str, Any], database: str, warehouse: str) -> str:
    action = task_spec.get("action", "")
    params = task_spec.get("params", {})
    # The task's ``def`` name is a Python identifier, so it goes through
    # sanitize_identifier (shared with the flow body below via _task_func_name).
    # Raw, an ordinary ``load-raw`` emitted ``def load-raw():`` and a taskId
    # carrying a newline put a statement at module scope.
    func = _task_func_name(task_spec)

    action_parts = action.split(".")
    if len(action_parts) >= 3:
        operation = action_parts[2]

        if operation == "query" or operation == "run_query":
            sql = params.get("sql", params.get("query", "SELECT 1"))

            # py_str_literal replaces a hand-rolled replace()-based escaper
            # that handled quotes and backslashes but not newlines: an ordinary
            # multi-line SELECT emitted an unterminated single-line literal and
            # the whole flow file failed to import. repr() picks its own quote
            # style, so the hand-written "" around the placeholder are gone.
            return f'''@task(retries=3, retry_delay_seconds=30, timeout_seconds=1800)
def {func}():
    """Execute Snowflake query"""
    conn = get_snowflake_connection()
    cursor = conn.cursor()
    try:
        cursor.execute({py_str_literal(sql)})
        results = cursor.fetchall()
        logger.info(f"Query executed: {{{{len(results)}}}} rows")
        return len(results)
    finally:
        cursor.close()
        conn.close()'''

    # Generic fallback. The emitted logger call deliberately loses the ``f``
    # prefix it used to carry: repr() escapes quotes and backslashes but NOT
    # braces, so a ``{`` in ``action`` survived into a generated f-string as a
    # live expression evaluated at task run. %s-style lazy logging has no brace
    # semantics at all, which closes that channel for good. ``params`` is
    # rebuilt with json.loads for the same reason — see _json_literal.
    return f'''@task(retries=2, retry_delay_seconds=30)
def {func}():
    """Generic task: {escape_for_docstring(action)}"""
    params = json.loads({json_literal(params)})
    logger.info("Action: %s, Params: %s", {py_str_literal(action)}, params)
    return True'''


def _generate_flow(contract_id: str, contract_name: str, tasks: List[Dict[str, Any]]) -> str:
    # sanitize_identifier, not the former local _sanitize_name: that one only
    # collapsed non-alphanumerics, so ``2024-orders`` emitted
    # ``def 2024_orders_flow():`` (SyntaxError) and ``class`` emitted a keyword.
    # The deployment block below derives its name from the same call, so the
    # definition and the reference cannot drift.
    flow_name = task_identifier(contract_id)
    task_executions = []
    for task in tasks:
        func = _task_func_name(task)
        task_executions.append(f"    {func}_result = {func}()")

    task_exec_str = "\n".join(task_executions)

    return f'''# Flow definition
@flow(
    name={py_str_literal(flow_name)},
    description={py_str_literal(contract_name)},
    retries=1,
    retry_delay_seconds=60,
)
def {flow_name}_flow():
    """{escape_for_docstring(contract_name)} flow on Snowflake."""
{task_exec_str}

    logger.info("Flow completed successfully")
    return True'''


def _generate_deployment(contract_id: str, contract_name: str, schedule: str, timezone: str) -> str:
    flow_name = task_identifier(contract_id)
    deployment_name = f"{flow_name}-deployment"
    cron_schedule = _convert_schedule(schedule)
    # Build the tag list in Python and emit its repr: one literal whose quotes
    # and escaping repr() supplies, so a quote in the contract id cannot break
    # out of the hand-written list. Same idiom as aws/codegen/airflow.py.
    tags = ["fluid", "auto-generated", "snowflake", str(contract_id)]
    # These two console lines are emitted as plain literals, without the ``f``
    # prefix they used to carry. Nothing in them needs run-time evaluation, and
    # an ``f`` turns a ``{`` in the schedule or timezone into a live expression
    # in the generated file — the channel repr() does not close. Assembling the
    # text here and escaping the whole line once is the clearer fix.
    schedule_line = f"   Schedule: {cron_schedule} ({timezone})"
    run_line = f"   Run: prefect deployment run '{flow_name}_flow/{deployment_name}'"

    return f"""# Deployment configuration
if __name__ == "__main__":
    deployment = Deployment.build_from_flow(
        flow={flow_name}_flow,
        name={py_str_literal(deployment_name)},
        version="1.0",
        tags={tags!r},
        schedule=CronSchedule(
            cron={py_str_literal(cron_schedule)},
            timezone={py_str_literal(timezone)},
        ),
        work_queue_name="default",
    )

    deployment.apply()

    success(f"Deployment created: {{deployment.name}}")
    cprint({py_str_literal(schedule_line)})
    cprint({py_str_literal(run_line)})"""


def _convert_schedule(schedule: str) -> str:
    schedule_lower = schedule.lower()
    if schedule_lower == "@hourly":
        return "0 * * * *"
    elif schedule_lower == "@daily":
        return "0 0 * * *"
    elif schedule_lower == "@weekly":
        return "0 0 * * 0"
    elif schedule_lower == "@monthly":
        return "0 0 1 * *"
    if schedule.count(" ") >= 4:
        return schedule
    return "0 2 * * *"


# ``_sanitize_name`` (a local re.sub that handled neither leading digits, nor
# Python keywords, nor the empty string) is gone: every identifier this module
# emits now goes through codegen_utils.sanitize_identifier, which does.
