# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Regression tests: untrusted contract values must not become code in the
generated Prefect flow / Dagster pipeline files.

These six emitters are the siblings of the Airflow generators pinned by
``tests/test_airflow_codegen_injection.py``. They were missed by the #215
hardening pass and by #630, and carried **zero** calls to the shared
``codegen_utils`` escapers.

They are a more severe sink than the Airflow ones. An Airflow payload runs
when the scheduler parses the DAG; here the splices land inside *module-level*
``@flow`` / ``@task`` / ``@job`` decorators, so the payload runs on any plain
``import`` of the generated file — ``prefect deploy``, a Prefect worker,
``dagster dev``, or a developer opening the file in a REPL.

Three distinct channels are pinned, because closing only the first leaves the
others open:

1. **Quote break-out** — the classic. Closed by ``py_str_literal`` (``repr``).
2. **Brace / f-string** — these emitters write generated lines that keep an
   ``f`` prefix (e.g. ``logger.info(f"Executing: {action}")``). A ``{`` in a
   contract value then becomes an *expression evaluated at task run*.
   ``repr()`` escapes quotes and backslashes but **not** braces, so
   ``py_str_literal`` alone does not close this one.
3. **Identifier position** — a ``taskId`` becoming a generated ``def`` name.

Assertions are on the parsed AST, never on generated bytes, so a formatter
cannot make them flaky — and a formatter is not a safety layer: injected
Python formats perfectly well.
"""

from __future__ import annotations

import ast

import pytest

# Quote break-out: close the literal, run a statement, reopen.
POC_SQUOTE = "x'; import os; os.system('touch /tmp/PWNED')\ny='"
POC_DQUOTE = 'x"; import os; os.system("touch /tmp/PWNED")\ny="'
# Triple-quote break-out, for docstring and triple-quoted sinks.
POC_TRIPLE = 'SELECT 1"""\nimport os; os.system("touch /tmp/PWNED")\nx="""'
# Brace channel: harmless inside a plain string, live code inside an f-string.
POC_BRACE = "value{__import__('os').system('touch /tmp/PWNED')}tail"
# Identifier position: a taskId that would become `def ...` in the output.
POC_IDENT = "t_evil\nimport os; os.system('touch /tmp/PWNED')\nx = "
# Ordinary, benign, and still fatal before the fix.
BENIGN_APOSTROPHE = "SELECT * FROM t WHERE c = 'a'"

_DANGEROUS_CALLS = {"system", "popen", "exec", "eval", "__import__", "spawn", "Popen", "getcwd"}
_DANGEROUS_MODULES = {"os", "subprocess", "sys", "shutil", "socket"}


def assert_inert(code: str) -> ast.Module:
    """Parse ``code`` and assert it contains no executable injected construct.

    Mechanism-agnostic: it does not care *how* the emitter escaped, only that
    the payload survives as inert data rather than as an AST node that runs.
    """
    tree = ast.parse(code)  # SyntaxError here means a payload broke the file
    offenders = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            name = getattr(node.func, "id", None) or getattr(node.func, "attr", None)
            if name in _DANGEROUS_CALLS:
                offenders.append(f"call:{name}")
        if isinstance(node, ast.Import):
            offenders.extend(
                f"import:{a.name}" for a in node.names if a.name.split(".")[0] in _DANGEROUS_MODULES
            )
        if (
            isinstance(node, ast.ImportFrom)
            and (node.module or "").split(".")[0] in _DANGEROUS_MODULES
        ):
            offenders.append(f"from:{node.module}")
    assert not offenders, f"code injection: generated file executes {offenders}\n---\n{code}"
    return tree


def assert_no_live_fstring_payload(code: str) -> None:
    """Assert no generated f-string evaluates a contract-derived expression.

    This is the channel ``repr()`` does not close. An emitted
    ``logger.info(f"Executing: {action}")`` turns any ``{`` in ``action`` into
    a live expression. We assert that every f-string in the generated file has
    only *simple* interpolations — names and attribute/subscript chains the
    emitter itself wrote — never a call.
    """
    tree = ast.parse(code)
    bad = []
    for node in ast.walk(tree):
        if isinstance(node, ast.JoinedStr):
            for part in node.values:
                if not isinstance(part, ast.FormattedValue):
                    continue
                for sub in ast.walk(part.value):
                    if isinstance(sub, ast.Call):
                        fn = getattr(sub.func, "id", None) or getattr(sub.func, "attr", None)
                        bad.append(f"line {getattr(node, 'lineno', '?')}: call {fn} in f-string")
    assert not bad, f"live expression injected via f-string brace channel: {bad}\n---\n{code}"


def assert_payload_is_inert_data(code: str, payload: str) -> None:
    """Escaping, not stripping: the payload must survive as readable data."""
    tree = ast.parse(code)
    literals = [
        n.value for n in ast.walk(tree) if isinstance(n, ast.Constant) and isinstance(n.value, str)
    ]
    assert any(
        payload in lit for lit in literals
    ), "payload was mangled or dropped rather than escaped — escaping must preserve the value"


# ---------------------------------------------------------------------------
# Emitter matrix
# ---------------------------------------------------------------------------


def _contract(**over):
    """A contract whose every free-text field carries a payload."""
    base = {
        "id": "analytics.sales.orders",
        "name": POC_DQUOTE,
        "description": POC_TRIPLE,
        "orchestration": {
            "schedule": "0 2 * * *",
            "timezone": POC_SQUOTE,
            "tasks": [
                {
                    "taskId": POC_IDENT,
                    "type": "provider_action",
                    "action": POC_BRACE,
                    "params": {
                        "query": POC_TRIPLE,
                        "sql": POC_TRIPLE,
                        "database": POC_SQUOTE,
                        "bucket": POC_DQUOTE,
                        "table": POC_SQUOTE,
                        "region": POC_BRACE,
                        "function": POC_DQUOTE,
                        "enabled": True,
                        "outputLocation": POC_SQUOTE,
                    },
                },
                {
                    "taskId": "second_task",
                    "type": "provider_action",
                    "action": "x.s3.ensure_bucket",
                    "params": {"bucket": "b", "sql": BENIGN_APOSTROPHE},
                    "dependsOn": [POC_IDENT],
                },
            ],
        },
    }
    base.update(over)
    return base


def _emitters():
    """(id, callable) for all six emitters, with their differing signatures."""
    from fluid_build.providers.aws.codegen.dagster import (
        generate_dagster_pipeline as aws_dagster,
    )
    from fluid_build.providers.aws.codegen.prefect import generate_prefect_flow as aws_prefect
    from fluid_build.providers.gcp.codegen.dagster import (
        generate_dagster_pipeline as gcp_dagster,
    )
    from fluid_build.providers.gcp.codegen.prefect import generate_prefect_flow as gcp_prefect
    from fluid_build.providers.snowflake.codegen.dagster import (
        generate_dagster_pipeline as sf_dagster,
    )
    from fluid_build.providers.snowflake.codegen.prefect import (
        generate_prefect_flow as sf_prefect,
    )

    return [
        ("aws/prefect", lambda c: aws_prefect(c, "123456789012", "eu-west-1")),
        ("aws/dagster", lambda c: aws_dagster(c, "123456789012", "eu-west-1")),
        ("gcp/prefect", lambda c: gcp_prefect(c, "my-project", "us-central1")),
        ("gcp/dagster", lambda c: gcp_dagster(c, "my-project", "us-central1")),
        ("sf/prefect", lambda c: sf_prefect(c, "acct", "DB", "WH")),
        ("sf/dagster", lambda c: sf_dagster(c, "acct", "DB", "WH")),
    ]


def _ids():
    return [i for i, _ in _emitters()]


def _fn(name):
    return dict(_emitters())[name]


@pytest.mark.parametrize("emitter", _ids())
def test_emitter_is_injection_safe(emitter):
    """No contract value may become an executable construct."""
    assert_inert(_fn(emitter)(_contract()))


@pytest.mark.parametrize("emitter", _ids())
def test_emitter_closes_fstring_brace_channel(emitter):
    """A `{` in a contract value must not become a live expression.

    `repr()` does not escape braces, so this is NOT closed by py_str_literal
    alone — the emitter must drop the `f` prefix or double the braces.
    """
    assert_no_live_fstring_payload(_fn(emitter)(_contract()))


@pytest.mark.parametrize("emitter", _ids())
def test_emitter_output_compiles(emitter):
    """The generated file must be importable Python, payload or not."""
    code = _fn(emitter)(_contract())
    compile(code, "generated.py", "exec")


@pytest.mark.parametrize("emitter", _ids())
def test_benign_apostrophe_does_not_break_output(emitter):
    """The bug users hit first, with no attacker involved."""
    c = _contract(name="Orders", description="ordinary")
    c["orchestration"]["tasks"] = [
        {
            "taskId": "q1",
            "type": "provider_action",
            "action": "x.athena.execute_query",
            "params": {
                "query": BENIGN_APOSTROPHE,
                "sql": BENIGN_APOSTROPHE,
                "database": "db",
                "bucket": "b",
            },
        }
    ]
    code = _fn(emitter)(c)
    compile(code, "generated.py", "exec")
    assert_payload_is_inert_data(code, BENIGN_APOSTROPHE)


@pytest.mark.parametrize("emitter", _ids())
def test_multiline_sql_does_not_break_output(emitter):
    """Hand-rolled escapers in these files handle quotes but not newlines."""
    c = _contract(name="Orders", description="ordinary")
    c["orchestration"]["tasks"] = [
        {
            "taskId": "q1",
            "type": "provider_action",
            "action": "x.athena.execute_query",
            "params": {
                "query": "SELECT a,\n  b\nFROM t",
                "sql": "SELECT a,\n  b\nFROM t",
                "database": "db",
                "bucket": "b",
            },
        }
    ]
    compile(_fn(emitter)(c), "generated.py", "exec")


# ---------------------------------------------------------------------------
# Identifier agreement and shared-helper key coercion
#
# Both of these were found by the defect scan AFTER the injection matrix above
# was already green — the escaping was right and the surrounding code was not.
# ---------------------------------------------------------------------------


# Undefined names that are PRE-EXISTING and deliberately out of scope for this
# security change: `cprint` (a typo for print) and `success` in the Prefect
# emitters. They are recorded as acceptance criteria on the Prefect 3 port
# (issue #631). Allow-listed here so this oracle still fails on any NEW
# undefined name introduced by identifier work — which is what it is for.
_KNOWN_PREEXISTING_UNDEFINED = {"cprint", "success"}


def _assert_no_undefined_names(code: str) -> None:
    tree = ast.parse(code)
    bound = set(dir(__import__("builtins"))) | _KNOWN_PREEXISTING_UNDEFINED
    for node in ast.walk(tree):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            bound.update((a.asname or a.name).split(".")[0] for a in node.names)
        elif isinstance(node, ast.Name) and isinstance(node.ctx, (ast.Store, ast.Del)):
            bound.add(node.id)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            bound.add(node.name)
            args = getattr(node, "args", None)
            if args is not None:
                bound.update(
                    a.arg
                    for a in [*args.posonlyargs, *args.args, *args.kwonlyargs]
                    + [args.vararg, args.kwarg]
                    if a is not None
                )
        elif isinstance(node, ast.Lambda):
            a = node.args
            bound.update(
                x.arg
                for x in [*a.posonlyargs, *a.args, *a.kwonlyargs] + [a.vararg, a.kwarg]
                if x is not None
            )
    undefined = sorted(
        {
            n.id
            for n in ast.walk(tree)
            if isinstance(n, ast.Name) and isinstance(n.ctx, ast.Load) and n.id not in bound
        }
    )
    assert not undefined, f"generated file references undefined names {undefined}\n---\n{code}"


@pytest.mark.parametrize("emitter", _ids())
def test_leading_digit_task_id_wires_to_a_name_that_exists(emitter):
    """The `def` name and the dependency `_result` value must agree.

    ``task_identifier`` prefixes a leading digit where ``sanitize_identifier``
    strips it, so deriving the two halves of a dependency edge with different
    helpers emits a reference to a name the module never binds — and if a
    sibling task happens to match the stripped form, it silently wires the
    WRONG upstream instead of failing.
    """
    c = _contract(name="Orders", description="ordinary")
    c["orchestration"]["tasks"] = [
        {
            "taskId": "2024_load",
            "type": "provider_action",
            "action": "x.s3.ensure_bucket",
            "params": {"bucket": "b", "sql": "SELECT 1", "query": "SELECT 1", "database": "d"},
        },
        {
            "taskId": "report",
            "type": "provider_action",
            "action": "x.s3.ensure_bucket",
            "params": {"bucket": "c", "sql": "SELECT 2", "query": "SELECT 2", "database": "d"},
            "dependsOn": ["2024_load"],
        },
    ]
    _assert_no_undefined_names(_fn(emitter)(c))


@pytest.mark.parametrize("emitter", _ids())
def test_leading_digit_does_not_wire_to_a_sibling(emitter):
    """The silent-miswire variant: a sibling named like the stripped form."""
    c = _contract(name="Orders", description="ordinary")
    common = {"bucket": "b", "sql": "SELECT 1", "query": "SELECT 1", "database": "d"}
    c["orchestration"]["tasks"] = [
        {
            "taskId": "2024_load",
            "type": "provider_action",
            "action": "x.s3.ensure_bucket",
            "params": dict(common),
        },
        {
            "taskId": "_load",
            "type": "provider_action",
            "action": "x.s3.ensure_bucket",
            "params": dict(common),
        },
        {
            "taskId": "report",
            "type": "provider_action",
            "action": "x.s3.ensure_bucket",
            "params": dict(common),
            "dependsOn": ["2024_load"],
        },
    ]
    code = _fn(emitter)(c)
    _assert_no_undefined_names(code)
    # `_load_result` legitimately exists as the `_load` task's own binding, so
    # check the EDGE specifically: every line wiring `report` to an upstream
    # must reference the 2024_load binding, not the sibling's.
    # Emitters differ in idiom: some pass `<op>_result`, some pass the op
    # itself. Either is fine — what matters is that the NAME is the 2024_load
    # binding and never the `_load` sibling's.
    # NB: some Prefect emitters drop the edge entirely today (`task_results` is
    # built and never read) — a pre-existing defect tracked on issue #631, not
    # this change's to fix. So this asserts "if an edge is emitted, it names the
    # right upstream", which is the identifier-agreement property under test.
    edge_lines = [ln for ln in code.splitlines() if "report" in ln and "_load" in ln]
    for ln in edge_lines:
        assert (
            "task_2024_load" in ln
        ), f"dependency edge wired to the wrong upstream: {ln.strip()!r}"


def test_json_literal_matches_json_dumps_key_spelling():
    """Keys must be coerced the way json.dumps spells them, not via str().

    PyYAML is YAML 1.1, so a bare ``on:``/``off:``/``yes:``/``no:``/``~:`` key
    parses to bool/None. ``str(True)`` is ``"True"``; JSON spells it ``"true"``.
    Getting this wrong silently renames keys in the generated output — and one
    call site ships that string straight to AWS Lambda.
    """
    from fluid_build.providers.common.codegen_utils import json_literal

    assert json_literal({True: "a", False: "b"}) == repr('{"false": "b", "true": "a"}')
    assert json_literal({None: "n"}) == repr('{"null": "n"}')
    assert json_literal({1: "x", 2.5: "y"}) == repr('{"1": "x", "2.5": "y"}')


def test_json_literal_survives_mixed_type_keys():
    """The regression shipped in #630: sort_keys=True cannot compare mixed types."""
    from fluid_build.providers.common.codegen_utils import json_literal

    assert json_literal({"a": 1, 2: "b"}) == repr('{"2": "b", "a": 1}')


def test_task_identifier_keeps_leading_digit_ids_distinct():
    from fluid_build.providers.common.codegen_utils import task_identifier

    assert task_identifier("2024_run") != task_identifier("9999_run")
    assert task_identifier("class").isidentifier()
    assert task_identifier("").isidentifier()
