# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0

"""Tests for dbt Mesh emission in ``generate speed-transformation``.

Covers the two mesh-facing changes:

1. Every expose in ``exposes[]`` automatically gets ``access: public``
   on its emitted schema.yml model (Q4 Option 1 from the plan:
   automatic, no extra contract authoring). Internal staging models
   stay on dbt's default ``access: protected``.

2. ``--mesh-hub <name>`` emits a ``dependencies.yml`` declaring the
   hub project, so downstream ``dbt deps`` pulls it in for cross-
   project ``ref('other_project', 'model')`` references.

Tests don't invoke the full CLI — they exercise
``generate_schema_yml`` directly against synthetic contracts and
assert the resulting YAML has the right mesh fields.
"""

from __future__ import annotations

from typing import Any, Dict

import pytest
import yaml

from fluid_build.engines.dbt.schema_yml import generate_schema_yml

# -----------------------------------------------------------------------------
# Fixtures
# -----------------------------------------------------------------------------


def _contract(*, expose_count: int = 1, include_dq: bool = False) -> Dict[str, Any]:
    """Build a minimal test contract with N exposes."""
    exposes = []
    for i in range(expose_count):
        expose = {
            "exposeId": f"mart_model_{i}",
            "description": f"Mart model #{i}",
            "kind": "table",
            "contract": {
                "version": "1.0.0",
                "schema": [
                    {"name": "ID", "type": "STRING", "required": True},
                    {"name": "VALUE", "type": "NUMBER"},
                ],
            },
        }
        if include_dq:
            expose["contract"]["dq"] = {
                "rules": [
                    {
                        "id": "id_not_null",
                        "type": "completeness",
                        "selector": "ID",
                        "threshold": 1.0,
                        "operator": ">=",
                        "severity": "error",
                    }
                ]
            }
        exposes.append(expose)
    return {
        "id": "test.product.v1",
        "name": "Test Product",
        "exposes": exposes,
    }


def _parse_schema_yml(out: Dict[str, str]) -> Dict[str, Any]:
    """Load the emitted schema.yml content (skipping the comment
    header) into a Python dict for assertion."""
    content = out.get("models/marts/schema.yml", "")
    assert content, "expected models/marts/schema.yml in output"
    # Strip the ``# Generated by fluid generate`` header — yaml parser
    # handles comments fine, but we want to be explicit about what we
    # assert against.
    return yaml.safe_load(content)


# -----------------------------------------------------------------------------
# Access: public annotation — Q4 Option 1 (automatic from exposes[])
# -----------------------------------------------------------------------------


class TestAccessPublic:
    def test_every_expose_gets_access_public(self):
        """Three exposes → three models with access: public.
        No extra annotation needed on the contract side."""
        contract = _contract(expose_count=3)
        out = generate_schema_yml(contract)
        parsed = _parse_schema_yml(out)
        assert len(parsed["models"]) == 3
        for model in parsed["models"]:
            assert model["access"] == "public", (
                f"Model {model['name']!r} missing access: public. "
                "Every expose is a public output port of the data "
                "product by definition — dbt Mesh requires this for "
                "cross-project ref() to work."
            )

    def test_empty_exposes_returns_no_schema_yml(self):
        """A contract without exposes has no public surface → no
        schema.yml emitted. This is the pre-uplift behaviour; mesh
        annotation must not accidentally force emission."""
        contract = {"id": "x", "exposes": []}
        out = generate_schema_yml(contract)
        assert "models/marts/schema.yml" not in out

    def test_description_preserved_alongside_access(self):
        """Adding ``access: public`` must NOT clobber the existing
        ``description`` / ``columns`` emission. They coexist."""
        contract = _contract(expose_count=1, include_dq=True)
        out = generate_schema_yml(contract)
        parsed = _parse_schema_yml(out)
        model = parsed["models"][0]
        assert model["access"] == "public"
        assert model["description"] == "Mart model #0"
        # DQ rules still generate column tests (regression guard).
        assert "columns" in model
        id_col = next(c for c in model["columns"] if c["name"] == "ID")
        assert "tests" in id_col
        assert "not_null" in id_col["tests"]


class TestModelVersioning:
    def test_expose_version_flows_into_latest_version(self):
        """``exposes[].contract.version`` becomes ``latest_version`` on
        the emitted model so dbt's model-version pinning works across
        mesh boundaries."""
        contract = _contract(expose_count=1)
        out = generate_schema_yml(contract)
        parsed = _parse_schema_yml(out)
        model = parsed["models"][0]
        assert model["latest_version"] == "1.0.0"
        assert model["versions"] == [{"v": "1.0.0"}]

    def test_missing_version_skips_versioning_fields(self):
        """When a contract doesn't declare a version (older drafts),
        the versioning fields are simply absent rather than defaulted."""
        contract = _contract(expose_count=1)
        # Strip the version field.
        del contract["exposes"][0]["contract"]["version"]
        out = generate_schema_yml(contract)
        parsed = _parse_schema_yml(out)
        model = parsed["models"][0]
        assert "latest_version" not in model
        assert "versions" not in model
        # access: public still there — versioning is orthogonal.
        assert model["access"] == "public"


# -----------------------------------------------------------------------------
# --mesh-hub flag — dependencies.yml emission
# -----------------------------------------------------------------------------


class TestMeshHub:
    def test_mesh_hub_emits_dependencies_yml(self):
        contract = _contract(expose_count=1)
        out = generate_schema_yml(contract, mesh_hub="my_hub_project")
        assert "dependencies.yml" in out
        deps = yaml.safe_load(out["dependencies.yml"])
        assert deps == {"projects": [{"name": "my_hub_project"}]}

    def test_mesh_hub_without_exposes_still_emits_dependencies_yml(self):
        """A purely-consuming product (exposes nothing, consumes from
        the hub) should still declare its hub participation — otherwise
        ``dbt deps`` wouldn't know to resolve the hub package."""
        contract = {"id": "x", "exposes": []}
        out = generate_schema_yml(contract, mesh_hub="my_hub_project")
        assert "dependencies.yml" in out
        assert "models/marts/schema.yml" not in out  # no exposes = no schema

    def test_no_mesh_hub_omits_dependencies_yml(self):
        """Without the flag, dependencies.yml is not emitted."""
        contract = _contract(expose_count=1)
        out = generate_schema_yml(contract, mesh_hub=None)
        assert "dependencies.yml" not in out

    def test_default_mesh_hub_is_none(self):
        """Positional call without mesh_hub kwarg uses None default,
        matching the Q4 Option 1 design: mesh annotations are
        automatic, hub declaration is explicit opt-in."""
        contract = _contract(expose_count=1)
        out = generate_schema_yml(contract)
        assert "dependencies.yml" not in out
        # access: public still emitted because it's automatic.
        parsed = _parse_schema_yml(out)
        assert parsed["models"][0]["access"] == "public"


# -----------------------------------------------------------------------------
# End-to-end: both annotations coexist
# -----------------------------------------------------------------------------


class TestMeshAnnotationsCoexist:
    def test_all_mesh_features_in_one_contract(self):
        """access: public on every expose + dependencies.yml for the
        hub + descriptions + DQ column tests — all coexist cleanly."""
        contract = _contract(expose_count=2, include_dq=True)
        out = generate_schema_yml(contract, mesh_hub="central_hub")
        # dependencies.yml present
        assert yaml.safe_load(out["dependencies.yml"]) == {"projects": [{"name": "central_hub"}]}
        # schema.yml has both models with mesh + DQ annotations
        parsed = _parse_schema_yml(out)
        assert len(parsed["models"]) == 2
        for model in parsed["models"]:
            assert model["access"] == "public"
            assert model["latest_version"] == "1.0.0"
            assert "description" in model
            assert "columns" in model


# -----------------------------------------------------------------------------
# Argparse registration — --mesh-hub is wired into the CLI
# -----------------------------------------------------------------------------


class TestGenerateSpeedTransformationArgparse:
    def test_mesh_hub_flag_registered(self):
        """``fluid generate speed-transformation --mesh-hub my_hub``
        parses cleanly + surfaces on the Namespace."""
        import argparse

        from fluid_build.cli import generate_speed_transformation

        parser = argparse.ArgumentParser()
        sp = parser.add_subparsers(dest="generate_sub")
        generate_speed_transformation.register_subcommand(sp)
        ns = parser.parse_args(
            [
                "speed-transformation",
                "--mesh-hub",
                "my_data_hub",
            ]
        )
        assert ns.mesh_hub == "my_data_hub"

    def test_mesh_hub_default_none(self):
        """Default of None means no mesh_hub annotation (Option 1
        automatic-only path). Operators who want the hub opt in."""
        import argparse

        from fluid_build.cli import generate_speed_transformation

        parser = argparse.ArgumentParser()
        sp = parser.add_subparsers(dest="generate_sub")
        generate_speed_transformation.register_subcommand(sp)
        ns = parser.parse_args(["speed-transformation"])
        assert ns.mesh_hub is None
