# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""dbt ``catalogs.yml`` emission for Iceberg exposes.

dbt creates the Iceberg table entry but not the external volume or catalog
integration behind it, which its own docs put on the user. These tests pin the
emitted shape against dbt's *shipped* v1 schema, the naming contract this
emitter shares with the Snowflake IaC emitter, and the cases where nothing
should be written at all.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, Optional

import pytest
import yaml

from fluid_build.engines.dbt.catalogs_yml import generate_catalogs_yml
from fluid_build.providers._iceberg_catalog import (
    iceberg_external_volume_name,
    is_glue_cataloged,
    resolve_iceberg_catalog,
)

pytestmark = pytest.mark.unit


def _build(platform: str = "snowflake") -> Dict[str, Any]:
    return {"engine": "dbt", "execution": {"runtime": {"platform": platform}}}


def _contract(
    *,
    fmt: str = "iceberg",
    catalog: Optional[str] = None,
    database: str = "ANALYTICS",
    contract_id: str = "gold.orders",
    platform: str = "snowflake",
    **extra_location: Any,
) -> Dict[str, Any]:
    location: Dict[str, Any] = {"database": database, "table": "ORDERS", **extra_location}
    if catalog:
        location["catalog"] = catalog
    return {
        "fluidVersion": "0.7.6",
        "kind": "DataProduct",
        "id": contract_id,
        "name": "orders",
        "metadata": {"layer": "Gold"},
        "exposes": [
            {
                "exposeId": "orders",
                "kind": "table",
                "binding": {
                    "platform": platform,
                    "format": fmt,
                    "location": location,
                },
                "contract": {"schema": [{"name": "id", "type": "string"}]},
            }
        ],
    }


def _parse(content: str) -> Dict[str, Any]:
    assert content.startswith("# Generated by fluid generate")
    return yaml.safe_load(content)


def _integration(content: str) -> Dict[str, Any]:
    doc = _parse(content)
    return doc["catalogs"][0]["write_integrations"][0]


class TestShippedV1Schema:
    """Pin dbt's released schema, not the proposed v2 in Discussion #12723."""

    def test_uses_write_integrations_not_the_proposed_v2_shape(self):
        doc = _parse(generate_catalogs_yml(_contract(), _build()))
        catalog = doc["catalogs"][0]
        assert "write_integrations" in catalog
        assert catalog["active_write_integration"] == catalog["write_integrations"][0]["name"]
        # v2 drops write_integrations and nests under warehouse keys. Emitting
        # it today produces a file no released dbt can parse.
        assert "config" not in catalog

    def test_table_format_is_always_iceberg(self):
        assert (
            _integration(generate_catalogs_yml(_contract(), _build()))["table_format"] == "iceberg"
        )

    def test_catalog_and_integration_names_are_deterministic(self):
        first = generate_catalogs_yml(_contract(), _build())
        second = generate_catalogs_yml(_contract(), _build())
        assert first == second


class TestSnowflakeManagedCatalog:
    """No explicit catalog means Snowflake Horizon, which dbt calls built_in."""

    def test_catalog_type_is_built_in(self):
        assert (
            _integration(generate_catalogs_yml(_contract(), _build()))["catalog_type"] == "built_in"
        )

    def test_carries_an_external_volume(self):
        integration = _integration(generate_catalogs_yml(_contract(), _build()))
        assert integration["external_volume"]

    def test_external_volume_matches_the_shared_helper(self):
        """The naming contract with the Snowflake IaC emitter.

        Both call ``iceberg_external_volume_name``, so the volume FLUID creates
        is exactly the volume this file references. If these ever diverge, dbt
        writes to a volume that does not exist.
        """
        contract = _contract()
        binding = contract["exposes"][0]["binding"]
        integration = _integration(generate_catalogs_yml(contract, _build()))
        assert integration["external_volume"] == iceberg_external_volume_name(contract, binding)

    def test_built_in_does_not_emit_catalog_linked_database(self):
        integration = _integration(generate_catalogs_yml(_contract(), _build()))
        assert "catalog_linked_database" not in integration.get("adapter_properties", {})


class TestExternalRestCatalog:
    @pytest.mark.parametrize("catalog", ["glue", "polaris", "unity", "rest"])
    def test_external_catalogs_map_to_iceberg_rest(self, catalog):
        integration = _integration(generate_catalogs_yml(_contract(catalog=catalog), _build()))
        assert integration["catalog_type"] == "iceberg_rest"

    def test_rest_catalog_has_no_external_volume(self):
        """external_volume is a built_in concern; dbt rejects it elsewhere."""
        integration = _integration(generate_catalogs_yml(_contract(catalog="polaris"), _build()))
        assert "external_volume" not in integration

    def test_glue_declares_its_linked_database_type(self):
        integration = _integration(generate_catalogs_yml(_contract(catalog="glue"), _build()))
        props = integration["adapter_properties"]
        assert props["catalog_linked_database_type"] == "glue"
        assert props["catalog_linked_database"] == "ANALYTICS"

    def test_non_glue_rest_omits_the_glue_only_property(self):
        integration = _integration(generate_catalogs_yml(_contract(catalog="polaris"), _build()))
        assert "catalog_linked_database_type" not in integration.get("adapter_properties", {})


class TestSnowflakeCatalogKinds:
    """Snowflake's catalog type is the kind table's ``snowflake_catalog_type``.

    Before the table, this emitter kept its own lower-cased set, so
    ``catalog: lakekeeper`` (and any non-canonical spelling) fell through to
    ``built_in``: dbt wrote a Snowflake-managed table while the streaming sink
    committed the same name to Lakekeeper over REST.
    """

    @pytest.mark.parametrize(
        "catalog", ["lakekeeper", "Lakekeeper", "iceberg-rest", "ICEBERG_REST"]
    )
    def test_rest_family_spellings_map_to_iceberg_rest(self, catalog):
        integration = _integration(generate_catalogs_yml(_contract(catalog=catalog), _build()))
        assert integration["catalog_type"] == "iceberg_rest"
        assert "external_volume" not in integration
        props = integration["adapter_properties"]
        assert props["catalog_linked_database"] == "ANALYTICS"
        assert "catalog_linked_database_type" not in props

    def test_lakekeeper_agrees_with_the_streaming_sink(self):
        """The originating bug, end to end: both writers must mean a REST catalog."""
        contract = _contract(catalog="lakekeeper")
        binding = contract["exposes"][0]["binding"]
        assert resolve_iceberg_catalog(binding, contract=contract).catalog_type == "rest"
        integration = _integration(generate_catalogs_yml(contract, _build()))
        assert integration["catalog_type"] == "iceberg_rest"

    @pytest.mark.parametrize(
        "catalog", ["snowflake", "Snowflake", "snowflake_managed", "snowflake-managed"]
    )
    def test_snowflake_spellings_are_built_in(self, catalog):
        contract = _contract(catalog=catalog)
        integration = _integration(generate_catalogs_yml(contract, _build()))
        assert integration["catalog_type"] == "built_in"
        assert integration["external_volume"] == iceberg_external_volume_name(
            contract, contract["exposes"][0]["binding"]
        )

    def test_unknown_kind_keeps_the_built_in_fallback(self):
        """Historic fallback, kept so a typo does not silently flip the table
        to a catalog-linked database; ``fluid validate`` reports the value."""
        integration = _integration(
            generate_catalogs_yml(_contract(catalog="not-a-catalog"), _build())
        )
        assert integration["catalog_type"] == "built_in"
        assert integration["external_volume"]

    @pytest.mark.parametrize("catalog", ["hive", "HIVE", "jdbc", "hadoop", "dynamodb"])
    def test_catalog_snowflake_cannot_reach_writes_no_file(self, catalog):
        """No Snowflake catalog integration exists for these. ``built_in``
        would have dbt create a second, Snowflake-managed table under the name
        the Hive metastore (or JDBC / Hadoop / DynamoDB catalog) owns."""
        assert generate_catalogs_yml(_contract(catalog=catalog), _build()) is None

    def test_unreachable_expose_is_omitted_beside_a_reachable_one(self):
        contract = _contract(catalog="hive")
        managed = {**contract["exposes"][0], "exposeId": "managed"}
        managed["binding"] = {**managed["binding"], "location": {"database": "A", "table": "B"}}
        contract["exposes"].append(managed)
        doc = _parse(generate_catalogs_yml(contract, _build()))
        assert [c["name"] for c in doc["catalogs"]] == ["managed_catalog"]
        assert doc["catalogs"][0]["write_integrations"][0]["catalog_type"] == "built_in"

    def test_omission_is_logged_with_the_way_out(self, caplog):
        with caplog.at_level(logging.WARNING, logger="fluid_build.engines.dbt.catalogs_yml"):
            generate_catalogs_yml(_contract(catalog="hive"), _build())
        message = caplog.text
        assert "'orders'" in message and "'hive'" in message
        assert "lakekeeper" in message and "omit location.catalog" in message

    @pytest.mark.parametrize(
        "platform, catalog",
        [
            ("aws", None),
            ("aws", "glue"),
            ("aws", "lakekeeper"),
            ("snowflake", None),
            ("snowflake", "GLUE"),
            ("snowflake", "polaris"),
        ],
    )
    def test_glue_link_type_tracks_the_aws_iac(self, platform, catalog):
        """The AWS IaC creates a Glue table exactly when ``is_glue_cataloged``.

        dbt on Snowflake must reach that same table through a Glue
        catalog-linked database. An absent catalog on ``platform: aws`` used
        to emit ``built_in`` with a volume that nothing creates (the Snowflake
        IaC only serves ``platform: snowflake`` exposes).
        """
        contract = _contract(catalog=catalog, platform=platform)
        binding = contract["exposes"][0]["binding"]
        integration = _integration(generate_catalogs_yml(contract, _build()))
        props = integration.get("adapter_properties", {})
        is_glue_link = props.get("catalog_linked_database_type") == "glue"
        assert is_glue_link == is_glue_cataloged(binding)
        if is_glue_link:
            assert integration["catalog_type"] == "iceberg_rest"


class TestBigQueryCatalogKinds:
    """``biglake_metastore`` is dbt-bigquery's only catalog type.

    It cannot redirect a model to an external Iceberg catalog, so emitting it
    for ``catalog: lakekeeper`` had dbt create a BigLake table under the name
    the streaming sink commits to in Lakekeeper.
    """

    @staticmethod
    def _contract(catalog: Optional[str] = None) -> Dict[str, Any]:
        return _contract(catalog=catalog, platform="gcp", bucket="lake", path="p")

    @pytest.mark.parametrize(
        "catalog", ["lakekeeper", "Lakekeeper", "rest", "iceberg_rest", "glue", "not-a-catalog"]
    )
    def test_non_biglake_catalog_writes_no_file(self, catalog):
        assert generate_catalogs_yml(self._contract(catalog), _build("gcp")) is None

    @pytest.mark.parametrize("catalog", ["bigquery", "BigQuery", "BIGQUERY"])
    def test_biglake_spellings_are_byte_identical_to_absent(self, catalog):
        absent = generate_catalogs_yml(self._contract(), _build("gcp"))
        assert generate_catalogs_yml(self._contract(catalog), _build("gcp")) == absent
        assert "catalog_type: biglake_metastore" in absent

    def test_lakekeeper_expose_is_omitted_beside_a_biglake_one(self):
        contract = self._contract("lakekeeper")
        biglake = {**contract["exposes"][0], "exposeId": "biglake"}
        biglake["binding"] = {
            **biglake["binding"],
            "location": {"dataset": "d", "table": "T", "bucket": "lake"},
        }
        contract["exposes"].append(biglake)
        doc = _parse(generate_catalogs_yml(contract, _build("gcp")))
        assert [c["name"] for c in doc["catalogs"]] == ["biglake_catalog"]

    def test_omission_is_logged_with_the_way_out(self, caplog):
        with caplog.at_level(logging.WARNING, logger="fluid_build.engines.dbt.catalogs_yml"):
            generate_catalogs_yml(self._contract("lakekeeper"), _build("gcp"))
        assert "dbt-bigquery" in caplog.text and "'lakekeeper'" in caplog.text


class TestByteIdenticalShapes:
    """Golden pins for the shapes the catalog-kind table must not move."""

    _PREFIX = (
        "# Generated by fluid generate. Do not edit manually.\n"
        "# Regenerate with: fluid generate\n\n"
        "catalogs:\n"
        "- name: orders_catalog\n"
        "  active_write_integration: orders_write_integration\n"
        "  write_integrations:\n"
        "  - name: orders_write_integration\n"
    )

    def test_snowflake_absent_catalog(self):
        assert generate_catalogs_yml(_contract(), _build()) == self._PREFIX + (
            "    table_format: iceberg\n"
            "    catalog_type: built_in\n"
            "    external_volume: FLUID_GOLD_ORDERS_VOL\n"
        )

    def test_snowflake_glue_catalog(self):
        assert generate_catalogs_yml(_contract(catalog="glue"), _build()) == self._PREFIX + (
            "    table_format: iceberg\n"
            "    catalog_type: iceberg_rest\n"
            "    adapter_properties:\n"
            "      catalog_linked_database: ANALYTICS\n"
            "      catalog_linked_database_type: glue\n"
        )

    def test_bigquery_absent_catalog(self):
        contract = _contract(platform="gcp", bucket="lake", path="p")
        assert generate_catalogs_yml(contract, _build("gcp")) == self._PREFIX + (
            "    external_volume: gs://lake/p\n"
            "    table_format: iceberg\n"
            "    file_format: parquet\n"
            "    catalog_type: biglake_metastore\n"
        )


class TestEmitsNothingWhenItShould:
    def test_no_iceberg_expose_writes_no_file(self):
        assert generate_catalogs_yml(_contract(fmt="snowflake_table"), _build()) is None

    def test_contract_with_no_exposes_writes_no_file(self):
        assert generate_catalogs_yml({"id": "x", "exposes": []}, _build()) is None

    @pytest.mark.parametrize("platform", ["gcp", "aws", "local"])
    def test_unverified_adapters_write_no_file(self, platform):
        """Guessing an unverified shape is worse than emitting nothing.

        dbt supports Iceberg on Databricks and BigQuery too, but their
        catalogs.yml shapes are not verified here.
        """
        assert generate_catalogs_yml(_contract(), _build(platform)) is None

    def test_expose_without_an_id_is_skipped(self):
        contract = _contract()
        del contract["exposes"][0]["exposeId"]
        assert generate_catalogs_yml(contract, _build()) is None


class TestNameCollisions:
    def test_separator_folded_ids_do_not_produce_duplicate_catalogs(self):
        """``a.b`` and ``a_b`` fold to the same base; dbt would reject a file
        defining the same catalog twice, so the second gets a digest suffix."""
        contract = _contract()
        second = dict(contract["exposes"][0])
        second = {**second, "exposeId": "or.ders"}
        contract["exposes"][0]["exposeId"] = "or_ders"
        contract["exposes"].append(second)
        doc = _parse(generate_catalogs_yml(contract, _build()))
        names = [c["name"] for c in doc["catalogs"]]
        assert len(names) == 2
        assert len(set(names)) == 2


class TestEngineWiring:
    def test_generate_includes_catalogs_yml_for_an_iceberg_contract(self):
        from fluid_build.engines.dbt import DbtEngine

        files = DbtEngine().generate(_contract(), _build())
        assert "catalogs.yml" in files
        assert "catalog_type: built_in" in files["catalogs.yml"]

    def test_generate_omits_catalogs_yml_without_iceberg(self):
        from fluid_build.engines.dbt import DbtEngine

        files = DbtEngine().generate(_contract(fmt="snowflake_table"), _build())
        assert "catalogs.yml" not in files
