# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""dbt ``catalogs.yml`` emission for Iceberg exposes.

dbt creates the Iceberg table entry but not the external volume or catalog
integration behind it, which its own docs put on the user. These tests pin the
emitted shape against dbt's *shipped* v1 schema, the naming contract this
emitter shares with the Snowflake IaC emitter, and the cases where nothing
should be written at all.
"""

from __future__ import annotations

from typing import Any, Dict, Optional

import pytest
import yaml

from fluid_build.engines.dbt.catalogs_yml import generate_catalogs_yml
from fluid_build.providers._iceberg_catalog import iceberg_external_volume_name

pytestmark = pytest.mark.unit


def _build(platform: str = "snowflake") -> Dict[str, Any]:
    return {"engine": "dbt", "execution": {"runtime": {"platform": platform}}}


def _contract(
    *,
    fmt: str = "iceberg",
    catalog: Optional[str] = None,
    database: str = "ANALYTICS",
    contract_id: str = "gold.orders",
) -> Dict[str, Any]:
    location: Dict[str, Any] = {"database": database, "table": "ORDERS"}
    if catalog:
        location["catalog"] = catalog
    return {
        "fluidVersion": "0.7.6",
        "kind": "DataProduct",
        "id": contract_id,
        "name": "orders",
        "metadata": {"layer": "Gold"},
        "exposes": [
            {
                "exposeId": "orders",
                "kind": "table",
                "binding": {
                    "platform": "snowflake",
                    "format": fmt,
                    "location": location,
                },
                "contract": {"schema": [{"name": "id", "type": "string"}]},
            }
        ],
    }


def _parse(content: str) -> Dict[str, Any]:
    assert content.startswith("# Generated by fluid generate")
    return yaml.safe_load(content)


def _integration(content: str) -> Dict[str, Any]:
    doc = _parse(content)
    return doc["catalogs"][0]["write_integrations"][0]


class TestShippedV1Schema:
    """Pin dbt's released schema, not the proposed v2 in Discussion #12723."""

    def test_uses_write_integrations_not_the_proposed_v2_shape(self):
        doc = _parse(generate_catalogs_yml(_contract(), _build()))
        catalog = doc["catalogs"][0]
        assert "write_integrations" in catalog
        assert catalog["active_write_integration"] == catalog["write_integrations"][0]["name"]
        # v2 drops write_integrations and nests under warehouse keys. Emitting
        # it today produces a file no released dbt can parse.
        assert "config" not in catalog

    def test_table_format_is_always_iceberg(self):
        assert (
            _integration(generate_catalogs_yml(_contract(), _build()))["table_format"] == "iceberg"
        )

    def test_catalog_and_integration_names_are_deterministic(self):
        first = generate_catalogs_yml(_contract(), _build())
        second = generate_catalogs_yml(_contract(), _build())
        assert first == second


class TestSnowflakeManagedCatalog:
    """No explicit catalog means Snowflake Horizon, which dbt calls built_in."""

    def test_catalog_type_is_built_in(self):
        assert (
            _integration(generate_catalogs_yml(_contract(), _build()))["catalog_type"] == "built_in"
        )

    def test_carries_an_external_volume(self):
        integration = _integration(generate_catalogs_yml(_contract(), _build()))
        assert integration["external_volume"]

    def test_external_volume_matches_the_shared_helper(self):
        """The naming contract with the Snowflake IaC emitter.

        Both call ``iceberg_external_volume_name``, so the volume FLUID creates
        is exactly the volume this file references. If these ever diverge, dbt
        writes to a volume that does not exist.
        """
        contract = _contract()
        binding = contract["exposes"][0]["binding"]
        integration = _integration(generate_catalogs_yml(contract, _build()))
        assert integration["external_volume"] == iceberg_external_volume_name(contract, binding)

    def test_built_in_does_not_emit_catalog_linked_database(self):
        integration = _integration(generate_catalogs_yml(_contract(), _build()))
        assert "catalog_linked_database" not in integration.get("adapter_properties", {})


class TestExternalRestCatalog:
    @pytest.mark.parametrize("catalog", ["glue", "polaris", "unity", "rest"])
    def test_external_catalogs_map_to_iceberg_rest(self, catalog):
        integration = _integration(generate_catalogs_yml(_contract(catalog=catalog), _build()))
        assert integration["catalog_type"] == "iceberg_rest"

    def test_rest_catalog_has_no_external_volume(self):
        """external_volume is a built_in concern; dbt rejects it elsewhere."""
        integration = _integration(generate_catalogs_yml(_contract(catalog="polaris"), _build()))
        assert "external_volume" not in integration

    def test_glue_declares_its_linked_database_type(self):
        integration = _integration(generate_catalogs_yml(_contract(catalog="glue"), _build()))
        props = integration["adapter_properties"]
        assert props["catalog_linked_database_type"] == "glue"
        assert props["catalog_linked_database"] == "ANALYTICS"

    def test_non_glue_rest_omits_the_glue_only_property(self):
        integration = _integration(generate_catalogs_yml(_contract(catalog="polaris"), _build()))
        assert "catalog_linked_database_type" not in integration.get("adapter_properties", {})


class TestEmitsNothingWhenItShould:
    def test_no_iceberg_expose_writes_no_file(self):
        assert generate_catalogs_yml(_contract(fmt="snowflake_table"), _build()) is None

    def test_contract_with_no_exposes_writes_no_file(self):
        assert generate_catalogs_yml({"id": "x", "exposes": []}, _build()) is None

    @pytest.mark.parametrize("platform", ["gcp", "aws", "local"])
    def test_unverified_adapters_write_no_file(self, platform):
        """Guessing an unverified shape is worse than emitting nothing.

        dbt supports Iceberg on Databricks and BigQuery too, but their
        catalogs.yml shapes are not verified here.
        """
        assert generate_catalogs_yml(_contract(), _build(platform)) is None

    def test_expose_without_an_id_is_skipped(self):
        contract = _contract()
        del contract["exposes"][0]["exposeId"]
        assert generate_catalogs_yml(contract, _build()) is None


class TestNameCollisions:
    def test_separator_folded_ids_do_not_produce_duplicate_catalogs(self):
        """``a.b`` and ``a_b`` fold to the same base; dbt would reject a file
        defining the same catalog twice, so the second gets a digest suffix."""
        contract = _contract()
        second = dict(contract["exposes"][0])
        second = {**second, "exposeId": "or.ders"}
        contract["exposes"][0]["exposeId"] = "or_ders"
        contract["exposes"].append(second)
        doc = _parse(generate_catalogs_yml(contract, _build()))
        names = [c["name"] for c in doc["catalogs"]]
        assert len(names) == 2
        assert len(set(names)) == 2


class TestEngineWiring:
    def test_generate_includes_catalogs_yml_for_an_iceberg_contract(self):
        from fluid_build.engines.dbt import DbtEngine

        files = DbtEngine().generate(_contract(), _build())
        assert "catalogs.yml" in files
        assert "catalog_type: built_in" in files["catalogs.yml"]

    def test_generate_omits_catalogs_yml_without_iceberg(self):
        from fluid_build.engines.dbt import DbtEngine

        files = DbtEngine().generate(_contract(fmt="snowflake_table"), _build())
        assert "catalogs.yml" not in files
