# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""DV2 table-name conventions — ``hub_*/lnk_*/sat_*/pit_*/br_*``.

Small pure helpers so that table names are generated by one function
rather than hand-formatted at multiple sites.  The helpers accept
already-prefixed names idempotently: ``hub_name("hub_party")`` returns
``"hub_party"`` unchanged.
"""

from __future__ import annotations

import re
from typing import Iterable, Optional

_SAFE_CHARS = re.compile(r"[^a-z0-9_]+")


def _slug(raw: str) -> str:
    """Lower-case, collapse non-alphanumeric runs into single underscores."""
    return _SAFE_CHARS.sub("_", raw.lower()).strip("_")


def _with_prefix(prefix: str, raw: str) -> str:
    name = _slug(raw)
    if name.startswith(f"{prefix}_"):
        return name
    return f"{prefix}_{name}" if name else prefix


def hub_name(entity: str) -> str:
    """Return ``hub_<entity>`` (idempotent if already prefixed)."""
    return _with_prefix("hub", entity)


def link_name(*entities: str) -> str:
    """Return ``lnk_<e1>_<e2>_...`` from two or more entity names.

    Order is preserved — DV2 links encode directionality via declared
    hub order.
    """
    parts = [_slug(e) for e in entities if e]
    joined = "_".join(parts)
    return _with_prefix("lnk", joined)


def satellite_name(parent: str, descriptor: Optional[str] = None) -> str:
    """Return ``sat_<parent>[_<descriptor>]``.

    ``parent`` may already be a hub name (``hub_party``) — the ``hub_``
    prefix is stripped before re-labelling as ``sat_party`` so users get
    a clean satellite name either way.
    """
    base = _slug(parent)
    if base.startswith("hub_"):
        base = base[4:]
    if descriptor:
        base = f"{base}_{_slug(descriptor)}"
    return _with_prefix("sat", base)


def pit_name(parent: str) -> str:
    """Return ``pit_<parent>``; strips a leading ``hub_`` prefix."""
    base = _slug(parent)
    if base.startswith("hub_"):
        base = base[4:]
    return _with_prefix("pit", base)


def bridge_name(descriptor: str) -> str:
    """Return ``br_<descriptor>``."""
    return _with_prefix("br", descriptor)


def iter_standard_prefixes() -> Iterable[str]:
    """The five prefixes this module emits — for validators/linters."""
    return ("hub", "lnk", "sat", "pit", "br")
