# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate SQL script files from FLUID contract builds."""

from __future__ import annotations

import logging
import re
from typing import Any, Dict, List, Optional, Sequence, Tuple

from fluid_build.providers._sql_safety import validate_ident

from .._stages import resolve_stage_outputs
from ..base import GenerationResult, TransformationIntent

_logger = logging.getLogger(__name__)

_HEADER = (
    "-- Generated by fluid generate — do not edit manually.\n-- Regenerate with: fluid generate\n"
)

#: One materialised stage. ``{ref}`` is a validated (optionally
#: schema-qualified) identifier; ``{sql}`` is the stage's own statement with
#: any trailing ';' stripped. The ';' sits on its own line so a runner that
#: segments on semicolons still sees one statement.
#:
#: CREATE OR REPLACE VIEW is the portable choice: both platforms forge-cli
#: can actually execute support it (DuckDB via the local provider, and
#: Snowflake), as do BigQuery, Redshift, Athena, Trino, PostgreSQL and
#: Databricks for emit-only targets. ``providers/local/local.py`` already
#: emits this exact form for its own CSV register step.
#:
#: It is NOT non-destructive: OR REPLACE drops grants on Snowflake and
#: Databricks and makes any Snowflake stream over the view stale. Do not
#: describe it as safe anywhere.
STAGE_VIEW_DDL = "CREATE OR REPLACE VIEW {ref} AS\n{sql}\n;"

#: Statements that declare their own sink. Such SQL must not be wrapped in a
#: view -- it already says where its output goes.
_SINK_KEYWORDS = frozenset(
    {
        "insert",
        "create",
        "merge",
        "update",
        "delete",
        "copy",
        "truncate",
        "alter",
        "drop",
        "call",
        "grant",
        "revoke",
    }
)


def _first_keyword(sql: str) -> str:
    r"""The first word of ``sql``, skipping leading whitespace and comments.

    Deliberately a scanner rather than a regex. The obvious pattern --
    ``\A(?:\s|--[^\n]*\n|/\*.*?\*/)*(?:insert|create|...)\b`` -- is
    exponential, because ``/\*.*?\*/`` under DOTALL is ambiguous inside a
    starred alternation: ``/**//**/`` parses either as two comments or as one
    whose body is ``*//*``, so a non-matching input explores every partition.
    Measured on that pattern: 81 bytes took 135ms, 97 bytes 2.2s, 105 bytes
    8.7s, and 113 bytes never returned. This SQL comes from a contract, and
    contracts travel -- CodeQL flagged it as `py/redos`, correctly.

    This visits each character at most once, so it is linear by construction.
    """
    index, length = 0, len(sql)
    while index < length:
        char = sql[index]
        if char.isspace():
            index += 1
        elif sql.startswith("--", index):
            newline = sql.find("\n", index)
            index = length if newline == -1 else newline + 1
        elif sql.startswith("/*", index):
            close = sql.find("*/", index + 2)
            index = length if close == -1 else close + 2
        else:
            break
    end = index
    while end < length and (sql[end].isalpha() or sql[end] == "_"):
        end += 1
    return sql[index:end].lower()


def _already_a_sink(sql: str) -> bool:
    """True when ``sql`` already writes to a target of its own."""
    return _first_keyword(sql) in _SINK_KEYWORDS


#: Anything interpolated into a ``--`` comment line. A newline in a contract
#: value closes the comment and puts the rest of the value at statement
#: level -- and these files are meant to be RUN. Verified: a stage named
#: ``s\nDROP TABLE victim; --`` dropped the table.
_COMMENT_BREAKERS = re.compile(r"[\r\n\u2028\u2029]+")


def _comment_safe(value: Any) -> str:
    """Flatten a value so it cannot escape the ``--`` comment it sits in."""
    return _COMMENT_BREAKERS.sub(" ", str(value))


def _view_ref(output: str) -> str:
    """Validate an ``outputs`` name for use as a view identifier.

    Split on '.' so a schema-qualified name works, and validate each segment
    through the repo's central helper. The schema types these names loosely
    enough to admit dots, hyphens and a leading digit, so a name can be
    contract-legal and still not be a usable identifier -- and a hyphenated
    one would comment out the rest of the DDL line.
    """
    parts = str(output).split(".")
    if not parts or any(not part for part in parts):
        raise ValueError(f"output name {output!r} is empty or has an empty segment")
    try:
        return ".".join(validate_ident(part) for part in parts)
    except ValueError:
        raise ValueError(
            f"output name {output!r} is not a usable SQL identifier (letters, "
            "digits and underscores only, not starting with a digit)"
        ) from None


def _materialise(sql: str, output_name: Optional[str]) -> Tuple[str, Optional[str]]:
    """Return ``(body, reason_not_materialised)``; reason is None on success."""
    body = sql.strip().rstrip(";").rstrip()
    if not output_name:
        return body + "\n", "stage declares no output it exclusively owns"
    if _already_a_sink(body):
        return body + ";\n", "SQL already writes to its own target"
    try:
        ref = _view_ref(output_name)
    except ValueError as exc:
        _logger.warning("sql_stage_output_not_materialisable: %s", exc)
        return body + "\n", str(exc)
    return STAGE_VIEW_DDL.format(ref=ref, sql=body) + "\n", None


def _materialisation_header(output_name: Optional[str], reason: Optional[str]) -> str:
    if reason is None:
        return f"-- Materialises: {_comment_safe(output_name)}  (CREATE OR REPLACE VIEW)\n"
    return f"-- Not materialised: {_comment_safe(reason)}\n"


def _warn_if_not_topological(names: Sequence[str], depends: Dict[str, List[str]]) -> None:
    """Warn when declaration order is not a valid execution order.

    Files are numbered by declaration position and a runner executes them in
    filename order. That was cosmetic while every script was an inert SELECT;
    once a stage materialises a view the later script actually needs it to
    exist. Declaration order is a valid topological order in every shipped
    contract, so this warns rather than reordering -- renumbering would
    silently change filenames a user may have scripted against.
    """
    position = {name: i for i, name in enumerate(names)}
    for name in names:
        for dep in depends.get(name, []):
            if dep in position and position[dep] > position[name]:
                _logger.warning(
                    "sql_stage_order_not_topological: stage %r is emitted before %r, "
                    "which it depends on; the generated scripts will not run in "
                    "filename order. Declare stages in dependency order.",
                    name,
                    dep,
                )


def generate_scripts(
    contract: Dict[str, Any],
    build: Dict[str, Any],
    *,
    transformation_intent: Optional[TransformationIntent] = None,
) -> GenerationResult:
    """Generate SQL script files."""
    pattern = build.get("pattern", "embedded-logic")

    if transformation_intent and transformation_intent.stages:
        return _generate_from_intent(contract, transformation_intent)

    if pattern == "multi-stage":
        return _generate_multi_stage(contract, build)
    else:
        return _generate_embedded(contract, build)


def _generate_embedded(
    contract: Dict[str, Any],
    build: Dict[str, Any],
) -> GenerationResult:
    """Generate a single SQL script from embedded-logic."""
    properties = build.get("properties", {})
    sql = properties.get("sql", "")
    build_id = build.get("id", "main")
    contract_id = contract.get("id", "unknown")

    header = (
        f"{_HEADER}-- Contract: {_comment_safe(contract_id)}\n"
        f"-- Build: {_comment_safe(build_id)}\n\n"
    )

    if sql:
        return {f"{build_id}.sql": header + sql.strip() + "\n"}

    return {f"{build_id}.sql": (header + "-- TODO: Add transformation SQL\n" + "SELECT 1;\n")}


def _generate_multi_stage(
    contract: Dict[str, Any],
    build: Dict[str, Any],
) -> GenerationResult:
    """Generate ordered SQL scripts from multi-stage build."""
    files: GenerationResult = {}
    properties = build.get("properties", {})
    stages = properties.get("stages", [])
    contract_id = contract.get("id", "unknown")

    # A stage's SQL refers to its upstreams by their OUTPUT names -- every
    # cross-stage reference in every shipped quickstart does -- so each stage
    # is materialised as a view under the output it owns. Without that the
    # emitted scripts cannot run: nothing creates a relation by any name.
    outputs = resolve_stage_outputs(stages, log_event="sql_stage_output_name_collision")
    _warn_if_not_topological(
        [str(s.get("name")) for s in stages if isinstance(s, dict) and s.get("name")],
        {
            str(s.get("name")): list(s.get("dependsOn") or [])
            for s in stages
            if isinstance(s, dict) and s.get("name")
        },
    )

    for idx, stage in enumerate(stages):
        if not isinstance(stage, dict):
            continue

        name = stage.get("name", f"stage_{idx}")
        sql = stage.get("properties", {}).get("sql", "")
        depends_on = stage.get("dependsOn", [])

        header = (
            f"{_HEADER}-- Contract: {_comment_safe(contract_id)}\n"
            f"-- Stage: {_comment_safe(name)} ({idx + 1}/{len(stages)})\n"
        )
        if depends_on:
            header += f"-- Depends on: {_comment_safe(', '.join(str(d) for d in depends_on))}\n"

        if sql:
            # A stage with no SQL is unfinished; materialising its `SELECT 1`
            # placeholder would let downstream stages run against a dummy
            # relation and look like they worked.
            body, reason = _materialise(sql, outputs.get(str(name)))
            header += _materialisation_header(outputs.get(str(name)), reason) + "\n"
            content = header + body
        else:
            header += "\n"
            content = (
                header
                + f"-- TODO: Add transformation SQL for stage '{_comment_safe(name)}'\n"
                + "SELECT 1;\n"
            )

        # Prefix with index for execution order
        files[f"{idx + 1:02d}_{name}.sql"] = content

    return files


def _generate_from_intent(
    contract: Dict[str, Any],
    intent: TransformationIntent,
) -> GenerationResult:
    """Generate SQL scripts from AI-produced TransformationIntent."""
    files: GenerationResult = {}
    contract_id = contract.get("id", "unknown")

    # Intent stages carry `outputs` too (generate_speed_transformation builds
    # them from the spec), and use snake_case `depends_on` where the contract
    # path uses `dependsOn`.
    outputs = resolve_stage_outputs(intent.stages, log_event="sql_stage_output_name_collision")

    for idx, stage in enumerate(intent.stages):
        # The contract path has always skipped a malformed entry; this one
        # raised AttributeError on it.
        if not isinstance(stage, dict):
            continue

        name = stage.get("name", f"stage_{idx}")
        sql = stage.get("sql", "")
        depends_on = stage.get("depends_on", [])

        header = (
            f"{_HEADER}-- Contract: {_comment_safe(contract_id)}\n"
            f"-- Stage: {_comment_safe(name)}\n"
        )
        if depends_on:
            header += f"-- Depends on: {', '.join(depends_on)}\n"

        if sql:
            body, reason = _materialise(sql, outputs.get(str(name)))
            header += _materialisation_header(outputs.get(str(name)), reason) + "\n"
            content = header + body
        else:
            header += "\n"
            content = (
                header
                + f"-- TODO: AI could not generate SQL for stage '{_comment_safe(name)}'\n"
                + "SELECT 1;\n"
            )

        files[f"{idx + 1:02d}_{name}.sql"] = content

    return files
