# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Airflow DAG Generation for GCP Provider.

Generates Python DAG files from FLUID contracts for deployment to Cloud Composer
or self-hosted Airflow on GCP.
"""

from datetime import datetime
from datetime import timezone as dt_timezone
from typing import Any, Dict, List

from fluid_build.providers.common.codegen_utils import (
    convert_schedule_to_airflow,
    generate_file_header,
    generate_task_dependencies_code,
    py_str_literal,
    sanitize_identifier,
)


def generate_airflow_dag(contract: Dict[str, Any], project: str, region: str) -> str:
    """
    Generate Airflow DAG Python code from FLUID contract.

    Args:
        contract: FLUID contract with orchestration section
        project: GCP project ID
        region: GCP region

    Returns:
        Python code for Airflow DAG
    """
    orchestration = contract.get("orchestration", {})
    if not orchestration:
        raise ValueError("Contract missing orchestration section")

    tasks = orchestration.get("tasks", [])
    if not tasks:
        raise ValueError("Orchestration has no tasks")

    # Extract configuration
    contract_id = contract.get("id", "unknown")
    contract_name = contract.get("name", contract_id)
    schedule = orchestration.get("schedule", "0 2 * * *")
    timezone = orchestration.get("timezone", "UTC")

    # Filter provider action tasks
    provider_tasks = [t for t in tasks if t.get("type") == "provider_action"]

    # Generate DAG code
    dag_code = generate_file_header(
        contract_id=contract_id,
        contract_name=contract_name,
        provider="gcp",
        schedule=schedule,
        timezone=timezone,
        gcp_project=project,
        gcp_region=region,
    )
    dag_code += "\n\n"
    dag_code += _generate_dag_imports()
    dag_code += "\n\n"
    dag_code += _generate_dag_definition(contract_id, contract_name, schedule, timezone)
    dag_code += "\n\n"
    dag_code += _generate_task_definitions(provider_tasks, project, region)
    dag_code += "\n\n"
    dag_code += generate_task_dependencies_code(provider_tasks, syntax="airflow")

    return dag_code


def _generate_dag_header(
    contract_id: str, contract_name: str, schedule: str, timezone: str, project: str, region: str
) -> str:
    """Generate DAG file header with metadata."""
    return f'''"""
FLUID Generated DAG: {contract_name}

Contract ID: {contract_id}
Schedule: {schedule}
Timezone: {timezone}
GCP Project: {project}
GCP Region: {region}

Auto-generated by FLUID Forge - DO NOT EDIT MANUALLY
Generated: {datetime.now(dt_timezone.utc).replace(tzinfo=None).isoformat()}Z
"""'''


def _generate_dag_imports() -> str:
    """Generate import statements."""
    return """from datetime import datetime, timedelta
from zoneinfo import ZoneInfo
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.providers.google.cloud.operators.bigquery import (
    BigQueryCreateEmptyDatasetOperator,
    BigQueryCreateEmptyTableOperator,
    BigQueryInsertJobOperator,
)
from airflow.providers.google.cloud.operators.gcs import (
    GCSCreateBucketOperator,
    GCSDeleteBucketOperator,
)
from airflow.providers.google.cloud.operators.pubsub import (
    PubSubCreateTopicOperator,
    PubSubCreateSubscriptionOperator,
)
from airflow.providers.google.cloud.operators.dataflow import (
    DataflowTemplatedJobStartOperator,
)
import json
import logging

logger = logging.getLogger(__name__)"""


def _generate_dag_definition(
    contract_id: str, contract_name: str, schedule: str, timezone: str
) -> str:
    """Generate DAG definition with default arguments."""
    # Convert cron to Airflow schedule
    airflow_schedule = convert_schedule_to_airflow(schedule)

    # All contract-derived values are emitted as repr()-escaped literals so a
    # malicious name/timezone/schedule/id cannot break out and inject code that
    # Airflow would run at DAG-parse time. dag_id is an identifier (no quotes).
    dag_id_lit = py_str_literal(sanitize_identifier(contract_id))
    contract_name_lit = py_str_literal(contract_name)
    airflow_schedule_lit = py_str_literal(airflow_schedule)
    timezone_lit = py_str_literal(timezone)
    tags = ["fluid", "auto-generated", "gcp", contract_id]

    return f"""# Default DAG arguments
default_args = {{
    'owner': 'fluid-forge',
    'depends_on_past': False,
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 3,
    'retry_delay': timedelta(minutes=5),
    'execution_timeout': timedelta(hours=2),
}}

# DAG definition
dag = DAG(
    dag_id={dag_id_lit},
    default_args=default_args,
    description={contract_name_lit},
    schedule_interval={airflow_schedule_lit},
    start_date=datetime(2026, 1, 1, tzinfo=ZoneInfo({timezone_lit})),
    catchup=False,
    tags={tags!r},
)"""


def _generate_task_definitions(tasks: List[Dict[str, Any]], project: str, region: str) -> str:
    """Generate task definitions."""
    task_code = "# Task definitions\n"

    for task in tasks:
        task_code += _generate_single_task(task, project, region)
        task_code += "\n\n"

    return task_code.rstrip()


def _generate_single_task(task: Dict[str, Any], project: str, region: str) -> str:
    """Generate code for a single task."""
    task.get("taskId")
    action = task.get("action", "")
    params = task.get("params", {})

    # Parse action (e.g., "gcp.bigquery.create_dataset")
    action_parts = action.split(".")
    if len(action_parts) < 3:
        # Fallback to PythonOperator
        return _generate_python_task(task, project, region)

    service = action_parts[1]
    operation = action_parts[2]

    # Map to appropriate Airflow operator
    if service == "bigquery":
        return _generate_bigquery_task(task, operation, params, project, region)
    elif service == "gcs" or service == "storage":
        return _generate_gcs_task(task, operation, params, project, region)
    elif service == "pubsub":
        return _generate_pubsub_task(task, operation, params, project, region)
    elif service == "dataflow":
        return _generate_dataflow_task(task, operation, params, project, region)
    else:
        # Fallback to PythonOperator
        return _generate_python_task(task, project, region)


def _generate_bigquery_task(
    task: Dict[str, Any], operation: str, params: Dict[str, Any], project: str, region: str
) -> str:
    """Generate BigQuery task code."""
    task_id = task.get("taskId")
    var = sanitize_identifier(task_id)
    task_id_lit = py_str_literal(task_id)
    project_lit = py_str_literal(project)
    region_lit = py_str_literal(region)

    if operation == "create_dataset":
        dataset_lit = py_str_literal(params.get("dataset_id", "unknown_dataset"))
        location_lit = py_str_literal(params.get("location", region))
        return f"""{var} = BigQueryCreateEmptyDatasetOperator(
    task_id={task_id_lit},
    dataset_id={dataset_lit},
    project_id={project_lit},
    location={location_lit},
    dag=dag,
)"""

    elif operation == "create_table":
        dataset_lit = py_str_literal(params.get("dataset_id", "unknown_dataset"))
        table_lit = py_str_literal(params.get("table_id", "unknown_table"))
        schema_fields = params.get("schema", [])
        return f"""{var} = BigQueryCreateEmptyTableOperator(
    task_id={task_id_lit},
    dataset_id={dataset_lit},
    table_id={table_lit},
    project_id={project_lit},
    schema_fields={schema_fields!r},
    dag=dag,
)"""

    elif operation == "query" or operation == "run_query":
        query_sql = params.get("query", "SELECT 1")
        destination_dataset = params.get("destination_dataset")
        destination_table = params.get("destination_table")

        config = {
            "query": {
                "query": query_sql,
                "useLegacySql": False,
            }
        }

        if destination_dataset and destination_table:
            config["query"]["destinationTable"] = {
                "projectId": project,
                "datasetId": destination_dataset,
                "tableId": destination_table,
            }

        return f"""{var} = BigQueryInsertJobOperator(
    task_id={task_id_lit},
    configuration={config!r},
    project_id={project_lit},
    location={region_lit},
    dag=dag,
)"""

    else:
        return _generate_python_task(task, project, region)


def _generate_gcs_task(
    task: Dict[str, Any], operation: str, params: Dict[str, Any], project: str, region: str
) -> str:
    """Generate Cloud Storage task code."""
    task_id = task.get("taskId")
    var = sanitize_identifier(task_id)
    task_id_lit = py_str_literal(task_id)
    project_lit = py_str_literal(project)

    if operation == "create_bucket" or operation == "ensure_bucket":
        bucket_lit = py_str_literal(params.get("bucket", "unknown-bucket"))
        location_lit = py_str_literal(params.get("location", region))
        storage_lit = py_str_literal(params.get("storage_class", "STANDARD"))

        return f"""{var} = GCSCreateBucketOperator(
    task_id={task_id_lit},
    bucket_name={bucket_lit},
    project_id={project_lit},
    storage_class={storage_lit},
    location={location_lit},
    dag=dag,
)"""

    else:
        return _generate_python_task(task, project, region)


def _generate_pubsub_task(
    task: Dict[str, Any], operation: str, params: Dict[str, Any], project: str, region: str
) -> str:
    """Generate Pub/Sub task code."""
    task_id = task.get("taskId")
    var = sanitize_identifier(task_id)
    task_id_lit = py_str_literal(task_id)
    project_lit = py_str_literal(project)

    if operation == "create_topic":
        topic_lit = py_str_literal(params.get("topic", "unknown-topic"))
        return f"""{var} = PubSubCreateTopicOperator(
    task_id={task_id_lit},
    topic={topic_lit},
    project_id={project_lit},
    dag=dag,
)"""

    elif operation == "create_subscription":
        topic_lit = py_str_literal(params.get("topic", "unknown-topic"))
        subscription_lit = py_str_literal(params.get("subscription", "unknown-sub"))
        return f"""{var} = PubSubCreateSubscriptionOperator(
    task_id={task_id_lit},
    topic={topic_lit},
    subscription={subscription_lit},
    project_id={project_lit},
    dag=dag,
)"""

    else:
        return _generate_python_task(task, project, region)


def _generate_dataflow_task(
    task: Dict[str, Any], operation: str, params: Dict[str, Any], project: str, region: str
) -> str:
    """Generate Dataflow task code."""
    task_id = task.get("taskId")
    var = sanitize_identifier(task_id)
    task_id_lit = py_str_literal(task_id)
    project_lit = py_str_literal(project)
    region_lit = py_str_literal(region)

    if operation == "run_template":
        template_lit = py_str_literal(params.get("template", ""))
        job_name_lit = py_str_literal(params.get("job_name", task_id))
        parameters = params.get("parameters", {})

        return f"""{var} = DataflowTemplatedJobStartOperator(
    task_id={task_id_lit},
    job_name={job_name_lit},
    template={template_lit},
    parameters={parameters!r},
    project_id={project_lit},
    location={region_lit},
    dag=dag,
)"""

    else:
        return _generate_python_task(task, project, region)


def _generate_python_task(task: Dict[str, Any], project: str, region: str) -> str:
    """Generate generic Python task.

    The action + params are emitted via ``repr``/``json.dumps`` and
    concatenated (never f-string-interpolated inside a quoted literal) so a
    contract value containing quotes/newlines cannot break out of the lambda
    body — mirrors ``schedulers/airflow``'s ``_generate_generic_task``.
    """
    import json

    task_id = task.get("taskId")
    action = task.get("action")
    params = task.get("params", {})

    var = sanitize_identifier(task_id)
    task_id_lit = py_str_literal(task_id)
    action_lit = py_str_literal(action)
    # json.dumps -> double-quoted JSON; repr() wraps it as a safe single-line
    # literal embedded via string concatenation.
    params_json = repr(json.dumps(params, sort_keys=True, default=str))

    return f"""{var} = PythonOperator(
    task_id={task_id_lit},
    python_callable=lambda: logger.info(
        'Action: ' + {action_lit} + ', Params: ' + {params_json}
    ),
    dag=dag,
)"""
