# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Dagster Pipeline Generation for GCP Provider.

Generates Python pipeline code from FLUID contracts for Dagster on GCP.

Supports:
- BigQuery ops with type safety
- Cloud Storage resources
- Pub/Sub integration
- Dataflow pipelines
"""

from datetime import datetime
from datetime import timezone as dt_timezone
from typing import Any, Dict, List

from fluid_build.providers.common.codegen_utils import (
    escape_for_docstring,
    json_literal,
    py_str_literal,
    sanitize_identifier,
    task_identifier,
)


def generate_dagster_pipeline(contract: Dict[str, Any], project: str, region: str) -> str:
    """
    Generate Dagster pipeline Python code from FLUID contract.

    Args:
        contract: FLUID contract with orchestration section
        project: GCP project ID
        region: GCP region

    Returns:
        Python code for Dagster pipeline
    """
    orchestration = contract.get("orchestration", {})
    if not orchestration:
        raise ValueError("Contract missing orchestration section")

    tasks = orchestration.get("tasks", [])
    if not tasks:
        raise ValueError("Orchestration has no tasks")

    # Extract configuration
    contract_id = contract.get("id", "unknown")
    contract_name = contract.get("name", contract_id)
    schedule = orchestration.get("schedule", "0 2 * * *")
    timezone = orchestration.get("timezone", "UTC")

    # Filter provider action tasks
    provider_tasks = [t for t in tasks if t.get("type") == "provider_action"]

    # Generate pipeline code
    code = _generate_header(contract_id, contract_name, schedule, timezone, project, region)
    code += "\n\n"
    code += _generate_imports()
    code += "\n\n"
    code += _generate_resources(project, region)
    code += "\n\n"
    code += _generate_ops(provider_tasks, project, region)
    code += "\n\n"
    code += _generate_job(contract_id, provider_tasks, schedule, timezone)

    return code


def _generate_header(
    contract_id: str, contract_name: str, schedule: str, timezone: str, project: str, region: str
) -> str:
    """Generate file header with metadata."""
    # Every field is escaped: an unescaped ``"""`` in a contract value closes
    # this header docstring and leaves whatever follows as a top-level
    # statement, which Dagster runs the moment it imports the pipeline file.
    return f'''"""
FLUID Generated Dagster Pipeline: {escape_for_docstring(contract_name)}

Contract ID: {escape_for_docstring(contract_id)}
Schedule: {escape_for_docstring(schedule)}
Timezone: {escape_for_docstring(timezone)}
GCP Project: {escape_for_docstring(project)}
GCP Region: {escape_for_docstring(region)}

Auto-generated by FLUID Forge - DO NOT EDIT MANUALLY
Generated: {datetime.now(dt_timezone.utc).replace(tzinfo=None).isoformat()}Z
"""'''


def _generate_imports() -> str:
    """Generate import statements."""
    return """from dagster import (
    op,
    job,
    resource,
    In,
    Out,
    Nothing,
    DagsterEventType,
    ScheduleDefinition,
)
from google.cloud import bigquery, storage, pubsub_v1, dataflow_v1beta3
import json
import logging

logger = logging.getLogger(__name__)"""


def _generate_resources(project: str, region: str) -> str:
    """Generate GCP resource definitions."""
    return f'''# GCP Resources
@resource
def gcp_project():
    """GCP project ID resource."""
    return {py_str_literal(project)}

@resource
def gcp_region():
    """GCP region resource."""
    return {py_str_literal(region)}

@resource
def bigquery_client(context):
    """BigQuery client resource."""
    project = context.resources.gcp_project
    return bigquery.Client(project=project)

@resource
def gcs_client(context):
    """Cloud Storage client resource."""
    project = context.resources.gcp_project
    return storage.Client(project=project)

@resource
def pubsub_client(context):
    """Pub/Sub client resource."""
    project = context.resources.gcp_project
    return pubsub_v1.PublisherClient()'''


def _generate_ops(tasks: List[Dict[str, Any]], project: str, region: str) -> str:
    """Generate op definitions."""
    ops_code = "# Pipeline Ops\n"

    for task in tasks:
        ops_code += _generate_single_op(task, project, region)
        ops_code += "\n\n"

    return ops_code.rstrip()


def _generate_single_op(task: Dict[str, Any], project: str, region: str) -> str:
    """Generate code for a single op."""
    task.get("taskId")
    action = task.get("action", "")
    params = task.get("params", {})
    depends_on = task.get("dependsOn", [])

    # Parse action
    action_parts = action.split(".")
    if len(action_parts) < 3:
        return _generate_generic_op(task, project, region)

    service = action_parts[1]
    operation = action_parts[2]

    # Determine input dependencies. ``dep_<id>`` is an identifier position, not
    # data: it is the op's input name here and the *keyword argument* name
    # _generate_job emits at the call site. Both sides must come from the same
    # sanitize_identifier call or the job passes an argument the op never
    # declared — and an unsanitised id would break out of these quotes into the
    # module-level @op(...) decorator, which Dagster evaluates on import.
    if depends_on:
        dep_items = ", ".join([f'"dep_{sanitize_identifier(d)}": In(Nothing)' for d in depends_on])
        ins_def = f"ins={{{dep_items}}}, "
    else:
        ins_def = ""

    # Map to appropriate op
    if service == "bigquery":
        return _generate_bigquery_op(task, operation, params, ins_def)
    elif service == "gcs" or service == "storage":
        return _generate_gcs_op(task, operation, params, ins_def)
    elif service == "pubsub":
        return _generate_pubsub_op(task, operation, params, ins_def)
    else:
        return _generate_generic_op(task, project, region)


def _generate_bigquery_op(
    task: Dict[str, Any], operation: str, params: Dict[str, Any], ins_def: str
) -> str:
    """Generate BigQuery op code."""
    # The op's ``def`` name is a Python identifier; a raw taskId such as
    # ``load-orders`` emitted ``def load-orders(context):``.
    op_name = task_identifier(task.get("taskId"))

    if operation == "create_dataset":
        dataset_id = params.get("dataset_id", "unknown_dataset")
        location = params.get("location", "US")
        # The dataset reference is built by concatenation rather than a
        # generated f-string: repr() escapes quotes but NOT braces, so a ``{``
        # in dataset_id would survive into an f-string as a live expression
        # evaluated at op run.
        return f'''@op({ins_def}required_resource_keys={{"bigquery_client", "gcp_project"}})
def {op_name}(context):
    """Create BigQuery dataset: {escape_for_docstring(dataset_id)}"""
    client = context.resources.bigquery_client
    dataset = bigquery.Dataset(context.resources.gcp_project + "." + {py_str_literal(dataset_id)})
    dataset.location = {py_str_literal(location)}

    try:
        dataset = client.create_dataset(dataset, exists_ok=True)
        context.log.info(f"Created dataset {{{{dataset.dataset_id}}}}")
        return dataset.dataset_id
    except Exception as e:
        context.log.error(f"Failed to create dataset: {{{{e}}}}")
        raise'''

    elif operation == "query" or operation == "run_query":
        query_sql = params.get("query", "SELECT 1")
        # The SQL is DATA. The hand-rolled double-.replace() this had escaped
        # backslashes and double quotes but NOT newlines or triple quotes, so
        # an ordinary multi-line SELECT emitted an unterminated string literal
        # — and a ``"""`` in the query closed it and injected a statement.
        # repr() (via py_str_literal) picks its own quote style and escapes all
        # three, so the hand-written quotes around the splice are dropped.
        return f'''@op({ins_def}required_resource_keys={{"bigquery_client"}})
def {op_name}(context):
    """Run BigQuery query"""
    client = context.resources.bigquery_client
    query = {py_str_literal(query_sql)}

    try:
        query_job = client.query(query)
        results = query_job.result()
        row_count = results.total_rows
        context.log.info(f"Query completed: {{{{row_count}}}} rows")
        return row_count
    except Exception as e:
        context.log.error(f"Query failed: {{{{e}}}}")
        raise'''

    else:
        return _generate_generic_op(task, None, None)


def _generate_gcs_op(
    task: Dict[str, Any], operation: str, params: Dict[str, Any], ins_def: str
) -> str:
    """Generate Cloud Storage op code."""
    # Identifier position — same treatment as every other op emitter here.
    op_name = task_identifier(task.get("taskId"))

    if operation == "create_bucket" or operation == "ensure_bucket":
        bucket_name = params.get("bucket", "unknown-bucket")
        location = params.get("location", "US")

        return f'''@op({ins_def}required_resource_keys={{"gcs_client"}})
def {op_name}(context):
    """Create GCS bucket: {escape_for_docstring(bucket_name)}"""
    client = context.resources.gcs_client
    bucket = client.bucket({py_str_literal(bucket_name)})
    bucket.location = {py_str_literal(location)}

    try:
        if not bucket.exists():
            bucket.create()
            context.log.info(f"Created bucket {{bucket.name}}")
        else:
            context.log.info(f"Bucket {{bucket.name}} already exists")
        return bucket.name
    except Exception as e:
        context.log.error(f"Failed to create bucket: {{e}}")
        raise'''

    else:
        return _generate_generic_op(task, None, None)


def _generate_pubsub_op(
    task: Dict[str, Any], operation: str, params: Dict[str, Any], ins_def: str
) -> str:
    """Generate Pub/Sub op code."""
    # Identifier position — same treatment as every other op emitter here.
    op_name = task_identifier(task.get("taskId"))

    if operation == "create_topic":
        topic_name = params.get("topic", "unknown-topic")
        return f'''@op({ins_def}required_resource_keys={{"pubsub_client", "gcp_project"}})
def {op_name}(context):
    """Create Pub/Sub topic: {escape_for_docstring(topic_name)}"""
    client = context.resources.pubsub_client
    topic_path = client.topic_path(context.resources.gcp_project, {py_str_literal(topic_name)})

    try:
        topic = client.create_topic(request={{"name": topic_path}})
        context.log.info(f"Created topic {{topic.name}}")
        return topic.name
    except Exception as e:
        if "already exists" in str(e).lower():
            context.log.info(f"Topic {{topic_path}} already exists")
            return topic_path
        context.log.error(f"Failed to create topic: {{e}}")
        raise'''

    else:
        return _generate_generic_op(task, None, None)


def _generate_generic_op(task: Dict[str, Any], project: str, region: str) -> str:
    """Generate generic op."""
    op_name = task_identifier(task.get("taskId"))
    action = task.get("action")
    params = task.get("params", {})
    depends_on = task.get("dependsOn", [])

    if depends_on:
        # Identifier position on both sides — see _generate_single_op. The
        # leading ", " this used to carry emitted ``@op(, ins={...})``, which
        # does not parse, so it is gone: ins_def is now the whole argument list.
        dep_items = ", ".join([f'"dep_{sanitize_identifier(d)}": In(Nothing)' for d in depends_on])
        ins_def = f"ins={{{dep_items}}}"
    else:
        ins_def = ""

    # Both log lines drop the generated ``f`` prefix. repr() does not escape
    # braces, so with the f prefix kept a ``{`` anywhere in ``action`` (or in
    # the params repr) stayed a LIVE expression evaluated when the op runs.
    # The whole message is pre-rendered here and emitted as one escaped
    # literal; params round-trips through json.loads so the op still logs a
    # real mapping (splicing its repr also emitted ``f"Params: {}"`` — a
    # SyntaxError — for the empty default).
    action_log = py_str_literal(f"Action: {action}")
    return f'''@op({ins_def})
def {op_name}(context):
    """Generic op: {escape_for_docstring(action)}"""
    context.log.info({action_log})
    params = json.loads({json_literal(params)})
    context.log.info("Params: " + repr(params))
    return True'''


def _generate_job(
    contract_id: str, tasks: List[Dict[str, Any]], schedule: str, timezone: str
) -> str:
    """Generate job and schedule definitions."""
    # Build op call graph
    op_calls = []
    dependencies = {}

    for task in tasks:
        task_id = task.get("taskId")
        depends_on = task.get("dependsOn", [])
        # The call site and the ``def`` the op emitters write are the two sides
        # of the same name: both go through task_identifier on the same raw
        # value, so they agree. Deriving one of them any other way emits a
        # reference to a name the generated module never bound.
        op_name = task_identifier(task_id)

        if depends_on:
            # Two DIFFERENT names on one line, and they must not be conflated:
            # the ``dep_<id>`` keyword has to match the op's ``ins`` key (built
            # with sanitize_identifier in _generate_single_op), while the
            # ``<id>_result`` VALUE has to match the variable the upstream op
            # was bound to above (task_identifier). They diverge exactly on a
            # leading digit -- ``2024_load`` binds ``task_2024_load_result``
            # but sanitize_identifier yields ``_load_result``, a name the
            # module never defines. Worse, a sibling task literally named
            # ``_load`` makes that resolve, silently wiring the wrong upstream.
            dep_args = ", ".join(
                f"dep_{sanitize_identifier(dep)}={task_identifier(dep)}_result"
                for dep in depends_on
            )
            op_calls.append(f"    {op_name}_result = {op_name}({dep_args})")
            dependencies[task_id] = depends_on
        else:
            # Independent op
            op_calls.append(f"    {op_name}_result = {op_name}()")

    op_calls_str = "\n".join(op_calls)

    # Convert cron to Dagster schedule
    cron_schedule = _convert_schedule(schedule)

    # sanitize_identifier, not the local _sanitize_name below: the latter is a
    # weaker fork with no keyword guard and no empty-string guard, so a
    # contract id of ``class`` or ``""`` emitted ``def class():`` / ``def ():``.
    job_name = task_identifier(contract_id)

    # The tag value, the cron string and the timezone are all spliced into
    # calls at MODULE scope, which Dagster evaluates on plain import — a quote
    # break-out in any of them runs before a single op does. _convert_schedule
    # passes any string with >= 4 spaces through verbatim, so the cron field is
    # no safer than the other two.
    return f'''# Job definition
@job(
    resource_defs={{
        "gcp_project": gcp_project,
        "gcp_region": gcp_region,
        "bigquery_client": bigquery_client,
        "gcs_client": gcs_client,
        "pubsub_client": pubsub_client,
    }},
    tags={{
        "fluid": "auto-generated",
        "contract_id": {py_str_literal(contract_id)},
        "provider": "gcp",
    }},
)
def {job_name}():
    """{escape_for_docstring(contract_id)} pipeline on GCP."""
{op_calls_str}

# Schedule
{job_name}_schedule = ScheduleDefinition(
    job={job_name},
    cron_schedule={py_str_literal(cron_schedule)},
    execution_timezone={py_str_literal(timezone)},
)'''


def _convert_schedule(schedule: str) -> str:
    """Convert FLUID schedule to Dagster cron schedule."""
    # Handle special keywords
    schedule_lower = schedule.lower()
    if schedule_lower == "@hourly":
        return "0 * * * *"
    elif schedule_lower == "@daily":
        return "0 0 * * *"
    elif schedule_lower == "@weekly":
        return "0 0 * * 0"
    elif schedule_lower == "@monthly":
        return "0 0 1 * *"

    # Pass through cron expressions
    if schedule.count(" ") >= 4:
        return schedule

    # Default to daily
    return "0 2 * * *"


def _sanitize_name(name: str) -> str:
    """Sanitize name for Python identifier.

    Kept for its existing importers (``tests/test_gcp_codegen.py``); no emitter
    in this module still calls it. Every identifier this file generates now
    goes through ``codegen_utils.sanitize_identifier``, which additionally
    strips leading digits and guards keywords and the empty string.
    """
    import re

    return re.sub(r"[^a-zA-Z0-9_]", "_", name)
