# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Prefect Flow Generation for GCP Provider.

Generates Python flow code from FLUID contracts for Prefect on GCP.

Supports:
- BigQuery tasks with retries
- Cloud Storage operations
- Pub/Sub messaging
- Deployment configuration
"""

from datetime import datetime
from datetime import timezone as dt_timezone
from typing import Any, Dict, List

from fluid_build.providers.common.codegen_utils import (
    escape_for_docstring,
    json_literal,
    py_str_literal,
    task_identifier,
)


def generate_prefect_flow(contract: Dict[str, Any], project: str, region: str) -> str:
    """
    Generate Prefect flow Python code from FLUID contract.

    Args:
        contract: FLUID contract with orchestration section
        project: GCP project ID
        region: GCP region

    Returns:
        Python code for Prefect flow
    """
    orchestration = contract.get("orchestration", {})
    if not orchestration:
        raise ValueError("Contract missing orchestration section")

    tasks = orchestration.get("tasks", [])
    if not tasks:
        raise ValueError("Orchestration has no tasks")

    # Extract configuration
    contract_id = contract.get("id", "unknown")
    contract_name = contract.get("name", contract_id)
    schedule = orchestration.get("schedule", "0 2 * * *")
    timezone = orchestration.get("timezone", "UTC")

    # Filter provider action tasks
    provider_tasks = [t for t in tasks if t.get("type") == "provider_action"]

    # Generate flow code
    code = _generate_header(contract_id, contract_name, schedule, timezone, project, region)
    code += "\n\n"
    code += _generate_imports()
    code += "\n\n"
    code += _generate_config(project, region)
    code += "\n\n"
    code += _generate_tasks(provider_tasks, project, region)
    code += "\n\n"
    code += _generate_flow(contract_id, contract_name, provider_tasks)
    code += "\n\n"
    code += _generate_deployment(contract_id, contract_name, schedule, timezone)

    return code


def _generate_header(
    contract_id: str, contract_name: str, schedule: str, timezone: str, project: str, region: str
) -> str:
    """Generate file header with metadata."""
    # Contract-derived values are escaped so they cannot terminate the
    # surrounding triple-quoted docstring and inject a top-level statement that
    # Prefect would run the moment it imports the generated flow file.
    return f'''"""
FLUID Generated Prefect Flow: {escape_for_docstring(contract_name)}

Contract ID: {escape_for_docstring(contract_id)}
Schedule: {escape_for_docstring(schedule)}
Timezone: {escape_for_docstring(timezone)}
GCP Project: {escape_for_docstring(project)}
GCP Region: {escape_for_docstring(region)}

Auto-generated by FLUID Forge - DO NOT EDIT MANUALLY
Generated: {datetime.now(dt_timezone.utc).replace(tzinfo=None).isoformat()}Z
"""'''


def _generate_imports() -> str:
    """Generate import statements."""
    # ``json`` is imported because the generic-task body rebuilds its params
    # mapping with ``json.loads(...)`` (see _generate_generic_task).
    return """from prefect import flow, task
from prefect.deployments import Deployment
from prefect.server.schemas.schedules import CronSchedule
from google.cloud import bigquery, storage, pubsub_v1
import json
import logging
from datetime import timedelta

logger = logging.getLogger(__name__)"""


def _generate_config(project: str, region: str) -> str:
    """Generate configuration constants."""
    # Module-scope assignments: a quote in either value used to close the
    # hand-written literal and drop the remainder at column 0, where it runs on
    # plain import. py_str_literal (repr) supplies its own quotes.
    return f"""# GCP Configuration
GCP_PROJECT = {py_str_literal(project)}
GCP_REGION = {py_str_literal(region)}"""


def _generate_tasks(tasks: List[Dict[str, Any]], project: str, region: str) -> str:
    """Generate task definitions."""
    tasks_code = "# Prefect Tasks\n"

    for task_spec in tasks:
        tasks_code += _generate_single_task(task_spec, project, region)
        tasks_code += "\n\n"

    return tasks_code.rstrip()


def _generate_single_task(task_spec: Dict[str, Any], project: str, region: str) -> str:
    """Generate code for a single task."""
    task_spec.get("taskId")
    action = task_spec.get("action", "")
    params = task_spec.get("params", {})

    # Parse action
    action_parts = action.split(".")
    if len(action_parts) < 3:
        return _generate_generic_task(task_spec, project, region)

    service = action_parts[1]
    operation = action_parts[2]

    # Map to appropriate task
    if service == "bigquery":
        return _generate_bigquery_task(task_spec, operation, params)
    elif service == "gcs" or service == "storage":
        return _generate_gcs_task(task_spec, operation, params)
    elif service == "pubsub":
        return _generate_pubsub_task(task_spec, operation, params)
    else:
        return _generate_generic_task(task_spec, project, region)


def _generate_bigquery_task(
    task_spec: Dict[str, Any], operation: str, params: Dict[str, Any]
) -> str:
    """Generate BigQuery task code."""
    # A taskId becomes a generated ``def`` name, so it must be a legal, non-
    # keyword identifier. The same call is used by _generate_flow to emit the
    # call site, so the two sides always agree.
    task_id = task_identifier(task_spec.get("taskId"))

    if operation == "create_dataset":
        dataset_id = params.get("dataset_id", "unknown_dataset")
        location = params.get("location", "US")

        # The dataset id used to land inside a *generated* f-string, so a brace
        # in the value became a live replacement field evaluated at task run —
        # a channel repr() does not close. Dropping the f prefix and
        # concatenating an escaped literal closes it.
        return f'''@task(retries=3, retry_delay_seconds=30, timeout_seconds=600)
def {task_id}():
    """Create BigQuery dataset: {escape_for_docstring(dataset_id)}"""
    client = bigquery.Client(project=GCP_PROJECT)
    dataset = bigquery.Dataset(GCP_PROJECT + "." + {py_str_literal(dataset_id)})
    dataset.location = {py_str_literal(location)}

    try:
        dataset = client.create_dataset(dataset, exists_ok=True)
        logger.info(f"Created dataset {{dataset.dataset_id}}")
        return dataset.dataset_id
    except Exception as e:
        logger.error(f"Failed to create dataset: {{e}}")
        raise'''

    elif operation == "query" or operation == "run_query":
        # The hand-rolled .replace('"', '\\"') that used to sit here escaped
        # quotes but not backslashes, and in the wrong order: a query ending in
        # a backslash escaped the closing delimiter and left the whole module
        # unterminated. py_str_literal (repr) handles quotes, backslashes and
        # newlines, and supplies its own quoting — so the hand-written triple
        # quotes go with it.
        query_sql = params.get("query", "SELECT 1")

        return f'''@task(retries=3, retry_delay_seconds=30, timeout_seconds=1800)
def {task_id}():
    """Run BigQuery query"""
    client = bigquery.Client(project=GCP_PROJECT)
    query = {py_str_literal(query_sql)}

    try:
        query_job = client.query(query)
        results = query_job.result()
        row_count = results.total_rows
        logger.info(f"Query completed: {{row_count}} rows")
        return row_count
    except Exception as e:
        logger.error(f"Query failed: {{e}}")
        raise'''

    else:
        return _generate_generic_task(task_spec, None, None)


def _generate_gcs_task(task_spec: Dict[str, Any], operation: str, params: Dict[str, Any]) -> str:
    """Generate Cloud Storage task code."""
    # Identifier position — see _generate_bigquery_task.
    task_id = task_identifier(task_spec.get("taskId"))

    if operation == "create_bucket" or operation == "ensure_bucket":
        bucket_name = params.get("bucket", "unknown-bucket")
        location = params.get("location", "US")

        return f'''@task(retries=3, retry_delay_seconds=30, timeout_seconds=300)
def {task_id}():
    """Create GCS bucket: {escape_for_docstring(bucket_name)}"""
    client = storage.Client(project=GCP_PROJECT)
    bucket = client.bucket({py_str_literal(bucket_name)})
    bucket.location = {py_str_literal(location)}

    try:
        if not bucket.exists():
            bucket.create()
            logger.info(f"Created bucket {{bucket.name}}")
        else:
            logger.info(f"Bucket {{bucket.name}} already exists")
        return bucket.name
    except Exception as e:
        logger.error(f"Failed to create bucket: {{e}}")
        raise'''

    else:
        return _generate_generic_task(task_spec, None, None)


def _generate_pubsub_task(task_spec: Dict[str, Any], operation: str, params: Dict[str, Any]) -> str:
    """Generate Pub/Sub task code."""
    # Identifier position — see _generate_bigquery_task.
    task_id = task_identifier(task_spec.get("taskId"))

    if operation == "create_topic":
        topic_name = params.get("topic", "unknown-topic")

        return f'''@task(retries=3, retry_delay_seconds=30, timeout_seconds=300)
def {task_id}():
    """Create Pub/Sub topic: {escape_for_docstring(topic_name)}"""
    client = pubsub_v1.PublisherClient()
    topic_path = client.topic_path(GCP_PROJECT, {py_str_literal(topic_name)})

    try:
        topic = client.create_topic(request={{"name": topic_path}})
        logger.info(f"Created topic {{topic.name}}")
        return topic.name
    except Exception as e:
        if "already exists" in str(e).lower():
            logger.info(f"Topic {{topic_path}} already exists")
            return topic_path
        logger.error(f"Failed to create topic: {{e}}")
        raise'''

    else:
        return _generate_generic_task(task_spec, None, None)


def _generate_generic_task(task_spec: Dict[str, Any], project: str, region: str) -> str:
    """Generate generic task."""
    # Identifier position — see _generate_bigquery_task. This is the catch-all
    # branch every unmapped service falls through to, so it is the busiest
    # identifier site in the file.
    task_id = task_identifier(task_spec.get("taskId"))
    action = task_spec.get("action")
    params = task_spec.get("params", {})

    # Both logger lines kept an ``f`` prefix into the generated file, so a brace
    # in ``action`` — or anywhere in the ``params`` repr — became a live
    # expression evaluated at task run. Dropping the f prefix in favour of
    # lazy %-formatting closes that, and rebuilding params through
    # ``json.loads`` keeps it a mapping instead of a spliced expression.
    return f'''@task(retries=2, retry_delay_seconds=30)
def {task_id}():
    """Generic task: {escape_for_docstring(action)}"""
    logger.info("Action: %s", {py_str_literal(action)})
    logger.info("Params: %r", json.loads({json_literal(params)}))
    return True'''


def _generate_flow(contract_id: str, contract_name: str, tasks: List[Dict[str, Any]]) -> str:
    """Generate flow definition."""
    flow_name = _sanitize_name(contract_id)

    # Build task execution sequence
    task_executions = []
    task_results = {}

    for task in tasks:
        # Both the variable name and the call are Python identifiers in the
        # generated file, and they must resolve to exactly the name the task
        # emitters defined — same sanitize_identifier call, same result.
        task_id = task_identifier(task.get("taskId"))
        depends_on = task.get("dependsOn", [])

        if depends_on:
            # Wait for dependencies (in Prefect, execution order is implicit)
            for dep in depends_on:
                if dep not in task_results:
                    task_results[dep] = f"{dep}_result"
            task_executions.append(f"    {task_id}_result = {task_id}()")
        else:
            task_executions.append(f"    {task_id}_result = {task_id}()")

        task_results[task_id] = f"{task_id}_result"

    task_exec_str = "\n".join(task_executions)

    # ``description`` carries the raw contract name into a MODULE-SCOPE @flow
    # decorator kwarg — the severest data site in the file, since a quote there
    # dropped the remainder at column 0 where any import of the flow runs it.
    return f'''# Flow definition
@flow(
    name={py_str_literal(flow_name)},
    description={py_str_literal(contract_name)},
    retries=1,
    retry_delay_seconds=60,
)
def {flow_name}_flow():
    """{escape_for_docstring(contract_name)} flow on GCP."""
{task_exec_str}
    
    logger.info("Flow completed successfully")
    return True'''


def _generate_deployment(contract_id: str, contract_name: str, schedule: str, timezone: str) -> str:
    """Generate deployment configuration."""
    flow_name = _sanitize_name(contract_id)
    cron_schedule = _convert_schedule(schedule)

    # ``tags`` used to be assembled from hand-quoted text with the RAW contract
    # id spliced in; building the list here and emitting its repr escapes every
    # element at once (the idiom aws/codegen/airflow.py uses).
    tags = ["fluid", "auto-generated", "gcp", str(contract_id)]
    deployment_name = f"{flow_name}-deployment"
    # The two cprint lines kept an ``f`` prefix into the generated file, so a
    # brace in the schedule or timezone became a live expression at import.
    # Composing each message here and emitting ONE escaped literal drops the
    # inner f and closes the quote channel in the same move.
    schedule_msg = f"   Schedule: {cron_schedule} ({timezone})"
    run_msg = f"   Run: prefect deployment run '{flow_name}_flow/{deployment_name}'"

    return f"""# Deployment configuration
if __name__ == "__main__":
    deployment = Deployment.build_from_flow(
        flow={flow_name}_flow,
        name={py_str_literal(deployment_name)},
        version="1.0",
        tags={tags!r},
        schedule=CronSchedule(
            cron={py_str_literal(cron_schedule)},
            timezone={py_str_literal(timezone)},
        ),
        work_queue_name="default",
    )

    # To deploy: python {flow_name}_flow.py
    deployment.apply()

    success(f"Deployment created: {{deployment.name}}")
    cprint({py_str_literal(schedule_msg)})
    cprint({py_str_literal(run_msg)})"""


def _convert_schedule(schedule: str) -> str:
    """Convert FLUID schedule to cron schedule."""
    # Handle special keywords
    schedule_lower = schedule.lower()
    if schedule_lower == "@hourly":
        return "0 * * * *"
    elif schedule_lower == "@daily":
        return "0 0 * * *"
    elif schedule_lower == "@weekly":
        return "0 0 * * 0"
    elif schedule_lower == "@monthly":
        return "0 0 1 * *"

    # Pass through cron expressions
    if schedule.count(" ") >= 4:
        return schedule

    # Default to daily
    return "0 2 * * *"


def _sanitize_name(name: str) -> str:
    """Sanitize name for Python identifier.

    Delegates to the shared ``sanitize_identifier``. The local ``re.sub`` this
    replaces was a lossy copy that did not strip leading digits, so a contract
    id of ``2foo`` emitted ``def 2foo_flow():`` — a SyntaxError that killed the
    whole generated module. Kept as a named wrapper because it is part of this
    module's de-facto API (``tests/test_gcp_codegen.py`` imports it).
    """
    return task_identifier(name)
