# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Prefect Flow Generation for AWS Provider.

Generates Prefect 2.x flow Python code from FLUID contracts.

Supports:
- Tasks and flows
- Task dependencies
- AWS integrations
- Deployment configurations

Every contract-derived value spliced into the emitted source routes through
``providers/common/codegen_utils`` (``py_str_literal`` for data,
``sanitize_identifier`` for identifiers, ``escape_for_docstring`` for
docstrings). This is a sharper sink than the Airflow emitter: the splices land
inside *module-level* ``@flow`` / ``@task`` decorators, so an unescaped payload
runs on a plain ``import`` of the generated file — ``prefect deploy``, a
Prefect worker, or a developer opening it in a REPL.
"""

import json
from datetime import datetime
from datetime import timezone as dt_timezone
from typing import Any, Dict, List

from fluid_build.providers.common.codegen_utils import (
    escape_for_docstring,
    json_literal,
    py_str_literal,
    sanitize_identifier,
    task_identifier,
)


def generate_prefect_flow(contract: Dict[str, Any], account_id: str, region: str) -> str:
    """
    Generate Prefect 2.x flow Python code from FLUID contract.

    Args:
        contract: FLUID contract with orchestration section
        account_id: AWS account ID
        region: AWS region

    Returns:
        Python code for Prefect flow
    """
    orchestration = contract.get("orchestration", {})
    if not orchestration:
        raise ValueError("Contract missing orchestration section")

    tasks = orchestration.get("tasks", [])
    if not tasks:
        raise ValueError("Orchestration has no tasks")

    # Extract configuration
    contract_id = contract.get("id", "unknown")
    contract_name = contract.get("name", contract_id)
    schedule = orchestration.get("schedule", "0 2 * * *")
    timezone = orchestration.get("timezone", "UTC")

    # Filter provider action tasks
    provider_tasks = [t for t in tasks if t.get("type") == "provider_action"]

    # Generate flow code
    code = _generate_header(contract_id, contract_name, account_id, region)
    code += "\n\n"
    code += _generate_imports()
    code += "\n\n"
    code += _generate_tasks(provider_tasks, account_id, region)
    code += "\n\n"
    code += _generate_flow(contract_id, contract_name, provider_tasks)
    code += "\n\n"
    code += _generate_deployment(contract_id, contract_name, schedule, timezone)

    return code


def _generate_header(contract_id: str, contract_name: str, account_id: str, region: str) -> str:
    """Generate file header."""
    # The triple quotes below are the generated module docstring's own
    # delimiters, so the values are escaped rather than quoted: a `"""` in a
    # contract name would otherwise close the docstring and leave whatever
    # followed it as a top-level statement compiled on import.
    return f'''"""
FLUID Generated Prefect Flow: {escape_for_docstring(contract_name)}

Contract ID: {escape_for_docstring(contract_id)}
AWS Account: {escape_for_docstring(account_id)}
AWS Region: {escape_for_docstring(region)}

Auto-generated by FLUID Forge - DO NOT EDIT MANUALLY
Generated: {datetime.now(dt_timezone.utc).replace(tzinfo=None).isoformat()}
"""'''


def _generate_imports() -> str:
    """Generate import statements."""
    return """from prefect import flow, task
from prefect.deployments import Deployment
from prefect.server.schemas.schedules import CronSchedule
import boto3
import json
import logging
from typing import Dict, Any

logger = logging.getLogger(__name__)"""


def _generate_tasks(tasks: List[Dict[str, Any]], account_id: str, region: str) -> str:
    """Generate Prefect tasks."""
    tasks_code = "# Prefect Tasks\n\n"

    for task in tasks:
        tasks_code += _generate_single_task(task, account_id, region)
        tasks_code += "\n\n"

    return tasks_code.rstrip()


def _generate_single_task(task: Dict[str, Any], account_id: str, region: str) -> str:
    """Generate code for a single Prefect task."""
    task_id = task.get("taskId")
    action = task.get("action")
    params = task.get("params", {})

    # Parse action to determine service
    action_parts = action.split(".")
    service = action_parts[1] if len(action_parts) > 1 else "unknown"

    # Every splice below sits at module scope in the emitted file — the @task
    # decorator and the def it wraps are evaluated on a plain `import` — so
    # each contract value is routed through a codegen_utils escaper. repr()
    # brings its own quotes, hence no hand-written ones around the placeholders.
    task_id_literal = py_str_literal(task_id)
    description_literal = py_str_literal(f"Execute {action}")
    # The emitted logger line deliberately loses its `f` prefix. An f-string
    # that survives into the generated source turns a `{` in `action` into an
    # expression evaluated when the task runs, and repr() escapes quotes and
    # backslashes but NOT braces — so py_str_literal alone would not close it.
    executing_literal = py_str_literal(f"Executing: {action}")

    return f'''@task(
    name={task_id_literal},
    description={description_literal},
    retries=3,
    retry_delay_seconds=300,
)
def {_sanitize_task_name(task_id)}() -> Dict[str, Any]:
    """Execute {escape_for_docstring(action)}."""
    logger.info({executing_literal})
    params = json.loads({json_literal(params)})
    
    {_generate_task_implementation(action, service, region)}
    
    return {{"status": "success", "task_id": {task_id_literal}}}'''


def _generate_task_implementation(action: str, service: str, region: str) -> str:
    """Generate task implementation code."""
    # `region` reaches this generator from the contract on the plan path
    # (contract['region'] / exposes[].binding.location.region), so it is data,
    # not a constant. One literal, reused by every branch below — the
    # hand-written '...' around each placeholder are gone because repr()
    # supplies its own quotes.
    region_literal = py_str_literal(region)

    if service == "s3":
        return f"""# S3 operation
    s3_client = boto3.client('s3', region_name={region_literal})
    bucket = params.get("bucket")
    if bucket:
        try:
            s3_client.create_bucket(
                Bucket=bucket,
                CreateBucketConfiguration={{'LocationConstraint': {region_literal}}}
            )
            logger.info(f"Created S3 bucket: {{bucket}}")
        except s3_client.exceptions.BucketAlreadyOwnedByYou:
            logger.info(f"Bucket already exists: {{bucket}}")"""

    elif service == "glue":
        return f"""# Glue operation
    glue_client = boto3.client('glue', region_name={region_literal})
    
    if params.get("database"):
        database = params["database"]
        try:
            glue_client.create_database(
                DatabaseInput={{'Name': database}}
            )
            logger.info(f"Created Glue database: {{database}}")
        except glue_client.exceptions.AlreadyExistsException:
            logger.info(f"Database already exists: {{database}}")
    
    if params.get("table"):
        table = params["table"]
        database = params.get("database", "default")
        # TODO: Create table from params
        logger.info(f"Ensuring Glue table: {{database}}.{{table}}")"""

    elif service == "athena":
        return f"""# Athena operation
    athena_client = boto3.client('athena', region_name={region_literal})
    query = params.get("query")
    database = params.get("database", "default")
    
    if query:
        response = athena_client.start_query_execution(
            QueryString=query,
            QueryExecutionContext={{'Database': database}},
            ResultConfiguration={{
                'OutputLocation': params.get("outputLocation", "s3://athena-results/")
            }}
        )
        query_id = response['QueryExecutionId']
        logger.info(f"Started Athena query: {{query_id}}")
        
        # Wait for completion
        import time
        while True:
            result = athena_client.get_query_execution(QueryExecutionId=query_id)
            status = result['QueryExecution']['Status']['State']
            if status in ['SUCCEEDED', 'FAILED', 'CANCELLED']:
                logger.info(f"Query {{query_id}} status: {{status}}")
                break
            time.sleep(2)"""

    elif service == "redshift":
        return f"""# Redshift operation
    redshift_data = boto3.client('redshift-data', region_name={region_literal})
    sql = params.get("sql")
    cluster_id = params.get("cluster")
    database = params.get("database", "dev")
    
    if sql and cluster_id:
        response = redshift_data.execute_statement(
            ClusterIdentifier=cluster_id,
            Database=database,
            Sql=sql
        )
        logger.info(f"Executed Redshift SQL: {{response['Id']}}")"""

    elif service == "lambda":
        return f"""# Lambda operation
    lambda_client = boto3.client('lambda', region_name={region_literal})
    function_name = params.get("function")
    payload = params.get("payload", {{}})
    
    if function_name:
        response = lambda_client.invoke(
            FunctionName=function_name,
            InvocationType='RequestResponse',
            Payload=json.dumps(payload)
        )
        logger.info(f"Invoked Lambda: {{function_name}}")
        result = json.loads(response['Payload'].read())
        logger.info(f"Lambda result: {{result}}")"""

    else:
        # Same generated-f-string hazard as the task body above: the `f` is
        # dropped so a brace in `action` stays inert data. The `Params:` line
        # below keeps its `f` — {params} there is the generated function's own
        # local, not a generator-side splice.
        action_literal = py_str_literal(f"Action: {action}")
        return f"""# Generic provider action
    logger.info({action_literal})
    logger.info(f"Params: {{params}}")
    # TODO: Implement provider action execution"""


def _generate_flow(contract_id: str, contract_name: str, tasks: List[Dict[str, Any]]) -> str:
    """Generate Prefect flow definition."""
    # Build task execution with dependencies
    flow_body_lines = []
    task_vars = {}  # Map task_id to variable name

    for task in tasks:
        task_id = task.get("taskId")
        depends_on = task.get("dependsOn", [])
        # The `def` emitted by _generate_single_task and every reference built
        # here must come from the SAME call, or the flow body (and the wait_for
        # wiring below) names something the generated module never defined.
        task_func = _sanitize_task_name(task_id)

        # Create task call
        if depends_on:
            # Task with dependencies - use wait_for
            wait_for_tasks = [task_vars[dep] for dep in depends_on if dep in task_vars]
            if wait_for_tasks:
                wait_for_str = ", ".join(wait_for_tasks)
                flow_body_lines.append(
                    f"    {task_func}_result = {task_func}(wait_for=[{wait_for_str}])"
                )
            else:
                flow_body_lines.append(f"    {task_func}_result = {task_func}()")
        else:
            # Independent task
            flow_body_lines.append(f"    {task_func}_result = {task_func}()")

        task_vars[task_id] = f"{task_func}_result"

    # Collect all results
    all_results = list(task_vars.values())
    flow_body_lines.append(f"\n    return [{', '.join(all_results)}]")

    flow_body = "\n".join(flow_body_lines)

    # @flow is applied at import, so these kwargs are the same module-scope sink
    # as the @task ones: escaped literals, no hand-written quotes. The docstring
    # keeps its own `"""` delimiters and escapes the value instead.
    description_literal = py_str_literal(f"FLUID workflow for {contract_id}")
    starting_literal = py_str_literal(f"Starting FLUID workflow: {contract_name}")

    return f'''@flow(
    name={py_str_literal(contract_name)},
    description={description_literal},
    retries=2,
    retry_delay_seconds=600,
)
def {_sanitize_flow_name(contract_id)}_flow():
    """{escape_for_docstring(contract_name)} workflow."""
    logger.info({starting_literal})
{flow_body}'''


def _generate_deployment(contract_id: str, contract_name: str, schedule: str, timezone: str) -> str:
    """Generate Prefect deployment configuration."""
    cron_schedule = _convert_to_cron(schedule)
    # Identifier position: must stay byte-identical to the `def` emitted by
    # _generate_flow, so it goes through the same sanitiser.
    flow_name = _sanitize_flow_name(contract_id)

    # Built in Python and emitted with !r (the Airflow emitter's idiom) so the
    # whole list is one repr-escaped literal rather than three hand-quoted
    # items, one of which carries the contract id.
    tags = ["fluid", "auto-generated", str(contract_id)]

    deployment_name_literal = py_str_literal(f"{contract_id}-deployment")
    # Both confirmation lines lose the `f` prefix: `contract_name`, the
    # schedule and the timezone are all contract text, and this block runs at
    # module scope under `python <id>_flow.py`.
    deployed_literal = py_str_literal(f"Deployed: {contract_name}")
    schedule_literal = py_str_literal(f"Schedule: {cron_schedule} ({timezone})")

    return f"""# Deployment Configuration
if __name__ == "__main__":
    deployment = Deployment.build_from_flow(
        flow={flow_name}_flow,
        name={deployment_name_literal},
        schedule=CronSchedule(
            cron={py_str_literal(cron_schedule)},
            timezone={py_str_literal(timezone)}
        ),
        tags={tags!r},
        parameters={{}},
        work_queue_name="default",
    )
    
    deployment.apply()
    cprint({deployed_literal})
    cprint({schedule_literal})"""


def _sanitize_task_name(name: str) -> str:
    """Sanitize a taskId into the Python identifier the generated ``def`` uses.

    Delegates to the shared ``codegen_utils.sanitize_identifier``. What used to
    live here was a near-copy of it that dropped the keyword guard, so a taskId
    of ``class`` emitted ``def class() -> Dict[str, Any]:`` and the entire flow
    file was a ``SyntaxError`` on import. Routing every identifier through one
    function also guarantees the ``def`` and its call site cannot drift apart.

    NB the shared helper *strips* a leading digit (``1a`` -> ``a``) where this
    used to *prefix* one (``1a`` -> ``task_1a``). Both are legal identifiers,
    and both sides of every pair now resolve through this call, so the emitted
    flow is unaffected.
    """
    return task_identifier(name)


def _sanitize_flow_name(name: str) -> str:
    """Sanitize flow name for Prefect."""
    return _sanitize_task_name(name)


def _convert_to_cron(schedule: str) -> str:
    """Convert schedule to cron format."""
    # If already cron, return as-is
    if schedule.count(" ") >= 4:
        return schedule

    # Handle common presets
    presets = {
        "daily": "0 2 * * *",
        "hourly": "0 * * * *",
        "weekly": "0 2 * * 0",
        "monthly": "0 2 1 * *",
    }

    return presets.get(schedule.lower(), "0 2 * * *")
