# Copyright 2024-2026 Agentics Transformation Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""SLSA L2 in-toto attestation for FLUID bundles.

Emits an in-toto v1.0 Statement with an SLSA v1.0 Provenance predicate
next to a tgz bundle. Pairs with :mod:`cli._signing` — when both
``--sign`` and ``--attest`` are set, the attestation file is also
signed via ``cosign attest-blob``.

Reference specs:
- in-toto Statement v1.0: https://in-toto.io/Statement/v1
- SLSA Provenance v1.0:    https://slsa.dev/provenance/v1
- SLSA spec levels:        https://slsa.dev/spec/v1.0/levels

**What SLSA Level 2 requires that this emitter provides:**

- The attestation is generated by a trusted build service (the CI
  runner) — not the developer's laptop. Callers that invoke
  ``_collect_run_metadata()`` from inside a CI job get the CI run ID
  + build URL in ``runDetails.metadata``; local dev invocations fall
  back to a UUID with a ``localhost`` builder.id that signals
  "off-platform build".
- The source material (contract repo + git SHA) is recorded in
  ``buildDefinition.resolvedDependencies`` so verifiers can trace
  the bundle back to a specific commit.
- Every input to the build process is declared in
  ``buildDefinition.externalParameters``; a verifier can re-run and
  compare. We record the bundle digest (SHA-256) as the primary key.

**What SLSA Level 3+ requires that we do NOT yet provide** (follow-up
work, documented here so the gap is explicit):
- Hermetic, ephemeral, isolated build environment (Level 3).
- Two-party review on every change that affects the build (Level 3).
- Build service itself provides the attestation (Level 4; requires
  control plane support).

The emitter is provider-agnostic — works from GitHub Actions, GitLab
CI, Jenkins, CircleCI, Bitbucket, Azure DevOps, Tekton, local dev, or
an offline box. CI-specific metadata is sourced from env vars with
sane fallbacks.
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import subprocess
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from fluid_build.cli._common import CLIError

logger = logging.getLogger(__name__)

# in-toto Statement envelope type. Stable URI across in-toto v1.x.
_INTOTO_STATEMENT_TYPE = "https://in-toto.io/Statement/v1"
# SLSA Provenance predicate type. Stable for SLSA v1.0; bumping SLSA
# version would change this URI and the internal structure.
_SLSA_PROVENANCE_PREDICATE_TYPE = "https://slsa.dev/provenance/v1"
# Our build-type URI — identifies the builder (fluid-build bundle)
# and its version. The version suffix lets verifiers pin to a
# specific fluid-build release's provenance schema.
_FLUID_BUILD_TYPE_V1 = "https://fluid-build.io/bundle-provenance/v1"


def _sha256_file(path: Path) -> str:
    """Return the hex SHA-256 of a file's bytes.

    Chunked read so large bundles don't blow up memory. The digest
    here is the one embedded in the attestation's
    ``subject[0].digest.sha256``; verifiers re-compute this to bind
    the attestation to this specific bundle and reject tampering.
    """
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _git_head_sha(contract_dir: Path) -> Optional[str]:
    """Return ``git rev-parse HEAD`` for the contract repo, or None.

    Best-effort: if ``git`` isn't on PATH or the directory isn't a git
    repo, returns None rather than raising — off-repo builds are
    legitimate (e.g. a contract authored in a fresh tmpdir).
    """
    try:
        completed = subprocess.run(  # noqa: S603 — argv list, shell=False
            ["git", "-C", str(contract_dir), "rev-parse", "HEAD"],
            shell=False,
            check=False,
            capture_output=True,
            text=True,
            timeout=10,
        )
        if completed.returncode == 0:
            return completed.stdout.strip() or None
    except (FileNotFoundError, PermissionError, subprocess.TimeoutExpired):
        pass
    return None


def _git_remote_url(contract_dir: Path) -> Optional[str]:
    """Return ``git config --get remote.origin.url`` or None.

    The remote URL goes into ``resolvedDependencies[0].uri`` so
    verifiers know WHICH repo the bundle came from. Off-repo builds
    fall through to None.
    """
    try:
        completed = subprocess.run(  # noqa: S603
            ["git", "-C", str(contract_dir), "config", "--get", "remote.origin.url"],
            shell=False,
            check=False,
            capture_output=True,
            text=True,
            timeout=5,
        )
        if completed.returncode == 0:
            url = completed.stdout.strip()
            return url or None
    except (FileNotFoundError, PermissionError, subprocess.TimeoutExpired):
        pass
    return None


def _collect_run_metadata() -> Dict[str, Any]:
    """Detect the ambient CI system + return run-identifying metadata.

    Priority order (first match wins):
    1. GitHub Actions — GITHUB_RUN_ID + GITHUB_SERVER_URL/REPO
    2. GitLab CI — CI_JOB_ID + CI_JOB_URL
    3. CircleCI — CIRCLE_WORKFLOW_ID + CIRCLE_BUILD_URL
    4. Azure DevOps — BUILD_BUILDID + BUILD_BUILDURI
    5. Bitbucket Pipelines — BITBUCKET_BUILD_NUMBER + BITBUCKET_GIT_HTTP_ORIGIN
    6. Jenkins — BUILD_ID + BUILD_URL
    7. Fallback — generate a UUID; builder.id = "localhost".

    Returns a dict suitable for inclusion in ``runDetails``:
        {"builder": {"id": "..."}, "metadata": {"invocationId": "..."}}.
    """
    env = os.environ

    # GitHub Actions
    if env.get("GITHUB_RUN_ID"):
        server = env.get("GITHUB_SERVER_URL", "https://github.com")
        repo = env.get("GITHUB_REPOSITORY", "unknown/unknown")
        return {
            "builder": {"id": f"{server}/{repo}/.github/workflows@refs/heads/main"},
            "metadata": {
                "invocationId": (f"{server}/{repo}/actions/runs/{env['GITHUB_RUN_ID']}"),
                "startedOn": env.get("GITHUB_STARTED_AT") or _utc_now_iso(),
            },
        }

    # GitLab CI
    if env.get("CI_JOB_ID"):
        return {
            "builder": {
                "id": env.get(
                    "CI_SERVER_URL",
                    "https://gitlab.com",
                )
                + "/ci"
            },
            "metadata": {
                "invocationId": env.get(
                    "CI_JOB_URL",
                    f"gitlab-ci-job-{env['CI_JOB_ID']}",
                ),
                "startedOn": _utc_now_iso(),
            },
        }

    # CircleCI
    if env.get("CIRCLE_WORKFLOW_ID") or env.get("CIRCLE_BUILD_NUM"):
        return {
            "builder": {"id": "https://circleci.com/workflows"},
            "metadata": {
                "invocationId": env.get(
                    "CIRCLE_BUILD_URL",
                    f"circleci-build-{env.get('CIRCLE_BUILD_NUM', 'unknown')}",
                ),
                "startedOn": _utc_now_iso(),
            },
        }

    # Azure DevOps
    if env.get("BUILD_BUILDID"):
        return {
            "builder": {"id": "https://dev.azure.com/pipelines"},
            "metadata": {
                "invocationId": env.get(
                    "BUILD_BUILDURI",
                    f"azdo-build-{env['BUILD_BUILDID']}",
                ),
                "startedOn": _utc_now_iso(),
            },
        }

    # Bitbucket Pipelines
    if env.get("BITBUCKET_BUILD_NUMBER"):
        return {
            "builder": {"id": "https://bitbucket.org/pipelines"},
            "metadata": {
                "invocationId": (
                    f"{env.get('BITBUCKET_GIT_HTTP_ORIGIN', 'bitbucket://unknown')}"
                    f"/addon/pipelines/home#!/results/{env['BITBUCKET_BUILD_NUMBER']}"
                ),
                "startedOn": _utc_now_iso(),
            },
        }

    # Jenkins
    if env.get("BUILD_ID") and env.get("JENKINS_URL"):
        return {
            "builder": {"id": env.get("JENKINS_URL", "jenkins://unknown")},
            "metadata": {
                "invocationId": env.get(
                    "BUILD_URL",
                    f"jenkins-build-{env['BUILD_ID']}",
                ),
                "startedOn": _utc_now_iso(),
            },
        }

    # Fallback — off-platform build (local dev, one-shot script).
    # builder.id = "localhost" signals "do not trust this for SLSA L2".
    return {
        "builder": {"id": "localhost"},
        "metadata": {
            "invocationId": f"local-{uuid.uuid4()}",
            "startedOn": _utc_now_iso(),
        },
    }


def _utc_now_iso() -> str:
    """RFC 3339 UTC timestamp — the SLSA-recommended format."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def build_attestation(
    bundle_path: str,
    *,
    bundle_digest: Optional[str] = None,
    contract_dir: Optional[str] = None,
    extra_external_params: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Build a complete in-toto v1 Statement with SLSA Provenance v1.

    Arguments:
      bundle_path: Path to the bundle being attested. Must exist and
        be a regular file.
      bundle_digest: Pre-computed SHA-256 hex digest of the bundle.
        If omitted, recomputed here. Pass-in saves the second read
        when the caller already computed the digest during
        ``build_bundle_tgz``.
      contract_dir: Path to the contract repo root (for git SHA /
        remote URL discovery). Defaults to the bundle's parent dir.
      extra_external_params: Caller-supplied additions to
        ``buildDefinition.externalParameters``. Lets bundle.py add
        format/CLI flags to the provenance without this helper
        needing to know about the full fluid CLI surface.

    Returns a Python dict ready to be serialised to JSONL at
    ``<bundle>.intoto.jsonl``.

    Raises CLIError for malformed inputs (missing bundle).
    """
    bundle = Path(bundle_path).resolve()
    if not bundle.exists():
        raise CLIError(2, "attestation_bundle_missing", {"path": str(bundle)})
    if not bundle.is_file():
        raise CLIError(2, "attestation_bundle_not_file", {"path": str(bundle)})

    digest = bundle_digest or _sha256_file(bundle)
    cd = Path(contract_dir).resolve() if contract_dir else bundle.parent
    git_sha = _git_head_sha(cd)
    git_url = _git_remote_url(cd)
    run_meta = _collect_run_metadata()

    # buildDefinition.resolvedDependencies: where the SOURCE material
    # came from. If we have a git SHA, we add an entry for the repo +
    # commit; otherwise we fall back to the contract-dir absolute path.
    resolved_deps: List[Dict[str, Any]] = []
    if git_sha and git_url:
        resolved_deps.append(
            {
                "uri": f"git+{git_url}@refs/heads/HEAD",
                "digest": {"gitCommit": git_sha},
            }
        )
    elif git_sha:
        resolved_deps.append(
            {
                "uri": f"file://{cd}",
                "digest": {"gitCommit": git_sha},
            }
        )

    external_params = {
        "bundleOut": str(bundle),
        "bundleDigest": f"sha256:{digest}",
    }
    if extra_external_params:
        # Caller-supplied values win — they're more specific (format
        # flag, workdir, signing mode, etc.).
        external_params.update(extra_external_params)

    statement: Dict[str, Any] = {
        "_type": _INTOTO_STATEMENT_TYPE,
        "subject": [
            {
                "name": bundle.name,
                "digest": {"sha256": digest},
            }
        ],
        "predicateType": _SLSA_PROVENANCE_PREDICATE_TYPE,
        "predicate": {
            "buildDefinition": {
                "buildType": _FLUID_BUILD_TYPE_V1,
                "externalParameters": external_params,
                "resolvedDependencies": resolved_deps,
            },
            "runDetails": run_meta,
        },
    }
    return statement


def write_attestation(
    bundle_path: str,
    *,
    attest_out: Optional[str] = None,
    bundle_digest: Optional[str] = None,
    contract_dir: Optional[str] = None,
    extra_external_params: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Build + write an attestation file next to the bundle.

    Output path defaults to ``<bundle>.intoto.jsonl`` — the JSONL
    suffix follows in-toto convention (one statement per line, so
    multiple attestations can append cleanly; we emit exactly one).

    Returns the rendered statement dict + the written path, so
    callers can log the location or chain into cosign attest-blob.
    """
    statement = build_attestation(
        bundle_path,
        bundle_digest=bundle_digest,
        contract_dir=contract_dir,
        extra_external_params=extra_external_params,
    )
    bundle = Path(bundle_path).resolve()
    out_path = (
        Path(attest_out).resolve()
        if attest_out
        else bundle.with_suffix(bundle.suffix + ".intoto.jsonl")
    )
    # Canonical JSON on a single line, as per in-toto JSONL convention.
    out_path.write_text(
        json.dumps(statement, sort_keys=True, separators=(",", ":")) + "\n",
        encoding="utf-8",
    )
    logger.info(
        "attestation_written",
        extra={
            "path": str(out_path),
            "subject_digest": f"sha256:{statement['subject'][0]['digest']['sha256']}",
        },
    )
    return {"path": str(out_path), "statement": statement}


__all__ = [
    "build_attestation",
    "write_attestation",
]
